- Source/API/CBLModel.m
- Source/API/CBLModel_Internal.h
- Unit-Tests/Model_Tests.m
* Not checking the existence of the document when the model is new.
* Include API_ModelAwakeFromInitializer unit test.
#521
> Fix awakeFromInitializer document assertion fail (#521)

- Source/API/CBLModel.m
- Source/API/CBLModelFactory.h
- Source/API/CBLModelFactory.m
- Unit-Tests/Model_Tests.m
based on the mapping available in database.modelFactory
I tried to write a unit test for this new feature, but I couldn't run the unit tests to make sure it passes because I needed a signing identity. And I'm not sure it's actually correct because if you're doing real unit testing then database won't have a proper implementation of modelFactory that would be necessary for this test to pass.
> Adding a way to set the type of a new document automatically

- Source/API/CBLManager.m
- Source/CBLDatabase+Internal.h
- Source/CBLDatabase+Internal.m
- Source/CBL_Replicator.m
- Unit-Tests/Replication_Tests.m
* When replacing a database, creating a local checkpoint document containing the replacing database's localUUID (ID before getting replaced).
* When a replicator fetches remote checkpoint document to setup the last sequence info, if the last sequence is nil, try to get the imported last sequence which is obtained by using the localUUID stored in the local checkpoint document if it's available.
* Added test11_ReplicationWithReplacedDatabase unit test.
#406
> Import last seq for replication when replace a db (#406)

- Source/API/Extras/CBLIncrementalStore.h
- Source/API/Extras/CBLIncrementalStore.m
- Unit-Tests/IncrementalStore_Tests.m
CBLIncrementalStore - Utilize CBLQueryBuilder and add relationship search
- Use CBLQueryBuilder to fetch documents with predicates that do not have relationship keypath, otherwise fall back to the old way of using view and post filtering.
- Scan the original predice to generate a new predicate with template and a variable dictionary.
- Refator executeRequest:request:context:error method by seperating out each type of requests into its own method.
- Update unit tests
#571
> CBLIncrementalStore - Utilize CBLQueryBuilder and add relationship search (#571)

- Source/API/CBLDatabase.m
- Source/API/CBLDocument.m
- Source/API/CouchbaseLitePrivate.h
- Source/CBLDatabase+Internal.m
- Unit-Tests/Database_Tests.m
This didn't use to work correctly because the CBLDocument's currentRevision didn't
update to the new revision after the first update; then the second update would use
an obsolete _rev and fail with a conflict.
Added code to inform the CBLDocument immediately, even during a transaction, but
prevent the change notification from being posted till the transaction ends.
Fixes #256
> Allow a doc to be updated more than once in a single transaction

- Source/CBL_Router+Handlers.m
- Source/CBL_Router.m
- Unit-Tests/Router_Tests.m
- Based on CouchDB spec (http://wiki.apache.org/couchdb/HTTP_view_API), the stale option can be 'ok' or 'update_after'.
- If there is no stale specified or if the view has never updated its index before (first time), the index will be updated first. The result will be queried and returned after the index is updated.
- If stale=ok is set, the view will not update its index and the result will be returned as is.
- If stale=update_after, the view will return the result and then update its index after.
#584
> Add stale parameter support on view query requests

- Source/API/CBLView.h
> Fixed typo in CBLView documentation

- Source/API/CBLQuery.h
- Source/API/CBLQuery.m
- Unit-Tests/View_Tests.m
* Added a method called 'queryOptionsChanged', used for notifying LiveQuery that query params were changed and LiveQuery should re-run the query from scratch.
* Current I didn't reset the rows properties before re-run the query. Assuming that a user is observing rows property, by not resetting the rows property, users will not get any notification before the new re-run query result is done.
#596
> Add a method to notify LiveQuery when query options changed

- Source/API/CBLQuery.m
- Unit-Tests/View_Tests.m
Adding a new document which will not get emitted prior to creating a live query object could cause the _lastSequence tracked by the live query object equal to the database lastsequence (e.g. both are one). This could happen easily during the first luanch of the app and the database is fresh.
When the above situation happens, _willUpdate flag will never get reset as the update method will return immedidately before the flag is reset due to an if check at the top. As a result, the live query stops updating itself when there are new documents added to the database as the databaseChanged: call back method will return immdiately when it sees _willUpdate flag = YES.
#542
> Reset _willUpdate at the top of the update method

- Source/CBL_SQLiteStorage.m
- Source/CBL_SQLiteViewStorage.m
- Unit-Tests/View_Tests.m
This allows CBL to work with a SQLite build that doesn't include the fts3 or rtree modules
(for example, a stock build of SQLCipher.)
It probably also speeds up database creation somewhat.
Also, I noticed we didn't have any unit tests for geo anymore, so I went back in time and
restored the old one.
> Don't create SQLite FTS or RTree tables until needed

- Source/API/CBLModel+Properties.m
- Source/API/CBLModel.h
- Source/API/CBLModel.m
- Source/API/CBLModelArray.h
- Source/API/CBLModelFactory.h
- Source/API/CBLModelFactory.m
- Source/API/CBLQuery.m
- Source/API/CBLView.m
- Source/API/CouchbaseLitePrivate.h
- Unit-Tests/Model_Tests.m
* -[CBLModel findInverseOfRelation:fromClass:] explicitly computes an
inverse relation.
* An array-of-models-valued property can be declared as a computed
inverse relation by overriding +inverseRelationForArrayProperty or by
implementing +{property}InverseRelation.
See the doc-comments and issue #606 for more details.
Fixes #606
> Added CBLModel support for inverse relations [API CHANGE]

- CouchbaseLite.xcodeproj/project.pbxproj
- Source/API/CBLManager.m
- Source/API/CBLReplication.m
- Source/CBLCookieStorage.h
- Source/CBLCookieStorage.m
- Source/CBLDatabase+Internal.h
- Source/CBLDatabase+Internal.m
- Source/CBLRemoteRequest.h
- Source/CBLRemoteRequest.m
- Source/CBL_Puller.m
- Source/CBL_Replicator.h
- Source/CBL_Replicator.m
- Source/ChangeTracker/CBLChangeTracker.h
- Source/ChangeTracker/CBLChangeTracker.m
- Source/ChangeTracker/CBLSocketChangeTracker.m
- Source/ChangeTracker/CBLWebSocketChangeTracker.m
- Unit-Tests/CookieStorage_Tests.m
- Unit-Tests/Replication_Tests.m
Implement CBLCookieStorage:
* Stores cookies in the local checkpoint document. Each storage is referenced by a unique store key given when initializing the cookie storage instance. When integrating with the CBL_Replicator, the unique store key will be remoteCheckpointDocID.
* Implement the most of the feature sets of NSHTTPCookieStorage except the following 2 features: NSHTTPCookieAcceptPolicyOnlyFromMainDocumentDomain policy and setCookies:forURL:mainDocumentURL: method.
* Simply handle multiple thread access by using synchronized directive.
* Include a Unit Test file named CookieStorage_tests.m.
Replicator Integration:
* CBLRemoteRequest now has a cookieStorage property. If the cookie storage is set, the remote request object will get the cookies from the specified storage and set the …
> Feature/issue #543 Implement a cookie store per replicator

- Source/ChangeTracker/CBLSocketChangeTracker.m
See #622 for details on this.
Short version: `-my_proxySettings` returned the wrong proxy settings for `CFReadStreamSetProperty()` to use.
> Fixed CBLSocketChangeTracker to use correct OS proxy settings

- Source/API/CBLReplication.m
Added a little trick to retain itself at the beginning of the method.
> Prevent CBLReplicator to be released when the bg notification is called

- Source/CBLMisc.m
- Source/CBLRemoteRequest.h
- Source/CBLRemoteRequest.m
- Source/CBL_Replicator.h
- Source/CBL_Replicator.m
- Attempt to connect to the remote url when the reachability reports not-reachable. If an offline error returns, bring the replicator offline. Otherwise, bring the replicator online.
- Used request timeout of 10 seconds.
- Added autoRetry parameter to CBLRemoteRequest to be able to enable/disable retry feature; set auto retry to NO when trying to check if the server is reachable nor not.
- Extended NSURLErrorCannotConnectToHost, NSURLErrorCannotFindHost, and NSURLErrorNetworkConnectionLost to the CBLMisc.CBLIsOfflineError method.
#536
> Try to connect when rechability reports not-reachable

- Source/API/CBLQuery.h
- Source/CBLDatabase+Internal.m
- Unit-Tests/Database_Tests.m
In this mode an all-docs query returns docs in order by sequence number.
The startKey and endKey are interpreted as sequence numbers.
Note: Descending order isn't yet supported.
> API: Added kCBLBySequence to CBLAllDocsOptions (aka "changes feed")

- Source/API/CBLReplication.m
- Source/CBL_Replicator.m
- Unit-Tests/Replication_Tests.m
- In CBL_Replicator's stop method, post progress changed notification after calling stopped.
- Refactor CBLReplication's stop method to just calling stop method on the background replicator.
- The rest of the logic including forgetting the replicator and setting _started variable will be done in the updateStatus:error:processed:ofTotal: serverCert: method after getting the progress changed notitification after the replication get stopped.
#639
> Fix stop idle replicator not getting change notification

- Unit-Tests/Router_Tests.m
Add POST all_docs with keys in the body to confirm that the issue doesn't exist.
#356
> Add all_docs with keys body test case

- Source/CBL_BlobStore.m
- Not pre-opening the stream for non-encrypted BlobStore while getting an InputStream by a blob key.
- This helps reduce number of opened file descriptors when pushing high volumes of documents with attachments in multipart mode as each opened stream will get queued up into an input array of the CBLMultiStreamWriter.
#649
> Not pre-open stream in CBL_BlobStore's blobInputStreamForKey

- Source/API/CBLAttachment.m
- Source/CBL_BlobStore.m
NSDataReadingMappedIfSafe option can keep the file descriptors of the attachments open if the client application keeps holding the NSData object returned by CBLAttachment.content. For a very big attachment, alternatively, users can call contentURL and read the NSData with the NSDataReadingMappedIfSafe option themselves.
Changes:
1. Remove NSDataReadingMappedIfSafe option from  CBLAttachment.content method.
2. Still keep NSDataReadingMappedIfSafe option in the CBL_BlobStore.blobForKey() method as it gets used internally and no retaining NSData returned by the method.
3. Still keep NSDataReadingMappedIfSafe option in the CBL_BlobStore.blobData() method as the method doesn't get called by any codes.
#649
> Remove NSDataReadingMappedIfSafe when reading attachment content

- Source/CBLMisc.m
Change docid prefix from '!' to '-'. Using '!' doesn't work with sync function for the case of using the docid to construct a channel name. Sync gateway doesn't allow '!' as part of the channel name.
#661
> Change docid prefix

- Source/API/Extras/CBLIncrementalStore.m
- Unit-Tests/IncrementalStore_Tests.m
- Store embeded array of doc ids in the documents for many-to-many relationship.
- Bug fix: add relationship name as part of to-many inverse key view name.
- Small code clean up.
#638
> Add CBLIS support for many-to-many relationship

- Source/CBLMultipartUploader.h
- Source/CBLMultipartUploader.m
- Source/CBL_Pusher.m
Refactor the CBLMultipartUploader's init method to accept a block for creating a new mutipart writer object instead of a multipart writer object that cannot be reused when doing retry.
#665
> Fix multipart streams need to be recreated when doing retry

- Source/CBLBulkDownloader.m
- Source/CBLDatabase+Attachments.m
- Source/CBLDatabase+Insertion.m
- Source/CBL_Pusher.m
- Source/CBL_SQLiteStorage.m
- Unit-Tests/Replication_Tests.m
Two related issues have been fixed:
1. Correct minRevPos value when stripping the (non modified) attachments. This corrects the performance optimization when pushing documents that have non-modified attachments.
2. Applying a patch from @snej that "if the attachment is a stub, and the parent revision's JSON isn't known, but the attachment exists locally (based on its digest), just leave the stub alone".
#672
> Fix pulling documents with sub attachments failure

- Source/API/CBLDatabase.m
- Source/API/CBLManager.h
- Source/API/CBLManager.m
- Source/API/CouchbaseLitePrivate.h
- Source/CBLDatabase+Attachments.h
- Source/CBLDatabase+Attachments.m
- Source/CBLDatabase+Internal.h
- Source/CBLDatabase+Internal.m
- Source/CBLMisc.h
- Source/CBLMisc.m
- Source/CBL_ForestDBStorage.mm
- Source/CBL_SQLiteStorage.m
- Source/CBL_Storage.h
- Unit-Tests/Replication_Tests.m
- Unit-Tests/ViewInternal_Tests.m
- SQLite storage uses the 1.0 layout:
Database: .../DB_NAME.cblite
Attachments: .../DB_NAME attachments/
- ForestDB storage uses the new bundle layout with .cblite folder name extension:
Database: .../DB_NAME.cblite/db.forest
Attachments: .../DB_NAME.cblite/attachments/
- Set SQLite scheme version to 101 (non-backward compatible). Bumped non-backward version check to 200.
#676
> Backout the database file layout for SQLite storage

- Source/CBLDatabase+Internal.m
- Source/CBLRouter+Changes.m
- Source/CBL_ForestDBStorage.mm
- Source/CBL_Revision.h
- Source/CBL_Revision.m
- Source/CBL_SQLiteStorage.m
- Source/CBL_StorageTypes.h
- Unit-Tests/Router_Tests.m
- Descending mode will be only working when the feed mode is normal mode. The bad param error will be returned when using the descending mode with continuous and long poll mode.
- Currently ForestDB storage doesn't support this option. The not implemented error will be returned. (https://github.com/couchbase/couchbase-lite-ios/issues/641).
#107
> Fix REST API getting _changes feed in descending mode

- Source/API/CBLReplication.m
- Rename _pendingCookies to _bg_pendingCookies.
- Wrap the code that access _bg_replicator and _bg_pendingCookies in the -tellReplicatorAndWait block.
> Fix threading issue in CBLReplication -setCookieNamed: and deleteCookieNamed: method

- Source/API/CBLReplication.m
- Unit-Tests/Replication_Tests.m
- In CBLReplication -stop method, before returning, wait until the background stop notification comes.
- In CBLReplication -restart method, spin the -start method call into the next runloop or the next dispatching if the dispatch queue is used.
#696
> Fix replicator restart issue

- Source/API/CBLQuery+FullTextSearch.h
- Source/API/CBLQuery+FullTextSearch.m
- Source/API/CouchbaseLitePrivate.h
- Source/CBL_SQLiteViewStorage.m
- Unit-Tests/ViewInternal_Tests.m
Was accidentally removed during ForestDB storage development.
These aren't supported yet with ForestDB but are with SQLite.
(Most of the diffs are just restoring code from release/1.0.4.)
Fixes #709
> Restore deleted CBLQuery fullTextSnippets/Ranking API

- Source/API/CBLRevision.m
- Unit-Tests/Database_Tests.m
The UnsavedRevision.properties propery is declared as copy and that causes an issue that the new NSMutableDictionary object set to the property is changed to an immutable one at runtime by the SDK. Instead of synthesizing, implementing a pair get/set method with doing mutableCopy instead.
#718
> Fix UnsavedRevision.properties synthesizing

- Source/CBL_SQLiteStorage.m
- Unit-Tests/DatabaseInternal_Tests.m
Fixed bug #714 in SQLLiteStorage/_createDocNumericID that should insert or ignore that was returning -1 when it really should return the documents row id. For a unit test to call _createDocNumericID twice and fail correctly I had to add a function to clear the document from the key cache _docIDs.
> Fix error re-adding a document after it's been purged.

- Source/CBL_Puller.m
- Source/CBL_Replicator.h
- Source/CBL_Replicator.m
- Unit-Tests/ReplicatorInternal_Tests.m
Defer initialization of cookieStorage because this has the side effect
of setting the remoteCheckpointDocID, and we don't want to do that until
properties like the filter and filterParams are set up.
Fixes #728
> Fix for replicators not getting distinct checkpoints

- Source/CBL_ForestDBViewStorage.mm
- Unit-Tests/ViewInternal_Tests.m
- In CocoaIndexer, check to filter out a design doc.
- Update ViewInternal_Tests's -createViewNames to assert if there is a design doc get indexed.
#727
> ForestDBViewStorage, filter out _design docs when indexing

- Source/API/Extras/CBLIncrementalStore.h
- Source/API/Extras/CBLIncrementalStore.m
- Unit-Tests/IncrementalStore_Tests.m
- Getting the relationship document as the document id instead of the NSManagedObject object.
- Support multiple level relationship search. The default max releationship search depth of 3. Users can customize the max depth by specifiying the custom properties called `kCBLISCustomPropertyMaxRelationshipSearchDepth `.
> Fix #715 CBLIS fetch result via nested relationships

- CONTRIBUTING.md
- Source/API/Extras/CBLIncrementalStore.m
- Unit-Tests/IncrementalStore_Tests.m
- Use post filter instead of CBLQueryBuilder when sort descriptors contain relationship keys.
- Fix fetchByEntityAndDoPostFilterWithRequest to support sorting with relationship keys.
> Fix CBLIS sorting with relationship keys

- Source/API/Extras/CBLIncrementalStore.h
- Source/API/Extras/CBLIncrementalStore.m
- Unit-Tests/IncrementalStore_Tests.m
- Store boolean value in CBL database as JSON boolean value instead of number boolean value
- Provide kCBLISCustomPropertyQueryBooleanWithNumber (Default is NO) to support querying the existing boolean number value.
- If setting the kCBLISCustomPropertyQueryBooleanWithNumber property value to YES, when scanning the predicate for CBLQueryBuilder, CBLIS will replcate the original boolean predicate with an OR-compound predicate of the original predicate and the improvised number boolean predicate without parameterizing. For example, if the predicate is 'checked == YES', CBLIS will replace the predicate with 'checked == YES or checked == 1.
#756
> Fix CBLIS storing and querying boolean value

- Source/API/Extras/CBLIncrementalStore.m
- Unit-Tests/IncrementalStore_Tests.m
- Remove the attachment when nullifying the NSData property
- Optimize storing the attachment by checking if the NSData property value was changed or not
#763
> Fix CBLIS cannot nullify NSData property

- Source/CBLParseDate.c
- Unit-Tests/JSON_Tests.m
Fix for the issue: https://github.com/couchbase/couchbase-lite-ios/issues/765
> Fix issue 765: dateWithJSONObject: method cannot parse ISO 8601 dates with a time zone designator "+hhmm" or "-hhmm"

- Source/CBLMisc.h
- Source/CBLMisc.m
- Source/CBL_ForestDBStorage.mm
- Source/CBL_ForestDBViewStorage.mm
- Source/CBL_SQLiteStorage.m
- Source/CBL_SQLiteViewStorage.m
- Unit-Tests/Database_Tests.m
- Extracted keyForPrefixMatch(key, depth) from CBL_SQLiteViewStorage and CBL_ForestDBViewStorage to CBLMisc as CBLKeyForPrefixMatch(key, depth) so same implementation can be reused.
- Added prefixMatchLevel logic to the -getAllDocs:status: method of CBL_SQLiteStorage and CBL_ForestDBStorage.
- Added Database_Tests.test12_AllDocumentsPrefixMatchLevel.
#683
> Add prefixMatchLevel logic to allDocuments query

- Source/CBLParseDate.c
- Unit-Tests/JSON_Tests.m
> Fix issue 765: dateWithJSONObject: method cannot parse ISO 8601 dates with a time zone designator "+hhmm" or "-hhmm" #766

- Listener/CBLHTTPConnection.m
...for better compatibility with .NET clients.
Fixes #784
> Disable HTTP Digest auth for listener, over SSL connections

- Source/CBLDatabaseChange.m
- Source/CBL_SQLiteStorage.m
- Unit-Tests/DatabaseInternal_Tests.m
* -[CBL_SQLiteStorage forceInsert:...] was posting a change notification
even if the revision already existed in the db.
* The CBL_Revision in the CBLDocumentChange would have no sequence since
it hadn't been added to the db.
* This would cause an assertion failure when CBLRouter's changes feed
processed the notification.
* Fixed this and added unit-test coverage of this situation.
Fixes #717
> Fixed: insert of already-existing rev was posting a change notification (#717)

- Source/API/Extras/CBLIncrementalStore.m
- Unit-Tests/IncrementalStore_Tests.m
Instead of using setValuesForKeysWithDictionary:, just set userProperties.
#782
> Fix CBLIS cannot nullify attributes and relationships (#782)

- Source/CBL_Pusher.m
- Unit-Tests/Replication_Tests.m
- Unit-Tests/Server/cbl_unit_tests.json
- Filter out _removed revision in CBL_Pusher's processInbox when preparing revisions to send to the remote server.
- No changes in CBL_Pusher.unpushedRevisions properties. Therefore unpushedRevisions could contained _removed revisions. The same for getting _changes feed from the CBLRouter.
- Added a unit test
- Added cbl_replicator_removed_rev remote database config to Unit-Tests/Server/cbl_unit_tests.json
#671
> Filter out _removed revision from push replication

- Source/API/Extras/CBLIncrementalStore.m
- Unit-Tests/IncrementalStore_Tests.m
Manually merged https://github.com/couchbase/couchbase-lite-ios/pull/795 and added a minor fix to use scanContantValue: method to extract a constant value.
> CBLIS evaluates relationship with nsmanagedobjectid

- Source/API/Extras/CBLIncrementalStore.m
- Unit-Tests/IncrementalStore_Tests.m
- Use transaction in executeSaveRequest: method.
- Remove coalesced changes logic as we do not need this any more after using transaction in executeSaveRequest.
- Cache relationship query result.
- [Bug fix] When inform an ManagedObjectContext object with changes, making sure that it informed on the context object's thread.
#793
> CBLIS Improve execute save request performance

- Source/API/CBLView.h
- Source/API/CBLView.m
- Source/CBLView+Internal.h
- Unit-Tests/View_Tests.m
- Moved totalRows property from CBLView+Internal.h to CBLView.h
- When accessing the totalRows, update the index first.
#808
> Make CBLView.totalRows public

- Source/CBL_ForestDBViewStorage.mm
- Source/CBL_SQLiteViewStorage.m
- Unit-Tests/View_Benchmarks.m
- Unit-Tests/View_Tests.m
- When updating view index, gather a list of the conflict revisions if any.
- Add index conflict docs performance test to View_Benchmarks.
- Performance note when indexing 5000 documents, each has 0 conflict revisions (IP6 simulator):
```
SQLite:
Master branch:
[Time, seconds] average: 0.123, relative standard deviation: 4.698%, 
values: [0.137071, 0.118618, 0.122648, 0.118491, 0.119955, 0.130553, 0.125290, 0.121883, 0.118404, 0.120640]
_conflicts branch:
[Time, seconds] average: 0.127, relative standard deviation: 2.886%, 
values: [0.130026, 0.124279, 0.125534, 0.130044, 0.119877, 0.132092, 0.125637, 0.125442, 0.131264, 0.130175]
ForestDB:
Master branch:
[Time, seconds] average: 0.175, relative standard deviation: 0.806%, 
values: [0.173869, 0.176649, 0.173722, 0.175208, 0.176017, …
```
> Add _conflicts to the document in the map function

- Source/CBL_Attachment.m
- Unit-Tests/DatabaseAttachment_Tests.m
During the pull replication, the revpos of an attachment could be set to a parent revision while the follows=true. If the revpos value doesn't get preserved, the revpos will be set to the current generation.
Later, when pushing an updated document again, the attachment info will contain a wrong revpos and result to the missing_stub error on CouchDB. SyncGateway currently ignores the issue and doesn't overwrite the revpos value on the server side.
#817
> Fix attachment revpos not being set when follows=true

- Source/API/CBLManager.m
- Source/API/CBLReplication.m
- Source/CBLBlipReplicator.m
- Source/CBLDatabase+Replication.h
- Source/CBLDatabase+Replication.m
- Source/CBLManager+Internal.h
- Source/CBLRestPusher.m
- Source/CBL_Replicator.h
- Unit-Tests/Replication_Tests.m
1. Query unpushed revisions from the last sequence. When the bg replicator and the bg replication's last sequence is not null, use the last sequence from the bg replicator. Otherwise use the last sequence from the database.
2. In CBLBlipReplicator, for non-continuous replication, update the status to kCBLReplicatorStopped after connection is closed. This will allow the current last sequence to be synced with the remote and saved into the database before kCBLReplicatorStopped status is notified. This means that for new replicator, we will see the (one-time) replication status like below when it replicates 10 docs:
```
Replication status=3; completedChangesCount=0; changesCount=0
Replication status=3; completedChangesCount=10; changesCount=10
Replication status=0; completedChangesCount=10; …
```
> Fix CBLReplication.pendingDocumentIds when replication is not running

- Source/CBLDatabase+Attachments.m
- Unit-Tests/DatabaseAttachment_Tests.m
When the intermediate parent rev is _deleted rev, the status returned when getting the parentAttachments will be kCBLStatusOK instead of kCBLStatusNotFound. So it should go to the same logic as when the stastus is kCBLStatusNotFound to get the attachment from the attachment revpos instead.
#843
> Fix process attachments when the parent rev is a _deleted rev

- Source/CBLSyncConnection+Checkpoints.m
- Source/CBLSyncConnection+Pull.m
- Source/CBLSyncConnection+Push.m
- Source/CBLSyncConnection.h
- Source/CBLSyncConnection.m
- Source/CBLSyncConnection_Internal.h
- Source/CBLSyncListener.m
- Unit-Tests/Listener_Tests.m
- Added OnSyncAccessCheckBlock property to CBLSyncConnection similarly to CBL_Router.OnAccessCheckBlock property. OnSyncAccessCheckBlock (if specified) will be called to check the access for each sync request coming to the CBLSyncConnection's handlers. The handlers will then return the corresponding error responses depending on the result of the OnSyncAccessCheckBlock call.
- In read only mode, CBLSyncListener will block access to setCheckpoint, changes, and rev requests.
#838
> Fix #838 Implement readOnly to CBLSyncListener

- Source/API/CBLReplication.m
- Unit-Tests/Replication_Tests.m
When updating the replication on the main thread, instead of calling -doAsync: on the database, calling it on the manager object to loose the database open status check.
#698
> Fix #698 replication stopped notification not being sent when closing the database

- Source/CBL_Router.m
- Unit-Tests/Listener_Tests.m
- Unit-Tests/Router_Tests.m
- Aligned with the fix in CocoaHTTPServer (d44cf160dd72fa5a1df9924e33ad367c3e37b798), return 416 when the range is invalid.
- Added unit test cases
#74
> Fix #74 CBLRouter's processRequestRanges to return 416 when the range is invalid

- Source/API/CBLManager.m
- Source/CBLDatabase+Internal.m
- Source/CBLManager+Internal.h
- Unit-Tests/Database_Tests.m
- Closed background database in CBLManager._forgetDatabase: method.
- Added CBLManager._closeDatabaseNamed: method to facilitate closing the opened database of the given name.
- Added Database_Tests.test24_CloseDatabase
- Made CBLDatabase.isOpen value change observable (used in the unit test)
#686
> Fix #686 close database not closing background database

- Listener/CBLHTTPResponse.m
- Source/CBLSyncConnection+Checkpoints.m
- Source/CBLSyncConnection+Pull.m
- Source/CBLSyncConnection+Push.m
- Source/CBLSyncConnection.h
- Source/CBLSyncConnection.m
- Source/CBLSyncConnection_Internal.h
- Source/CBLSyncListener.m
- Unit-Tests/Listener_Tests.m
- Allowed access to PUT /_local/docid (Http Sync) setCheckpoint (Blip Sync).
- Removed docID from CBLSyncConnection's OnSyncAccessCheckBlock as there is currently no usage of the docID.
- Fixed unit tests.
#726
> Fixed #726 CBLListener readOnly mode cannot save checkpoint doc

- Source/CBLDatabase+Internal.m
I ran into this issue on a new app, and had to google the error to figure out how to fix it. Now the fix will be in the logs. (Use the `-ObjC` flag).
> helpful error message when storage classes are missing

- Source/CouchbaseLitePrefix.h
Renames more CocoaLumberjack symbols in CouchbaseLitePrefix.h (see
#880).
> Renames more CocoaLumberjack symbols.

- Source/API/CBLQueryBuilder.m
The comparator block is used more convenience than selector.
Fix an exception issue. See https://github.com/couchbase/couchbase-lite-ios/issues/890
> Add support for sort descriptor using comparator.

- Source/CBLDatabaseUpgrade.m
CBL Android 1.0.4 and .NET 1.1.0 have lowercase attachment file names. This method will detect that and uppercase the file names if needed. This makes the Database_Tests.test23_ReplaceOldVersionDatabase passed on the real device.
#875
> Fixed #875 Rename lowercase attachment files in CBLDatabaseUpgrade

- CouchbaseLite.xcodeproj/project.pbxproj
- Source/CBLDatabase+Internal.m
- Source/CBLMisc.h
- Source/CBLMisc.m
- Source/CBL_BlobStore+Internal.h
- Source/CBL_BlobStore.h
- Source/CBL_BlobStore.m
- Unit-Tests/BlobStore_Tests.m
- Unit-Tests/CBLTestCase.m
- Unit-Tests/DatabaseEncryption_Tests.m
Fixes a serious security problem: Attachments in an encrypted database didn't get encrypted. :(
The bug was simply that when CBLDatabase instantiated its CBL_BlobStore, it didn't set the blob-store's
encryption key. The first commit fixes that, and has a unit test to verify that when an encrypted database is created, the raw attachment blob files are encrypted on disk.
The harder part is fixing existing databases. We have to (a) detect an existing encrypted database with
an unencrypted attachment store that hasn't been fixed yet, and (b) rewrite all the blob files with encryption.
Part (a) is done by adding a file called `_encryption` to the BlobStore directory when encryption is being used. The contents of the file name the encryption algorithm, currently always `AES`. Existing databases …
> Encrypt attachment store if db encrypted, and fix existing unencrypted stores

- Source/API/CBLQuery.m
- Source/API/CBLQueryEnumerator.m
- Source/CBLView+Internal.h
- Unit-Tests/IncrementalStore_Tests.m
- Unit-Tests/View_Tests.m
Don't apply the skip and limit during the actual query. Instead do them after the in-memory sorting.
Fixes #892
Note: I had to change the expected results for an IncrementalStore test. I am pretty sure the prior expected results were wrong, but I haven't looked at this test before so I might have missed something.
> Fixed queries that have custom sortDescriptors and skips or limits

- Source/CBLRestPuller.m
- Source/CBLStatus.h
-[CBLRestPuller pullRemoteRevision:] was treating all errors as applying
only to the revision being pulled, i.e. it would just skip that rev and
continue. That should only be done for specific errors like a 403, 404
or 410 status. Others should set the replicator's error property.
This is actually a regression introduced a year ago in 87f3261 as part
of the fix for #377. That fix made document-level errors from this HTTP
call work correctly, but it broke connection-level errors like this one.
Fixes #900
> Fixed 401 status not being propagated to CBLReplication.lastError

- Source/API/CBLManager.h
- Source/API/CBLManager.m
- Source/CBLDatabase+Internal.m
- Source/CBLDatabaseUpgrade.h
- Source/CBLDatabaseUpgrade.m
- Unit-Tests/Database_Tests.m
If you set the new property CBLManager.upgradeStorage to YES, and the
existing property storageType to @"ForestDB", then existing SQLite
databases will be upgraded to ForestDB when first opened.
Fixes #870
> Support for upgrading SQLite databases to ForestDB (#870)

- Source/API/Extras/CBLIncrementalStore.m
Not firing fault when parent object is in faulted state.
#942
> Fixed #942 crash due to firing fault on faulted parent relationship object

- Source/API/Extras/CBLIncrementalStore.m
When processing CBL databas change, the changed document doesn't have type property. It's possible that the document was deleted without preserving the type property outside the CBLIS app. Now skipping the document without type property and print out a warning message.
#925
> Fixed #925 CBLIS crash due to missing type property

- Source/API/Extras/CBLIncrementalStore.m
- Unit-Tests/IncrementalStore_Tests.m
- Optimize database change processing by not refreshing the contexts when changes are from local.
- Use only firing fault mechanism to refresh all contexts instead of mixing between merging with notifications and firing fault mechanism.
- Ensure context refreshment is called on the right context's dispatch queue.
> Fixed #938 CBLIS execute save performance and context refreshing issue

- Source/API/CBLReplication.h
- Source/API/CBLReplication.m
Also updated the doc-comment to explain that cookies are saved per replication, not in the sharedHTTPCookieStorage.
@pasin, please verify that I didn't say anything wrong in the updated comment :)
> Made path, expirationDate nullable in CBLReplication's cookie setter

- Source/CBLDatabaseUpgrade.m
- Unit-Tests/Database_Tests.m
putLoalDocument:withID: doesn't expect the docID with `_local/` prefix so it added another `_local/` prefix to the ID. Need to remove `_local/` prefix from the ID.
#1041
> Fixed #1041 importing local docs when upgrading the database

- CouchbaseLite.xcodeproj/project.pbxproj
- Source/CBLJSViewCompiler-Prefix.pch
Moved CBLJSViewCompiler out of CouchbaseLite framework and restored CBLJSViewCompiler target for iOS.
#1064
> Fixed #1064 Restoring CBLJSViewCompiler target for iOS

- Source/API/CouchbaseLite.h
This is a regression bug after e97746843befc7987db35420bfbcddad435c9968 commit.
OSX includes CBLRegisterJSViewCompiler into the framework but iOS doesn't so we need to add CBLRegisterJSViewCompiler.h back to CouchbaesLite.h for Mac only.
#1054
> Include CBLRegisterJSViewCompiler.h for Mac only

- Source/CBLDatabase+Internal.m
CBL_SQLiteStorage is not implmenting the lowMemoryWarning method so check if the method is implemented before calling.
#1079
> Check if CBL_Storage's lowMemoryWarning method is implemented before calling

- Source/ChangeTracker/CBLWebSocketChangeTracker.m
If the server closes the WebSocket connection, even cleanly with no error status,
the change tracker should treat it as a recoverable error and retry.
Fixes #1083
> CBLWebSocketChangeTracker: Handle remote disconnect

- Source/API/CBLManager.m
Without this change, on an AppleTV device `[CBLManager sharedInstance]` is unusable, since trying to create a database will fail with a file permission error. This only reproduces on real devices, not the simulator.
(Copied from commit 35453d6c on the 1.1.1-appleTV branch; i.e. this change has been tested previously.)
> tvOS: App Support dir is r/o, so CBLManager should use Caches dir

- Source/API/CBLDocument.m
I noticed a curious case of a deleted document responding to `-isDeleted` with `NO`. Digging deeper into its properties I can see that the current revision indeed has `_deleted = 1`:
```
(lldb) po [document isDeleted]
NO
(lldb) po [document properties]
{
"_deleted" = 1;
"_id" = "MPBibliographyItem:10D49A6A-4822-400C-97A2-3A41429B118A";
"_rev" = "2-29edc04926e670a8e3df99e5b8122175";
}
```
The current definition of `isDeleted` in CBLDocument indeed does not check for the presence of `_deleted`:
```
- (BOOL) isDeleted {
return self.currentRevision == nil && [self getLeafRevisions: NULL].count > 0;
}
```
This PR is an attempt at addressing the above issue by checking for self.currentRevision.isDeletion as well as the pre-existing conditions. 
This case happens at least when fetching a …
> Check for currentRevision.isDeletion state in CBLDocument -isDeleted

- Source/API/CBLManager.m
- Source/CBLRestReplicator+Backgrounding.m
- Source/CBLRestReplicator.h
- Source/CBLRestReplicator.m
- Source/CBL_ForestDBStorage.mm
CBLRestReplicator wasn't ending its background task when the app became
active, which mean that when the app backgrounded again it attempted to
set another background task, which MYBackgroundMonitor doesn't support.
Fixes #1006
> Fixed assertion failure due to not ending background task on app wakeup

- Source/CBLBatcher.m
- Source/CBLBulkDownloader.m
- Source/CBLMultipartDocumentReader.m
- Source/CBLProgressGroup.m
- Source/CBLReachability.m
- Source/CBLRemoteRequest.m
- Source/CBLSyncConnection+Push.m
- Source/CBL_Router.m
If a block ref is stored in an ivar, and the ivar might change due to
a re-entrant call during a call to the block, then be safe and copy the
block ref to a local variable before calling it. Otherwise the block
might be dealloced while its code is running, which will cause garbage
results or even crashes when it accesses a captured variable.
Fixes #1015 (I think)
> Be more careful calling blocks

- Source/API/CBLQuery.m
- Source/API/CouchbaseLitePrivate.h
- Unit-Tests/View_Tests.m
If the database changes and a view index is updated, but doesn't change,
a LiveQuery on that view shouldn't re-run its query. I thought I'd
implemented that earlier, but I made a mistake, so the query ended up
being run anyway. (The LiveQuery still wouldn't notify, though, because
it would see that the old and new query results were the same.)
This commit fixes it so the query doesn't even happen.
Note that this optimization only works for ForestDB-based views, because
SQLite views don't implement the lastSequenceChangedAt property.
Fixes #1114
> Keep LiveQuery from triggering if view index didn't change

- Listener/CBLHTTPConnection.m
CBLHTTPConnection objects never got cleaned up, because my override of
-socketDidDisconnect:withError: wasn't calling the (undeclared)
superclass method, which is what removes the connection object from
the server's connection list.
This caused the CBLHTTPConnection, GCDAsyncSocket, and other objects
to stay in memory; not leaked exactly, but kept in the HTTPServer's
connection list.
Fixed by adding the 'super' call.
Fixes #1017
> Fix major listener memory leak

- Source/API/CBLDocument.h
- Source/API/CBLDocument.m
- Unit-Tests/Database_Tests.m
Public API for inserting an existing revision, e.g. by a pull replicator.
Fixes #1118; part of couchbase-lite-api#135
> API: Added -[CBLDocument putExistingRevisionWithProperties:...]

- Source/CBLRemoteRequest.m
When there is a permanent error occurred, the onCompletion block could be called second time on stopping remote requests originated from setting error property value inside the onCompletion block. So change to break cycles before executing onCompletion block.
#1140
> Fixed #1140 : CBLRemoteRequest onCompletion gets called twice

- Source/API/CBLBase.h
- Source/API/CBLDocument.h
- Source/API/CBLJSON.h
- Source/API/CBLManager.h
- Source/API/CBLQuery+Geo.h
- Source/API/CBLQuery.h
- Source/API/CBLQueryEnumerator.m
- Source/API/CBLRevision.h
- Source/API/CBLView.h
* Made some parameters nullable
* Made some parameter or return types more specific, either using
generics or by specifying a subclass
* Made CBLQueryEnumerator's item type CBLQueryRow to improve Swift 'for'
loop
These may cause compile errors in existing Swift app code, but they're
easy to fix (and will make the code cleaner.) Since Apple is doing the
same type of thing in their stepwise improvement of the Obj-C bindings,
I think this is reasonable.
Fixes #1143
> Public API tweaks for better Swift compatibility

- Source/CBLRestPuller.m
- Source/ChangeTracker/CBLChangeTracker.h
- Source/ChangeTracker/CBLChangeTracker.m
- Unit-Tests/ChangeTracker_Tests.m
- Unit-Tests/ReplicatorInternal_Tests.m
Added two unit tests to make sure that deleted docs aren't pulled if the
db is empty, and are pulled if it isn't.
Fixes #1078
> ChangeTracker: Only use active_only=true if db is empty

- Source/API/CBLReplication.m
- Unit-Tests/Replication_Tests.m
Now tracking replicator's lastSequence and caching it in an ivar.
-isDocumentPending: just compares the doc's sequence with that.
pendingDocumentIDs does basically what it used to do, but it doesn't
need to do it on a background thread.
Also, the bug-fix portion of this is that pendingDocumentIDs remembers
the database's lastSequenceNumber when it's cached; if that changes,
the cached value is invalidated.
Fixes #1132
> Reimplemented CBLReplication.pendingDocumentIDs and -isDocumentPending:

- Source/API/CBLManager.m
`customHTTPHeaders` was initialized in the `init` method but not by the public method `initWithDirectory:options:error:`. So it is legally possible to create an instance of `CBLManager` with a `nil` `customHTTPHeaders`.
To fix this, I moved `customHTTPHeaders` initialization to the custom initialization method.
> Moved customHTTPHeaders initialization to the common initializer

- CouchbaseLite.xcodeproj/project.pbxproj
- CouchbaseLite.xcodeproj/xcshareddata/xcschemes/CBL iOS framework-Carthage.xcscheme
- Added a new shared `CBL iOS framework-Carthage` scheme that will build `CBL iOS framework` target.
- Linked CBLRegisterJSViewCompiler.m, CBLJSFunction.m, and CBLJSViewCompiler.m to `CBL iOS framework` target.
- Changed `CBL iOS framework` target build settings:
1. Set `Symbols Hidden by Default` to No.
2. Set `Architectures` in `CBL iOS framework` to Standard architectures (armv7, arm64).
3. Set `Build Active Architecture Only` to No
4. Add `appletvsimulator` and `appletvos` to `Supported Platforms`
#1153
> Fixed #1153 Carthage building issue on iOS and tvOS

- Source/CBLRestPuller.m
- Remove the remote request from the list first to prevent this block to be called second time when setting a permanent error to the error property.
- As the implementation on 1.2 and dev branch are diverted. This is a double fix of the dev branch's aeae2ea8552d20d4085c9d4128dfa9f41e65446f commit.
#1140
> Fixed #1140 _asyncTaskCount double decreased in CBLMultipartDownloader completion block

- CouchbaseLite.xcodeproj/project.pbxproj
- CouchbaseLite.xcodeproj/xcshareddata/xcschemes/CI MacOS.xcscheme
- CouchbaseLite.xcodeproj/xcshareddata/xcschemes/CI iOS.xcscheme
- Documentation/build_docs.sh
Created CI iOS and CI MacOS scheme for Jenkins build.
Note:
1. LiteServ and LiteServ App target are built by CI MacOS scheme.
2. Documentation target are included in both scheme.
#1048
> Add CI iOS and CI MacOS scheme for Jenkins build

- Listener/CBLHTTPConnection.m
- Source/ChangeTracker/CBLSocketChangeTracker.m
- Unit-Tests/P2P_Tests.m
Added a unit test for this case.
Also fixed a minor issue in CBLSocketChangeTracker that was causing it
to log a warning about unexpected EOF when it gets an HTTP error.
Fixes #1168
> Fixed Listener not checking basic auth over SSL connections

- Source/CBL_SQLiteStorage.m
- Unit-Tests/DatabaseInternal_Tests.m
This makes revision pruning incremental, the way it is in ForestDB. A document's revision tree will never get deeper than the database's maxRevTreeDepth.
The -compact method used to prune every doc in the database. This is still needed, _once_, for pre-existing databases that might have a lot of docs that need pruning. I've added a special key to the database's 'info' metadata to indicate that this bulk prune isn't needed; it's set after the prune, or when a new database is created.
Fixes #1165
CC: @borrrden , @hideki
> SQLite: Prune deepest revisions when new ones are inserted

- Source/CBLDatabase+Attachments.m
- Source/CBLRestPusher.m
- Unit-Tests/P2P_Tests.m
- Unit-Tests/Replication_Tests.m
With lazy attachment downloading, it's possible to have a document but
not have its attachments. That document might be pushed later, i.e. to
a different server, but the replicator would end up failing an assertion
due to the missing attachment.
This commit fixes the crash by detecting the missing attachment and
bailing out of the push. The document won't be pushed, but the checkpoint
won't be advanced past it, so it will be retried on subsequent
replications to that server, so if the attachment is later downloaded,
the doc will be pushed.
Fixes #1128
> Gracefully handle missing attachments when pushing a document

- README.md
Previous version pointed to 1.1.
Now it points to current.
> Update documentation reference

- Source/CBLRestPusher.m
- Source/CBL_Revision.m
In diagnosing @hermanccw's crash (#1179) I read through some code and found a few ways that invalid JSON data could trigger assertion failures. I still don't know exactly how the bad data could have happened, but these are worth fixing and should prevent it in the future.
Fixes #1179
> Speculative fixes for assertion failures caused by invalid JSON

- Source/CBLForestBridge.mm
- Source/CBL_ForestDBViewStorage.mm
If the index is being auto-closed for being idle, it will just retry
the auto-close after another minute.
If the view itself is being closed, it'll log a warning that the
C4View couldn't close.
**NOTE:** This commit is dependent on a CBForest commit that's in [a PR being reviewed by Jim](https://github.com/couchbaselabs/cbforest/pull/72). Please review, but don't press the Merge button unless the other PR has been merged already. If it hasn't, just add a comment that you've reviewed, and I'll merge it when I get notified that Jim's merged the other one.
> Don't close view index while it's being enumerated

- Source/API/CBLDocument.h
- Source/API/CBLDocument.m
- Source/CBLDatabase+Attachments.h
- Source/CBLDatabase+Attachments.m
- Unit-Tests/Database_Tests.m
Allows revisions with attachments to be added.
Fixes #1195
> Added 'attachments:' parameter to -[CBLDocument putExistingRevision...]

- Source/CBLBlipReplicator.m
- Source/CBLReachability.h
- Source/CBLReachability.m
- Source/CBLRestReplicator.m
- Unit-Tests/ReplicatorInternal_Tests.m
* Now takes a URL, not just a hostname.
* Supports checking for general network connectivity
* Now checks system proxy settings to see if a proxy is required to
reach the given URL; if so, it switches to checking general
network connectivity.
* Host is considered reachable even if the flags say 'ConnectionRequired'
as long as the connection doesn't require user intervention.
Fixes #1005 (I think; don't have a proxied network to test with)
> Improved CBLReachability (proxy handling, intermittent connections)

- Source/CBL_Attachment.m
- Unit-Tests/Database_Tests.m
> Allow incoming attachments with revpos:0, for PouchDB compatibility

- CouchbaseLite.xcodeproj/project.pbxproj
- CouchbaseLite.xcodeproj/xcshareddata/xcschemes/CBL iOS framework-Carthage.xcscheme
- Added a new shared `CBL iOS framework-Carthage` scheme that will build `CBL iOS framework` target.
- Linked CBLRegisterJSViewCompiler.m, CBLJSFunction.m, and CBLJSViewCompiler.m to `CBL iOS framework` target.
- Changed `CBL iOS framework` target build settings:
1. Set `Symbols Hidden by Default` to No.
2. Set `Architectures` in `CBL iOS framework` to Standard architectures (armv7, arm64).
3. Set `Build Active Architecture Only` to No
4. Add `appletvsimulator` and `appletvos` to `Supported Platforms`
#1153
> Fix Carthage building issue on iOS and tvOS

- CouchbaseLite.xcodeproj/project.pbxproj
- Source/CBLMultipartBuffer.h
- Source/CBLMultipartBuffer.m
- Source/CBLMultipartReader.h
- Source/CBLMultipartReader.m
The CBLMultipartReader is somewhat slow parsing on older devices. This is almost entirely caused by the `[CBLMultipartReader deleteUpThrough:]` API, mostly because this particular NSMutableData API is very slow though even a realloc here wouldn't be that great.
This slowness is easily observable on an older device ( iPhone 4S in my case ) with instruments time profiler.
This PR addresses this by bringing in a more cyclic style buffer that appends data and maintains a offset/bytes pointer and finally compacts itself once it's past a certain amount of data.
This change makes most of the memory operations inside the `CBLMutlipartReader` negligible.
> Improve multipart reading performance using a cyclic buffer

- Source/CBLDatabase+Insertion.m
- Source/CBLDatabase+Internal.m
- Source/CBL_ForestDBStorage.mm
- Source/CBL_SQLiteStorage.m
- Unit-Tests/DatabaseInternal_Tests.m
The quick-and-dirty pruning algorithm for SQLite wasn't good enough. It
would get rid of all non-leaf revisions of a branch, if there was a
much deeper branch as well. This could cause the parent of the short
branch's leaf to be added again if pulled by the replicator, which
effectively re-creates the conflict if the short branch ended in a
deletion.
The code now does the Right Thing by traversing the rev tree and
preserving all revisions that are within maxRevTreeDepth generations of
a leaf.
Unfortunately this is going to slow down insertions somewhat. It could
be optimized because there are some redundant fetches of revs being
done, but honestly I'd rather save the effort for ForestDB.
Fixes #1217
> More accurate rev pruning in SQLite storage (fixes endless-merge bug)

- Source/CBLRestPusher.m
- Unit-Tests/ReplicatorInternal_Tests.m
Weird edge case: the replicator never becomes active, so it didn't realize it should stop when it didn't find any work to do.
I had to take out the line that sets the `createTarget` property to reproduce the bug; that property causes the replicator to send a PUT request, so work actually happens and the bug isn't triggered. In fact we shouldn't have this line anymore, because that property is useless with Sync Gateway.
Fixes #1228
> Fixed: One-shot push from empty database never stops

- Source/CBLRemoteRequest.h
- Source/CBLRemoteRequest.m
- Source/CBLRemoteSession.m
- Source/CBLStatus.m
- Unit-Tests/DatabaseInternal_Tests.m
- Unit-Tests/Database_Tests.m
- Unit-Tests/ReplicatorInternal_Tests.m
- Moved the JSON buffer from CBLRemoteJSONRequest up to CBLRemoteRequest.
- Took the status code out of the error message created by
CBLStatusToNSErrorWithInfo.
- Removed the createTarget setting from the replications run by
ReplicatorInternal_Tests; it's not supported by SG so it just causes
spurious 412 errors.
Fixes #1245
> CBLRemoteRequest reads error from JSON body when it gets a 4xx/5xx status

- Source/CBL_SQLiteViewStorage.m
When a new revision of a doc isn't the winner (i.e. it's on a shallower
branch), the view indexing code re-indexes the existing winning revision
instead. It should add the new losing revision to the _conflicts array,
but it was getting mixed up and adding the winning rev. Fixed.
Fixes #1252
> Fixed: doc._conflicts passed to map function may include wrong revID

- Source/CBL_Router+Handlers.m
- Source/CBL_Router.h
- Source/CBL_Router.m
- Unit-Tests/Router_Tests.m
* In a PUT of a doc (or _bulk_docs), adding an _exp property sets the
expiration date. Property value can be a number (Unix timestamp),
string (ISO-8601), or JSON null. A 0 or null clears the expiration.
* To retrieve expiration date, add ?show_exp=true to the GET request,
and the document body(ies) will contain an _exp property (with a
string value) if the document has an expiration.
See https://github.com/couchbaselabs/couchbase-lite-api/issues/141
> REST API for document expiration

- Source/API/CBLDocument.m
- Source/CBL_ForestDBStorage.mm
- Source/CBL_Router+Handlers.m
- Source/CBL_SQLiteStorage.m
- Source/CBL_Storage.h
- Unit-Tests/DatabaseInternal_Tests.m
- Unit-Tests/ReplicatorInternal_Tests.m
In a document GET with ?conflicts=true, the code to find the conflicts
could filter out all the revisions and end up with an empty array, then
add the _conflicts property anyway.
Turns out most of the callers of -getAllRevisionsOfDocumentID: needed
to filter out deleted revisions, so I added an includeDeleted parameter.
This simplifies the callers a bit and saves some work, as well as
fixing this bug.
Fixes #1260
> Don't return an empty "_conflicts" array from REST API

- LiteServ App/LiteServ App-Info.plist
Fixes #1271 
This disables App Transport Security by default to enable testing against non-SSL enabled endpoints. I'm not sure about the ramifications for releasing this by default (i.e. Is anyone using Mac OSX LiteServ for anything in production?).
> Disable App Transport Security for Mac OS X LiteServ

- Source/CBLRemoteSession.m
- Source/CBLStatus.h
- Source/CBLStatus.m
- Source/CBL_Router+Handlers.m
- Source/CBL_Router.m
- Unit-Tests/ReplicatorInternal_Tests.m
Fixed a regression from the conversion to NSURLSession. The CBL_URLProtocol has to be explicitly registered with the session. This restores the ability of the replicator to reach URLs served by the router.
As part of this, fixed two other things:
* Fixed router errors when HTTP request has indeterminate length: CBLRouter had trouble reading the response body if it was in the form of an HTTPBodyStream instead of an HTTPBody. (#1045)
* Greatly improved error messages from _replicate and _active_tasks: If a one-shot replication fails, you now get full info in the response body, instead of just a "500 Internal Server Error" status.
Fixes #1292 (a functional-testing blocker)
> Fix local-to-local replication

- Source/CBLOpenIDConnectAuthorizer.m
Add offline=true to the GET _oidc_challenge request.
#1301
> Fix OIDC Authenticator not getting refresh token

- Source/API/Extras/OpenIDConnectUI/OpenIDController+UIKit.h
Added `#import <UIKit/UIKit.h>` to OpenIDController+UIKit.h.
#1304
> Fix OpenIDController+UIKit missing import UIKit

- Unit-Tests/Replication_Tests.m
The previous fix (9c4dfb81b418c88cfc97dbd3e37beeca89446cff) is missing the fix in pullWithOIDCAuth: method.
> Patch OIDC unit tests

- Source/CBLMultipartWriter.m
- Source/CBL_Attachment.h
- Source/CBL_Attachment.m
The issue happens only when the database is encrypted. When the attachment is encrypted, the actual content length cannot be determined when getting the attachment stream.
The fixing is to use the declared length as the content length if the attachment is encrypted.
#1323
> Fixed #1323 : attachment content length = 0 when pushing the document

- Source/API/CBLAuthenticator.h
- Source/API/CBLManager.m
- Source/API/CBLReplication.h
- Source/API/CBLReplication.m
- Source/CBLAuthorizer.h
- Source/CBLAuthorizer.m
- Source/CBLOpenIDConnectAuthorizer.h
- Source/CBLOpenIDConnectAuthorizer.m
- Unit-Tests/Replication_Tests.m
New method is -[CBLReplication removeStoredCredentials:]
Also moved the recently-added .username property from CBLAuthenticator
to CBLReplication -- this makes it consistent that CBLAuthenticator
has no API of its own but has to be accessed through the replication object.
Fixes #1302
> Added API to remove OpenID tokens from Keychain

- Source/CBLOpenIDConnectAuthorizer.m
- Unit-Tests/Replication_Tests.m
> Fixed OIDC authenticator forgetting refresh token after 1st refresh

- Source/API/CouchbaseLitePrivate.h
- Source/CBLRestPusher.m
- Source/CBLRestReplicator.m
- Unit-Tests/Replication_Tests.m
When the pusher is notified of a new revision, but decides to ignore it
because it's an 'echo' from a pull replication (or because it's rejected
by the filter), it should advance the checkpoint past that rev's
sequence.
This is a good optimization in general, to prevent the next push from
re-scanning the same revisions, but more importantly it tells
CBLReplication.pendingDocuments that those revisions aren't pending.
To fix this I did have to change the timing at which the pusher adds
revs to its internal _pendingSequences set, because it needs to happen
at the same time that skipped sequences are being handled.
Fixes #1274
> Newly-pulled docs shouldn't show up in pusher's pendingDocuments

- Source/CBL_Router.h
- Source/CBL_Router.m
It was possible for a CBL_Router sending an async response to be
dealloced early, since there was nothing keeping a reference to it
during the entire duration of its lifecycle. (I couldn't actually
reproduce this crash, unfortunately.)
To fix this I added a global set sRunningRouters that the router is
added to at the start of its -run method, and removed from at the end
of its -stopNow method.
Fixes #1325
> Prevent premature dealloc of CBL_Router

- Source/API/CBLDatabase.m
- Source/CBL_Shared.h
- Source/CBL_Shared.m
- Unit-Tests/DatabaseEncryption_Tests.m
We can't rewrite the db if it's open by multiple handles (SQLite or
ForestDB). The proper solution is to close the other handles and then
re-open them [with the new key] afterwards, but that would be too
difficult to do for 1.3. So for now, just detect the situation and
fail with a descriptive error.
Fixes #1233 (we think)
> Disallow rekeying a db if it's open in multiple CBLManagers

- Source/API/CBLReplication.m
- Source/API/CouchbaseLitePrivate.h
- Source/CBLBlipReplicator.m
- Source/CBLCookieStorage.h
- Source/CBLCookieStorage.m
- Source/CBLDatabase+Internal.h
- Source/CBLDatabase+Internal.m
- Source/CBLDatabase+Replication.h
- Source/CBLDatabase+Replication.m
- Source/CBLInternal.h
- Source/CBLRestPuller.m
- Source/CBLRestReplicator.m
- Source/CBL_Replicator.h
- Unit-Tests/CookieStorage_Tests.m
- Unit-Tests/Replication_Tests.m
- Added cookieStorages properties to the internal CBLDatabase.
- Cookies are stored in the local database info document under the key named `cookies`.
- Implemented migrateOldCookieStorage to migrate cookies from checkpoint docs to the new local data info document. The old cookies are removed after the migration.
- CBLReplication always accesses the database cookie storage only from the background thread.
#1334
> Change cookie storage scope from replicator to database

- Source/API/CBLManager.m
- Source/CBLAuthorizer.h
- Source/CBLAuthorizer.m
- Source/CBLOpenIDConnectAuthorizer.m
- Source/CBLRemoteLogin.h
- Source/CBLRemoteLogin.m
- Source/CBLRestReplicator.m
- Unit-Tests/Replication_Tests.m
Store the database UUID in the kSecAttrAccount property in the Keychain
items. That lets us scope the lookup to that database.
Fixes #1348
> OpenID tokens in Keychain should be per-database

- Source/API/CBLReplication.m
- Source/CBLCookieStorage.h
- Source/CBLCookieStorage.m
- Unit-Tests/CookieStorage_Tests.m
Regression from the recent move of cookie storage to the database.
> -[CBLReplication deleteAllCookies] should only delete cookies for its URL

- Source/CBLOpenIDConnectAuthorizer.m
- Unit-Tests/Misc_Tests.m
Conditionalized some usages of NSURLComponents methods that were only
added later.
Tested both the old and new code paths.
Clean bill of health from Deploymate.
Fixes #1362
> Restored iOS 7 / macOS 10.9 compatibility

- Source/API/CBLManager.m
- Source/API/CouchbaseLitePrivate.h
- Source/CBLDatabase+Internal.m
- Source/CBLSymmetricKey.h
- Source/CBLSymmetricKey.m
- Unit-Tests/DatabaseEncryption_Tests.m
If in the CBL API you specify an encryption key of `@YES` when opening
a database, it'll generate a random key and store it in the Keychain.
Unfortunately the code to generate the key broke a while ago, but the
unit tests wouldn't reveal the problem if they had already been run
before, because the key would already exist.
I fixed this by:
* Correcting the bug in CBLDatabase that prevented the key from being
generated if an existing one couldn't be found
* Adding a new private method on CBLManager to delete a database's key
from the Keychain, which is now called before the unit test runs.
> Fixed ability to store db encryption key in (macOS) Keychain

- Source/CBL_ForestDBQueryEnumerator.mm
- Source/CBL_ForestDBStorage.mm
- Unit-Tests/View_Tests.m
* Added a unit test that reproduces the issue found in ToDoLite during testathon.
* Incorporated ForestDB fix for [MB-20196](https://issues.couchbase.com/browse/MB-20196)
* Added a check in query enumeration code to warn about errors returned from the CBForest enumerator (since the CBL API doesn't provide a way to return them.)
* Turn off gMYWarnRaisesException while logging a warning from CBForest; otherwise we end up throwing an exception from within a call to CBForest, which is Very Bad.
Fixes #1370
> Fixed ForestDB iteration issue

- CouchbaseLite.xcodeproj/project.pbxproj
> Fixed #1383 : Link libCBLForestDBStorage.a to CBL iOS Unit Tests and CBL tvOS Unit Target

- xcconfigs/tvOS Test App.xcconfig
This fix unblocks running unit tests on the tvOS device.
#1387
> Fix tvOS Unit Tests build failure when testing on device

- Source/CBL_SQLiteStorage.m
- Unit-Tests/Database_Tests.m
This is legal since our databases are in WAL mode. It greatly improves
concurrent access -- the ConcurrentWrites unit test (which has two
reader threads and two writers) runs 2.25x faster on my Mac!
I made a slight change to database opening to ensure that the db is
always set to WAL mode, instead of just setting the mode when the db is
first created.
Fixes #1389
> Allow SQLite read access concurrently with a write transaction

- Source/CBLRemoteSession.m
- Unit-Tests/Replication_Tests.m
This works around an OS bug where NSNotificationQueue doesn't post its
notifications when called in PostASAP mode while the runloop is handling
a block.
The workaround is to not call CFRunLoopPerform, but instead use our
existing MYPerformOnThread utility, which schedules the block in a
different way that doesn't trigger the bug.
Fixes #1392
> Fix for replicator notifications not getting posted

- Source/CBL_SQLiteStorage.m
- Unit-Tests/Database_Tests.m
If the cache isn't invalidated, an entry can be left behind for a new
doc that was created inside the canceled transaction. Then that rowid
can be used for a different doc, and now the cache points to the wrong
doc...
Fixes #1437
> Invalidate SQLite docNumericID cache after a transaction is aborted

- Source/CBLRestPuller.m
- Source/CBLRestReplicator+Internal.h
- Source/CBLRestReplicator.m
- Source/ChangeTracker/CBLSocketChangeTracker.m
- Source/ChangeTracker/CBLWebSocketChangeTracker.m
It's possible for an initial HTTP request sent by the replicator to hit
some middleware that returns a different Server: header, instead of SG.
In this case the replicator shouldn't hang onto that first header,
since it'll never end up using replicator optimizations like bulk_get.
I changed the logic so that if the currently cached server header is
not from SG, and we receive a different value in a subsequent response,
we switch to the new value (presumably SG.) But once we've received a
response from SG, we keep that.
Also, this commit adds some extra `ChangeTracker` logging -- the full
request headers are now logged, in an attempt to figure out why the
Cookie header isn't getting sent for one developer (which is what
triggers the above situation.)
For #1464
> Workaround for getting wrong `Server:` response header on first request

- Source/CBLCookieStorage.m
- Unit-Tests/CookieStorage_Tests.m
- Unit-Tests/Replication_Tests.m
Cookies are now kept in CBL_Shared and shared with all cookie storage of the same db name. All cookies storages will now see and operate over the same set of cookies. This will fix #1464 that the session cookies are lost when a new cookie storage is created.
> Fixed #1464 : Session cookies are lost

- Source/API/CBLModel.h
- Source/API/CBLModel.m
Addresses #1454 by adding an assertion + extending API documentation.
> Fix crash in `-[CBLModel propertiesToSave]` for model objects with a deleted (or otherwise nil) document

- Source/CBLRestReplicator.m
* When the replicator is offline, also cancel the retryIfRetry delayed call. When the replication becomes online, the same retry logic will be done automatically.
* This also fixes #794 issue caused by a race condition when a pull replicator becomes online and the retryIfRetry is called about at the same time but before fetchRemoteCheckpoint is done. If this condition happens, two beginReplicating() will be called (one from retry() and another one from fetchRemoteCheckpoint) and result to a crash as the changeTracker will be started twice.
> Fix replication retry is still active when the replicator is offline

- Source/API/CouchbaseLitePrivate.h
- Source/CBLDatabaseChange.h
Moved isDeletion property from private to public.
#1538
> Make CBLDatabaseChange’s isDeletion property public

- Source/CBLRemoteSession.m
I couldn't reproduce the issue myself but from the crash log, it seems like _allRequests is gone while it's used. Applied the technique to ensure that _allRequests is retained inside the block.
#1429
> Fix #1429 crash in CBLRemoteSession

- Source/API/CBLDatabase.m
- Source/CBLDatabase+Internal.h
- Source/CBLDatabase+Internal.m
- Unit-Tests/DatabaseEncryption_Tests.m
* Follow the same logic as deleting the database by closing all database handles first before rekeying. The database will be reopened and rekeyed.
* Add CBL_DatabaseWillBeRekeyedNotification to notify all database objects that the database will be rekey so that the database objects of the same database can be closed.
#1343
> Fixed #1343 rekey when there are multiple database handles

- Source/API/CBLManager.m
- Unit-Tests/DatabaseInternal_Tests.m
File protection was set only when first creating the manager directory. Need to ensure that the file protection level is set (if specified) even when the manager directory already exists.
#1491
> Fix #1491 change file protection level not effected

- Source/CBLRouter+Changes.m
- Source/CBL_Router.h
- Source/CBL_Router.m
- Unit-Tests/Router_Tests.m
* Implement _changes timeout for longpoll and continuous feeds
* The default timeout of 60 seconds applied will be applied if there is no timeout as well as heartbeat param set.
#1236
> Fixed #1236 Implement longpoll and continuous _changes timeout

- Objective-C/CBLDatabase.h
- Objective-C/CBLDatabase.mm
- Objective-C/CBLQuery+Predicates.mm
- Objective-C/Internal/CBLQuery+Internal.h
- Objective-C/Tests/QueryTest.m
Exposing the new LiteCore feature (and API change) in the Obj-C API.
> Query: Added support for indexing expressions (not just properties)

- Objective-C/CBLDocument.mm
- Objective-C/CBLProperties.mm
- Objective-C/Internal/CBLInternal.h
- Objective-C/Tests/DocumentTest.m
* Calling -fleeceValueToObject: to convert _root directly will end up always converting the whole _root into dictionary as checking dictionary tyle (_cbltype) will always be null at the _root level. Instead, constructing the dictionary by looping through each key/value at the root level and calling fleeceValueToObject() to convert each value.
* Removed unused variable.
#1590
> Fix converting fleece root to dictionary

- Objective-C/CBLDatabase.h
- Objective-C/CBLDatabase.mm
- Objective-C/CBLDocument.h
- Objective-C/CBLDocument.mm
* Make sure to use BOOL (not bool) and NSError** pattern to get convert to throws in Swift.
* Redeclare subscription methods, otherwise they don't get exposed to the Swift bridging APIs.
> Fixed objective-c to swift bridging API

- Source/CBL_SQLiteStorage.m
* Ignore `no such table: cfurl_cache_response` as using an NSURLConnection to connect to a custom scheme URL before the scheme is registered will cause this error which is harmless. #1596
* The statement error could happen when using invalid FTS query strings . Instead of crash from the warning, the error should return appropriately. #1598
> Fixed #1596 and #1598 Ignore some SQLite errors

- CouchbaseLite.xcodeproj/project.pbxproj
- Objective-C/CBLDocument.h
- Objective-C/CBLDocument.mm
- Objective-C/CBLProperties.h
- Objective-C/CBLProperties.mm
- Objective-C/CBLSubdocument.h
- Objective-C/CBLSubdocument.mm
- Objective-C/CouchbaseLite.exp
- Objective-C/CouchbaseLite.h
- Objective-C/Internal/CBLInternal.h
- Objective-C/Tests/DocumentTest.m
- Objective-C/Tests/SubdocumentTest.m
* When getting a property value that the raw value is Dictionary type, the value will be converted to Subdocument.
* When getting .properties, all dictionary values will be converted to Subdocument.
* By default, setting a Subdocument property will be by reference. However if the Subdocument has already been set to a key, the value of the Subdocument will be copied instead.
* Subdocument will be invalidated when the property doesn’t exist any more or the property value has been changed to non dictionary data. When the subdocument is validated, current implementation will set its parent, root, and properties to null value. The changesKeys and flag will be reset as well.
*  The Subdocument objects in an array could be re-ordered. However if the underlining dictionary are changed, the …
> Implement subdocument

- CouchbaseLite.xcodeproj/project.pbxproj
- xcconfigs/CBL Swift.xcconfig
Instead of depending on CBL ObjC target and dynamically linking with CouchbaseLite.framework, linking with LinkCore and using Objective-C / C codes directly. In the future, when Objective-C codes getting bigger, we could create CBL ObjC Static target and link with it instead.
#1640 #1642 #1643
> Reconfigure CBL Swift to link with LiteCore and use ObjC codes

- .gitmodules
carthage update on any sub-module of couchbase-lite-ios for iOS Development causes a timeout when checking out all dependancies.
Many companies restrict using the git:// scheme due to it using a specific port and not using proper authorization. Https is much more secure and more commonly unblocked.
Proposing this file be standardized to use https rather than git protocol.
This fixes the carthage update timeout issue.
Alternatively users cloning this project will need to run a command similar to:
git config --global url."https://".insteadOf git://
or remove --global and do it on a project-to-project basis.
> Changing the protocol scheme from git to https for better support

- Source/ChangeTracker/CBLChangeTracker.h
- Source/ChangeTracker/CBLChangeTracker.m
- Source/ChangeTracker/CBLSocketChangeTracker.m
- Source/ChangeTracker/CBLWebSocketChangeTracker.m
* Implement timeout in ChangeTracker only for longpoll and websocket mode.
* Timeout value is greater than the heartbeat value 10%.
* When timeout occurs, both socket and websocket ChangeTracker will be failed with NSURLErrorTimedOut and the errors will be handled by the puller replicator with the retry logic.
#1551
> Fixed #1551 Implement timeout in ChangeTracker for longpoll and websocket mode

- Objective-C/CBLProperties.h
- Objective-C/CBLProperties.mm
- Swift/Document.swift
- Swift/Properties.swift
- Swift/Tests/DocumentTest.swift
- Swift/Tests/SubdocumentTest.swift
* Renamed property() and setProperty(key, value) to getValue() and setValue(key, value).
* Made setValue(key, value) chainable API
* Added the missing CBLProperties’s -blobForKey: method.
> Inline Swift Property Accessors with the Spec

- CouchbaseLite.xcodeproj/project.pbxproj
- Objective-C/CBLLiveQuery.h
- Objective-C/CBLLiveQuery.mm
- Objective-C/CBLQueryEnumerator.h
- Objective-C/CBLQueryEnumerator.mm
- Objective-C/CBLQueryResultsArray.h
- Objective-C/CBLQueryResultsArray.mm
- Objective-C/CBLQueryRow.mm
- Objective-C/CBLReadOnlyDocument.mm
- Objective-C/CouchbaseLite.h
- Objective-C/Internal/CBLLog.m
- Objective-C/Tests/QueryTest.m
Implementation of CBLLiveQuery, with provisional API. NOTE: Creating a LiveQuery is different. Instead of using a -asLiveQuery method to convert a query, you directly instantiate a CBLLiveQuery.
The implementation is adapted from the 1.x sources, but I simplified it to run the query on the main thread, since we don't have a mechanism to run things in the background yet.
The first commit is about creating a lazy NSArray class for the query's `rows` property, so it doesn't have to instantiate every row as Cocoa objects all at once.
Fixes #1759
> 2.0: LiveQuery

- Source/CBLRestPusher.m
- Unit-Tests/Replication_Tests.m
Not treating 403 or forbidden error as an error when uploading multipart or non-multipart revision. This is inline with uploading bulk docs.
#1649
> Fixed #1649 : pusher stopped when getting a forbidden error

- Source/CBLBulkDownloader.m
The crash happened due to the Assert(!_docReader) in the -startParted: delegate called. Based on the log in #1770, the issue happened after a retry.
From the code review, we don’t reset the _docReader so if the retry is successful and if the -startParted: method is called again, the assertion will fail.
Note that I have also reviewed CBLMultipartReader but I couldn’t find a possible way that it would end up calling -startedPart method twice.
> Fixed #1770 : Clear _docReader before retry in CBLBulkDownloader

- Source/CBLRestReplicator.m
The issue couldn’t reproduce but here is what is speculated to happen:
There could be a race scenario between stopping the fetch remote checkpoint request when putting the replicator offine and the request itself is completed. If stopping the request is too late, the onComplete will be called in the next runloop, and that will cause a change tracker to start in offline mode.
To prevent above scenario, when the request is completed, check whether the replicator is still online or not. If the replicator is not online, just finish the request and return.
#1655
> Fixed #1655 : Race causing the change tracker to start twice

- Swift/ConflictResolver.swift
I was looking at the Swift code and saw that this class could be simplified.
* Made the mine/theirs/base properties regular 'var's.
* Used flatMap idiom to initialize base without needing an if/else. (It's the first time I've used it, but it's apparently a pretty common idiom in the Swift world.)
> Simplified Swift Conflict class

- Objective-C/CBLArray.m
- Objective-C/CBLBlob.mm
- Objective-C/CBLDictionary.mm
- Objective-C/CBLDocument.mm
- Objective-C/CBLReadOnlyArray.mm
- Objective-C/CBLReadOnlyDictionary.mm
- Objective-C/Internal/CBLData.h
- Objective-C/Internal/CBLData.mm
- Objective-C/Internal/CBLDocument+Internal.h
In the TuneMark benchmark's import phase, the time was dominated by adding an NSDictionary to an empty document, and encoding the document to Fleece. I've sped this up, and some other methods that showed up as hot-spots.
The biggest problem was the large number of -conformsToProtocol: calls. This method is very slow. I've replaced those with category methods on NSObject, which the CBL classes override. These are declared in CBLData.h.
There are some more changes in CBLDictionary to reduce the amount of work done in -setDictionary: and -toDictionary.
> Sped up array/dictionary conversions and Fleece encoding

- Objective-C/CBLPredicateQuery+Predicates.mm
- Objective-C/Internal/CBLAggregateExpression.m
- Objective-C/Internal/CBLBinaryExpression.m
See couchbase/couchbase-lite-core#204
The LC change (not yet pushed to Github) is that the "IN" operation now takes exactly 2 args: first the item, second the array expression. Also I added an array-literal syntax so you can do the SQL-style "IN" where you give a list of values. That's a "[]" expression where the args are the array elements.
> Updated query generation to compensate for changed LiteCore "IN" op

- Objective-C/CBLDatabase.h
- Objective-C/CBLDatabase.mm
- Objective-C/CBLReplicator.h
- Objective-C/CBLReplicator.mm
- Objective-C/Internal/CBLLog.h
- Objective-C/Internal/CBLLog.m
- Objective-C/Internal/Replicator/CBLWebSocket.mm
- Swift/Database.swift
* Implemented set log level API for ObjC and Swift.
* The log domains and levels are tentative.
* Need to sync between LiteCore and Lite log domains. We should shared the domains as many as possible.
> Implement setting log level API

- Source/CBLRestReplicator+Backgrounding.m
* There is a race condition between resetting _bgMonitor to nil in -endBackground on the replicator thread and accessing _bgMonitor in -okToEndBackgrounding on the main thread.
* The easiest way to fix this is to not resetting nil after stopping the bgMonitor given the fact that it could also be recreated again from the replicator thread in the -setupBackgrounding method.
#1677 #CBSE-4145
> Fix race between resetting _bgMonitor to nil and using it on different threads

- Scripts/generate_release_zip.sh
Adds the LiteCore command-line tools (cblite, litecp, litecorelog) to our builds, in a "Tools" subfolder.
> Add the command-line tools to builds

- Source/CBLCookieStorage.h
- Source/CBLCookieStorage.m
- Source/CBLRemoteRequest.m
- Source/CBLRestReplicator.m
- Source/ChangeTracker/CBLChangeTracker.m
- Unit-Tests/Replication_Tests.m
Problem:
* We set all CBLReplicator.headers to the NSURLSessionConfiguration.HTTPAdditionalHeaders so that the headers will be automatically set to the NSURLRequest. However if the HTTPAdditionalHeaders  contains Cookie and there is already cookies set the the NSURLRequest by the cookie storage, the Cookie in the HTTPAdditionalHeaders will be ignored.
* SGW has a feature to auto-refresh the session before the session gets expired. The new session cookie will be sent to the Replicator vis the NSURLResponse and will be saved into the cookie storage. When the refresh happens, the cookie originally set in the HTTPAdditionalHeaders will be ignore. However the new cookie set to the header after restarting the SGW will be ignore too.  (#1757 and #1715)
Solution:
When starting the replicator, …
> Fixed #1757 setting cookie in header could not be effective

- Source/CBLAuthorizer.m
* On High Sierra, the status codes returned are @[CSSMERR_APPLETP_HOSTNAME_MISMATCH and CSSMERR_TP_NOT_TRUSTED] instead of just @[CSSMERR_APPLETP_HOSTNAME_MISMATCH].
* Changed to logic to check the status codes to check whether the codes contain CSSMERR_APPLETP_HOSTNAME_MISMATCH or not.
#1912
> Fixed #1912 CBLWarnUntrustedCert for .local on High Sierra

- Source/API/CBLView.m
- Source/CBLView+Internal.h
- Source/CBLView+REST.m
- Unit-Tests/Router_Tests.m
If view’s properties is not nil, always compare the version (SHA1 hash of the new view’s properties) whether it is the same as the current version or not. If version is not the same, recompile the map/reduce fn and re-register the map/reduce fn.
#1758
> Fixed #1758 Updated designed doc’s map function not get re-compiled

- Source/CBLBulkDownloader.m
- Source/CBLDatabase+Internal.m
- Source/CBLRestPuller.m
- Source/CBL_ForestDBStorage.mm
- Source/CBL_Router+Handlers.m
- Source/CBL_SQLiteStorage.m
- Source/CBL_Storage.h
- Unit-Tests/DatabaseInternal_Tests.m
This logic is ported from .NET (https://github.com/couchbase/couchbase-lite-net/commit/07c1374d373b4d0ce8a4bedb640294aeec232d71) to fix channel removal potentially disrupts attachments issue (#1918)
The following code are slightly different from .NET:
https://github.com/couchbase/couchbase-lite-ios/blob/2c86216a1f8e921b1e9cc1a1bacf652d11903dd9/Source/CBLBulkDownloader.m#L58 (.NET always true)
https://github.com/couchbase/couchbase-lite-ios/blob/2c86216a1f8e921b1e9cc1a1bacf652d11903dd9/Source/CBLRestPuller.m#L429 (.NET always true)
https://github.com/couchbase/couchbase-lite-ios/blob/2c86216a1f8e921b1e9cc1a1bacf652d11903dd9/Source/CBL_ForestDBStorage.mm#L459-L465 (.NET doesn't load the revision body).
> Fixed #1918: Skip the removal rev when getting ancestor rev ids

- Objective-C/CBLArray.h
- Objective-C/CBLArray.m
- Objective-C/CBLArrayFragment.h
- Objective-C/CBLDictionary.h
- Objective-C/CBLDictionary.mm
- Objective-C/CBLDictionaryFragment.h
- Objective-C/CBLDocumentFragment.m
- Objective-C/CBLFragment.m
- Objective-C/CBLQueryResult.mm
- Objective-C/CBLReadOnlyArray.mm
- Objective-C/CBLReadOnlyArrayFragment.h
- Objective-C/CBLReadOnlyDictionary.mm
- Objective-C/CBLReadOnlyDictionaryFragment.h
- Objective-C/CBLReadOnlyFragment.m
- Objective-C/Internal/CBLDocument+Internal.h
- Objective-C/Tests/FragmentTest.m
- Swift/Fragment.swift
- Swift/ReadOnlyFragment.swift
(This is not dependent on the PR I submitted last week.)
* Parent returns nil if it knows the fragment doesn't exist
* Fragments are always initialized with parent and key/index; the value is derived lazily
* Numeric and boolean accessors don't create any intermediate NSObjects
* Chained subscripts reuse the same fragment object
* Removed expensive -conformsToProtocol: checks in setter
* All of CBLFragment turned out to be unnecessary except the setter
* Fixed a bug where booleanValue returned NO for non-numeric values
> Reimplemented fragments to be more lightweight

- Objective-C/CBLDictionary.mm
- Objective-C/CBLReadOnlyDictionary.mm
- Objective-C/Internal/CBLDocument+Internal.h
The NSArray backing the enumeration state was getting dealloced during the enumeration.
Fixes #1934
> Fixed crash in for/in loop with CBLDictionary (regression)

- Objective-C/Internal/Replicator/CBLWebSocket.mm
Set request.HTTPShouldHandleCookies to NO so that the CBLHTTPLogic will not add the cookies from the shared cookie storage. Also we don’t actually use the shared cookie storage.
> Fixed #1927 session cookie overwritten by the cookie in shared storage

- CouchbaseLite.xcodeproj/project.pbxproj
- Objective-C/CBLDatabase.h
- Objective-C/CBLDatabase.mm
- Objective-C/CBLDocument.mm
- Objective-C/CBLMutableDocument.mm
- Objective-C/CBLQuery.mm
- Objective-C/CBLQueryResult.mm
- Objective-C/CBLQueryResultSet.mm
- Objective-C/CBLReplicator.mm
- Objective-C/Internal/CBLDatabase+Internal.h
- Objective-C/Internal/CBLDocument+Internal.h
- Objective-C/Internal/CBLLock.h
- Objective-C/Internal/CBLPrefix.h
- Objective-C/Tests/ConcurrentTest.m
* Created CBL_LOCK(m) macro for locking.
* Applied the lock to non-thread safe database operations by following the guideline from https://github.com/couchbase/couchbase-lite-core/wiki/Thread-Safety.
#1948
> Fixed #1948 Make database operations thread safe

- Objective-C/Tests/ReplicatorTest.m
- Objective-C/Tests/iOS/Info-Tests.plist
- Objective-C/Tests/iOS/Info.plist
* These tests can be enabled via an environment variable without having to edit the source
* SG hostname and port can be customized
* eraseRemoteEndpoint now detects HTTP errors
* Added ATS exceptions to Info.plist so iOS can make non-SSL connections
> Improve tests of replication to SG

- CouchbaseLite.xcodeproj/project.pbxproj
- Objective-C/CBLDatabase.mm
- Objective-C/CBLErrors.h
- Objective-C/CBLPredicateQuery+Predicates.mm
- Objective-C/CBLQuery.mm
- Objective-C/CouchbaseLite.exp
- Objective-C/CouchbaseLite.h
- Objective-C/Internal/CBLMisc.m
- Objective-C/Internal/CBLPredicateQuery+Internal.h
- Objective-C/Internal/CBLPropertyExpression.h
- Objective-C/Internal/CBLPropertyExpression.m
- Objective-C/Internal/CBLStatus.h
- Objective-C/Internal/CBLStatus.mm
- Objective-C/Tests/ConflictTest.m
- Objective-C/Tests/DatabaseEncryptionTest.m
- Objective-C/Tests/DatabaseTest.m
- Objective-C/Tests/DocumentTest.m
- Objective-C/Tests/ReplicatorTest.m
- Swift/Tests/ConflictTest.swift
- Swift/Tests/DatabaseEncryptionTest.swift
- Swift/Tests/DocumentTest.swift
* Added public header CBLErrors.h which declares CBLErrorDomain and constants for all the LiteCore errors, plus HTTP and WebSocket codes.
* CBLStatus.m maps all NetworkDomain errors to NSURLErrorDomain.
* CBLStatus.m maps WebSocketDomain to CBLErrorDomain but offsets the codes by +10000 (as declared in CBLErrors.h)
* CBLStatus constants were folded into CBLErrorDomain codes.
Fixes #2006
> Declare NSError domain and codes in public API, and improve error mapping

- Objective-C/CBLDatabase.mm
- Objective-C/CBLDatabaseConfiguration.h
- Objective-C/Tests/ConflictTest.h
- Objective-C/Tests/ConflictTest.m
- Objective-C/Tests/ReplicatorTest.m
After conflict resolution, the doc history must include the current
remote revision, otherwise the next push will create a conflict. So
during resolution the conflicting [remote] branch must 'win'.
Fixes #2041
> Replication conflict resolution should always update remote branch

- CouchbaseLite.xcodeproj/project.pbxproj
- Objective-C/CBLReplicator.mm
- Objective-C/CBLReplicatorConfiguration.h
- Objective-C/CBLReplicatorConfiguration.m
- Objective-C/Internal/CBLReplicator+Internal.h
- Objective-C/Internal/Replicator/CBLReplicator+Backgrounding.h
- Objective-C/Internal/Replicator/CBLReplicator+Backgrounding.m
- Objective-C/Tests/ReplicatorTest.m
- Swift/ReplicatorConfiguration.swift
* Added ReplicatorConfiguration.allowReplicatingInBackground flag for disabling or enabling the feature.
* ReplicatorConfiguration.allowReplicatingInBackground=NO, the replicator will be suspended when the app goes into background and the replicator becomes idle. The replicator will be resumed when the app is brought foreground.
* ReplicatorConfiguration.allowReplicatingInBackground=YES, the replicator will keep running the background BUT it is the applicataion’s responsibility to extend the background task to keep the replicator running properly.
* If the replicator is started while the app is in background, the replicator will keep running until IDLE before getting suspended.
#2058
> Fixed #2058 : Implement replicator backgrounding support

- Source/CBLRestReplicator+Backgrounding.m
- Source/CBLRestReplicator+Internal.h
- Source/CBLRestReplicator.h
- Source/CBLRestReplicator.m
* Reverted the fix back to 1.4.0 that executes background / foregrounding logic on the main thread.
* In CBLRestReplicator.m, make CBLRestReplicator’s `_active` property atomic.
* In CBLRestReplicator.m, moved calling `[self setupBackgrounding]` to the end of the `-start` method.
* In `-backgroundTaskExpired` of CBLRestReplicator+Backgrounding.m, set `_deepBackground = YES` on the main thread instead of on the replicator thread as it was in 1.4.0.
#1898
> Fix #1898 without blocking the main thread

- Objective-C/CBLArray.mm
- Objective-C/CBLDictionary.mm
- Objective-C/CBLDocument.mm
- Objective-C/CBLMutableArray.mm
- Objective-C/CBLMutableDictionary.mm
- Objective-C/Internal/CBLDocument+Internal.h
- Objective-C/Internal/CBLLock.h
- Objective-C/Tests/ConcurrentTest.m
* Made Document, Dictionary, and Array thread-safe. The MutableDocument, MutableDictionary, and MutableArray are not guarantee to be thread-safe.
*  Created a shared lock which could either be the database object or the self object to lock all of the mcollection’s operations.
#1967
> Fixed #1967 : Make Document, Dictionary, and Array thread-safe

- Source/CBL_SQLiteStorage.m
Casting an NSInteger argument for String Format to long as suggested in https://developer.apple.com/library/content/documentation/Cocoa/Conceptual/Strings/Articles/formatSpecifiers.html
> Fixed: Build failed due to the new Xcode 9.3 compiler error

- Scripts/Support/License/LICENSE_community.txt
- Scripts/Support/License/LICENSE_enterprise.txt
- Scripts/generate_release_zip.sh
@pasin This is to update the latest EE license file for all of mobile products.  I've added the check if building on jenkins, then get the official license file from the build repo: https://github.com/couchbase/build/tree/master/license/couchbase-lite.  I didn't want to break the existing dev build incase dev doesn't have build repo checkout.
> MB-28145 Update EE license file for CBL iOS

- Objective-C/CBLDatabase.mm
- Objective-C/CBLDocument.mm
- Objective-C/Internal/CBLC4Document.h
- Objective-C/Internal/CBLC4Document.mm
- Objective-C/Tests/ReplicatorTest.m
Fixes resolution of conflicts when a doc has been deleted locally but updated on the server.
* Updated LiteCore to get its half of the fix.
* When creating a merge revision to resolve a conflict, make it a
deletion when necessary (using the new param of c4doc_resolveConflict.)
* Fixed a bug where CBLC4Document's properties referred to the current
revision, not the selected revision (which is different when a
conflict is being resolved.)
* Re-enabled testPullConflictDeleteWins_SG, now that it passes.
For couchbase/couchbase-lite-core#433
> Fixed merging of conflicts involving a deletion

- Source/CBLMultiStreamWriter.m
- Source/CBLMultipartWriter.m
- Source/CBL_Attachment.h
- Source/CBL_Attachment.m
- Source/CBL_BlobStore.h
- Source/CBL_BlobStore.m
* Made CBLMultipartWriter add the attachment object instead of opened stream to the list of the multipart inputs, which will be later opened as streams when writing to the output.
* In the CBLMultiStreamWriter’s -streamForInput: mode, if the input in an CBL_Attachment object, returns an opened attachment stream.
#2144 #2130
> Fixed #2144 and #2130 : Attachment files to be push are all opened at once

- Swift/Query.swift
*Summary:* This small PR prevents a crash where an `unowned`, deinit'd `Query` reference is fatally accessed. It changes the reference to `weak` with a guarded unwrap in the `listener` closure created in `addChangeListener`. 
*Context:* our app uses `Query` change listeners to populate views. These change listeners are tied to the life cycle of view controllers on a navigation stack. When these view controllers appear, they refresh from network and update some Couchbase documents. 
*Problem:* In one particular case, we had two screens (root view controller `A` and pushed view controller `B` for reference) which both added similarly configured change listeners on an identical query, with different instances of `Query` with different `ListenerToken` instances. We encountered a race …
> Use weak reference / guard in place of unowned in Query addChangeListener closure.

- Objective-C/Internal/Replicator/CBLWebSocket.mm
* When HTTP redirect happens, if using proxy, need to send a CONNECT request to the redirected host as well.
* The _logic.useProxyCONNECT is reset to NO after the CONNECT response is received. When sending the second CONNECT request for the redirected HOST, need to ensure that _logic.useProxyCONNECT is set to YES, otherwise the CONNECT request will not be sent.
* Moved `_logic.useProxyCONNECT = YES` from -initWithURL:c4socket:options:  to -_connect method where the CONNECT request will be sent.
#2179
> Fix HTTP redirect not working when using client proxy

- Objective-C/CBLQueryMeta.h
- Objective-C/CBLQueryMeta.m
- Objective-C/Tests/QueryTest.m
- Swift/Meta.swift
- Swift/Tests/QueryTest.swift
* add methods to handle the swift isDeleted call.
* refactored and grouped the sequence and isDeleted methods calls.
* removed unused variable from CBLQueryTest
* add 3 test cases with no deleted file, single deleted doc, and multiple deleted document.
Fix: #2232
> feat: Meta.isDeleted for Swift

- Objective-C/CBLDatabase.h
- Objective-C/CBLDatabase.mm
- Objective-C/Tests/DatabaseTest.m
- Swift/Database.swift
- Swift/Tests/DatabaseTest.swift
* add ObjC private method for purging the document by documentID
* private method will replace the document reference of the baseDocument pointer if provided
* thread safe private method
* re-used same private implementation in purgeDocument(document)
* copied and re-used all the test cases considered while purgingDocumentByDocument, in both ObjC and Swift.
* handling of the purging of deleted documents. 
Fix: #2231
> Feat: Implement Purge document by ID

- Objective-C/Tests/DatabaseTest.m
* tests to check whether the deleted docs are able to set expiration and whether they are working.
* test case limited to execute within 4 seconds. 
Fix: #2227
> Test: document expiry on deleted docs

- Objective-C/CBLReplicatorConfiguration.m
* certificate was not retained in the constructor, but was doing in the setter method.
* setter method will be called, when we are setting the configuration object directly.
* But while setting the already allocated object configuration through replicator:init:config: it will again allocate separate config, which in turn was not retaining the certificate object.
* tested by enabling the CBL_TEST_HOST. And now tests are passing.
Fix: #2238
> Fixed #2238 : pinnedServerCertificate memory release issue

- Objective-C/CBLDatabase.mm
* building through the script was failing due to the type from lite-core. fixed it by changing the type.
* only happens when the framework was built from script.
* successfully ran the script.
> fix: ./Script/build_framwork.sh failure

- Objective-C/Tests/DatabaseTest.m
* increased the time delay while the rescheduling pf purging happens.
* increased the time delay while the document date is made farther than the current, is working or not. that also seems to tight interval for testing.
* increased the waiting for testWhetherDocumentNotRemovedBeforeExpiry. 
* tested multiple times locally, not breaking.
> Fix: expiration unit test failure

- Objective-C/CBLDatabase.mm
- Objective-C/Tests/DocumentExpirationTest.m
- Swift/Tests/DocumentExpirationTest.swift
* purging of docs are done from the serial queue instead of the global background queue.
* test cases to check for the db.change event is added. 
link: #2266
> Fix: PurgeExpiredDocs from Serial Queue

- Objective-C/CBLQuery.mm
- Objective-C/Internal/CBLLiveQuery.mm
* made the liveQuery functions thread safe.
* if the query is released while accessing the liveQuery updates are being fired, we check for query instance and ignore.
> feat: Make LiveQuery Atomic

- Objective-C/CBLFileLogger.mm
* made the default logging as binary in ObjectiveC
* swift is already in binary format.
> fix: Make default file logging binary

- Objective-C/CBLFileLogger.mm
Fixed the default log directory to the followings:
iOS : <NSCachesDirectory>/CouchbaseLite/Logs
Mac: ~/Library/Logs/<BundleID>/CouchbaseLite
#2306
> Fixed #2306 default log directory

- Objective-C/CBLLog.h
- Swift/Log.swift
* when changing a log level of the custom instance, it should be done before setting the custom instance. 
- as the synchronize call will happen only on setCustom method.
> doc: update with custom instance set info

- Objective-C/CBLReplicator.mm
- Objective-C/Tests/ReplicatorTest.m
* replicator flag was setting to LiteCore flag value.
* enabled the objc test for Pull only. 
* objc push is also failing, which is still investigating. 
* swift is still failing with push and pul, which is also still investigating. 
link: #2303
> fix: replicator flag setting corrected

- Objective-C/Tests/LogTest.m
- Swift/Tests/LogTest.swift
* fixed the issue with filename in seconds instead of milliseconds
* enabled both swift and objc
fix: #2302
> fix: issue with filename in seconds

- Objective-C/Tests/LogTest.m
- Swift/Tests/LogTest.swift
* fixed the unit test failure by making the folder name a random one.
* issue was removing the folder to logs, while logging keeps happening.
fix: #2331
> fix: Unit test failure

- Objective-C/CBLBlob.mm
- Objective-C/CBLQueryParameters.mm
- Objective-C/Internal/CBLData.h
- Objective-C/Internal/CBLData.mm
- Objective-C/Tests/PredictiveQueryTest.m
- Swift/Parameters.swift
- Swift/Tests/PredictiveQueryTest.swift
* Encoded blob in parameters as blob properties + content instead of content only.
* Updated TextModel in unit tests to check the content type of blob.
#2320
> Fix Blob metadata not preserved in predictive query parameters

- .travis.yml
* code folding removed, as that doesn't give advantages. and needs to unfold for every build, analyze.
* if all build, analyse is grouped to form one build and one analyze, this was helpful. but in our case, this is not helping.
* going back to the old format.
> ci: reformat the output

- Swift/Parameters.swift
* corrected the array, dictionary and blob type as optional.
link: #2353
> fix: query parameter type

- Objective-C/Tests/ArrayTest.m
* add{Type} methods were not verified in the unit tests.
* set{Type}:atIndex were not verified in the unit tests.
* insert{Type}: atIndex: were not verified in the unit tests.
* although all these function calls are done towards the root function, setValue: which was already being tested.
Ref: #2376
> unit: add missing method check individually

- Objective-C/Tests/AuthenticatorTest.m
* check authenticate method for the basic and session authenticator
* add space before the function name and return type.
Ref: #2376
> unit: check authenticate method

- Objective-C/Tests/QueryTest.m
- Swift/Tests/QueryTest.swift
* add test which is failing in dot net to validate the failure. but iOS is passing all tests.
* test consists of fetching property with `alias`. 
ref: #2229
> unit: test join by docID

- Objective-C/CBLQuery.mm
- Objective-C/Tests/QueryTest.m
- Swift/Tests/QueryTest.swift
If the title string is `*` or has `* #` as the prefix, fallback to 2.1.x approach by getting the column name from the SelectResult.columnName.
> Fix select all with database alias

- Objective-C/CBLLog.mm
The log message has been reformatted so there is no need to reformat (which doesn’t take care of % character).
#2405
> Not reformat the log message in logCallback()

- Objective-C/CBLSessionAuthenticator.m
* removed the function convertExpires from the class. which was used before #2016 and now it is not used.
> refact: remove unused function

- CouchbaseLite.xcodeproj/project.pbxproj
- Objective-C/Tests/MiscCppTest.mm
* there are a few tests in CPP, which needs to be done from cpp test class itself. so kept a common test file with cpp tests in it.
* convertError method was not tested with some valid and invalid test scenarios.
Ref: #2376
> unit: add misc cpp tests

- Objective-C/Tests/QueryTest.m
* more readable and clear statements.
* include inner join and join. check for number2 as well as number1.
* add comments to the select statements, to distinguish between select and selectDistinct.
Ref: #2376
> refact: more readable

- Objective-C/Tests/ReplicatorTest.m
- Swift/Tests/ReplicatorTest.swift
* add logs to unit tests so that we can identify next time issue happens.
* if need to remove the logs, search for `// TODO: #2420`
ref: #2420
> debug: add logs in push filter

- Objective-C/CBLQuery.mm
- Objective-C/Tests/QueryTest.m
- Swift/SelectResult.swift
- Swift/Tests/QueryTest.swift
* removed the workaround and added the fix for the query column title issue.
* fixed the issue with selectResult with alias in Swift.
> fix: query column title correction

- Objective-C/CBLReplicator.mm
* when the conflict happens, it shouldn't immediately respond with failure. It should send only for documents which finished processing. else wait and send response when it is done/
* nonConflictedDocs: kept separate array and added to it, since removing requires search or shifting.
* added functions to avoid repetition
Ref: #2444
> feat: custom conflict error handling

- Objective-C/Tests/ReplicatorTest+CustomConflict.m
* this happens, when another thread/instance update the same document during the resolver solves(when db is not locked). 
Ref: #2428
> unit: resolver function called twice

- Objective-C/CBLDatabase.mm
- Objective-C/Tests/ReplicatorTest+CustomConflict.m
* when newly created document was returned from the resolve, it will lack the database, handled that scenario by assigning the local-doc.database.
* add merge document conditions to handle, local, remote and newly document returns from the resolve method.
Ref: #2428
> fix: issue with newly created doc without database

- Objective-C/CBLDatabase.mm
- Objective-C/Tests/DatabaseTest.m
* when purge happened during save, we should return NotFound error.
* should also return save false, which is already doing.
ref: #2430
> fix: purge during save conflict

- Objective-C/CBLDatabase.mm
* when doc is pushed back to remote, the crash happened due to fromData(s) == nullptr.
* fixed by handling the [.NET way](https://github.com/couchbase/couchbase-lite-net/blob/master/src/Couchbase.Lite.Shared/API/Database/Database.cs#L1320)
> fix: empty slice as body is crashing when pushing the doc

- Objective-C/CBLDatabase.mm
- Objective-C/Tests/DatabaseTest.m
* exception in conflict handler was not handling properly before.
* now it handles and returns conflict error, with save error.
* returns NO, and conflict error.
* test case added but disabled due to memory issue when exception thrown from the block.
ref: #2430
> fix: exception in conflict handler

- Objective-C/CBLDatabase.mm
* checking database exists, can be done only for the exception case, not necessary to assign the database, since the database has no role in conflict resolution.
> refact: clean check

- Objective-C/Tests/ReplicatorTest+CustomConflict.m
* validate the non blocking by making the first document to sleep.
* then second document should resolve in between.
* order should be doc1(whichever is resolved first) will start, doc2(whichever resolves second) will start, doc2 ends, doc1 ends.
ref:  #2428
> unit: non-blocking resolver

- Objective-C/Tests/DatabaseTest.m
* add conflict handler to be called twice test.
* confusion on either naming, may be the old is not old, as Jens suggested. since this test wil confuse. and cur is not cur, but the savedDoc.
ref: #2430
> unit: conflict handler called twice

- Swift/Tests/ReplicatorTest+CustomConflict.swift
- Swift/Tests/ReplicatorTest.swift
* check whether we can set or get conflict resolver to/from config.
* cannot check whether it is readonly, since setting readonly will result in fatalError. 
* Handling fatalError seems to be more effort, which not sure whether we should be adding or not. 
ref: #2428
> unit: resolver read from/to config

- Objective-C/Tests/DatabaseTest.m
* check with/without update to the current document if we return false from the conflict handler, how the save behaves.
ref: #2430
> unit: cancel conflict handler

- Objective-C/Tests/DatabaseTest.m
* validated the behavior, also make sure we can create the same doc-ID for creating new.
> unit: validate the behaviour when saving a purged doc

- Objective-C/CBLQuerySelectResult.m
- Objective-C/Tests/QueryTest+Main.m
- Swift/SelectResult.swift
- Swift/Tests/QueryTest.swift
* alias was using twice, after the SelectAll(withAlias), we were again passing in the alias. which duplicated the alias.
* removed the redundant test
* updated the lite-core to latest.
> fix: database alias issue

- CouchbaseLite.xcodeproj/project.pbxproj
- Objective-C/CBLConflict.h
- Objective-C/CBLConflict.m
- Objective-C/CBLDatabase.mm
- Objective-C/Tests/CustomLogger.h
- Objective-C/Tests/CustomLogger.m
- Objective-C/Tests/LogTest.m
- Objective-C/Tests/ReplicatorTest+CustomConflict.m
- Swift/Conflict.swift
- Swift/Tests/ReplicatorTest+CustomConflict.swift
* added document id in the conflict model.
* wrong doc-id handling updated with warning message and no error thrown.
* Extracted out the custom-logger helper class to verify the log messages.
* verified wrong-doc-id is sending warning logs as well as no error thrown.
* add warning message if the document is not found or document remote version couldn't choose a conflicting revision.
> feat: update custom conflict resolution for objc

- Swift/Tests/ReplicatorTest+CustomConflict.swift
* validated whether there is only single events are fired when document replication custom conflict resolution happens, and when CCR exception is thrown(skips the ccr).
> unit: swift unit tests for replication events

- Objective-C/Tests/ReplicatorTest+CustomConflict.m
- Swift/Tests/ReplicatorTest+CustomConflict.swift
* check the default conflict resolver logic.
* add one more case in objc and swift with deleting the local and saves the remote with higher generation.
ref: #2428
> unit: default resolver for swift

- CouchbaseLite.xcodeproj/project.pbxproj
- Swift/Tests/CustomLogger.swift
- Swift/Tests/LogTest.swift
- Swift/Tests/ReplicatorTest+CustomConflict.swift
* corrected the wrong doc id test case, to incorporate the update. 
* extracted CustomLogger from LogTest and kept separate, so we can validate any log messages
* validated the warning log when there is a wrong doc-id is passed and resolves
> unit: correct wrong doc id test swift

- Objective-C/CBLDatabase.mm
- Objective-C/CBLDocumentReplication.mm
- Objective-C/CBLReplicator.mm
- Objective-C/Internal/Replicator/CBLDocumentReplication+Internal.h
- Objective-C/Tests/ReplicatorTest+Main.m
- Swift/Tests/ReplicatorTest+CustomConflict.swift
* previously, if the error happened during the conflict was not updating the existing c4Error. Now updated.
* add test to verify if the blob which is from a different database saved, returns error which traverse back to document-replication-listener.
> fix: error caught and update ReplicatedDocument.error

- CouchbaseLite.xcodeproj/project.pbxproj
- Swift/Tests/DatabaseTest.swift
* check when save handler return false, in swift .
* Tests folder kept near the folders, and files below the folder for objc.
* rename the cur to use doc for save handler test method.
* minor open bracket kept same line and not next line.
#2430
> CBL-72: unit: save handler cancel in swift

- Objective-C/CBLReplicator.mm
- Objective-C/Internal/CBLReplicator+Internal.h
1. Refactored the replicator to use an enum state to control start, stop, and suspend.
2. Made conflict resolution concurrent and defer stopped until done.
3. Moved the logic to remove from the active replicator list to the stopped method so that the logic could go along with updating/posting stopped status.
> Made conflict resolution concurrent and defer stopped until done

- Objective-C/CBLReplicator.mm
* Separated started state into running and offline state so that the state can identify when the replicator is offline.
* Renamed kCBLStateUnsuspending to kCBLStateSuspendingCancel.
* Rearraged logic in c4StatusChanged:.
> Separate started state into running and offline state

- Objective-C/Tests/ReplicatorTest+CustomConflict.m
- Objective-C/Tests/ReplicatorTest.m
- Swift/Tests/ReplicatorTest+CustomConflict.swift
- Swift/Tests/ReplicatorTest.swift
* Wrapped the replicator tests that have an expcetion thrown in either ignoreException() or expectException() so that the tests will not be breaked.
* In ReplicatorTest.run(), check if the replicator is stopped or not before calling stop() to avoid the warning message.
> Fix break point in replicator tests when an exception is thrown

- xcconfigs/Project.xcconfig
Removed VALID_ARCHS manual settings to use the default valid arcs automatically determined by the SDK parameter of the xcodebuild command.
> Fix VALID_ARCHS mapping warnings

- CouchbaseLite.xcodeproj/project.pbxproj
- Objective-C/CBLReplicatorConfiguration.m
- Objective-C/Internal/Replicator/CBLReplicatorConfiguration+Swift.h
- Objective-C/Internal/Replicator/CBLReplicatorConfiguration+Swift.m
- Swift/CouchbaseLiteSwift-EE.modulemap
- Swift/CouchbaseLiteSwift.modulemap
- Swift/ReplicatorConfiguration.swift
* BridgingConflictResolver referenced to CBLConflictResolverProtocol which is not visible publicly in CouchbaseLiteSwift.framework, as a result, the swift XCode editor couldn’t fine the definition of CBLConflictResolverProtocol and crashed.
* Bridged between Swift and Objective-C conflict resolver by using Resolver Block instead. The bridging resolver class calling to the Resolver Block is done internally in Objective-C
> Fix CBL-107 Swift XCode editor crash due to BridgingConflictResolver

- README.md
* remove specific version number from title, and from cocoapods(will anyways gets the latest) and carthage(same).
* we can provide specific version number for cocoapods and carthage in release readme's.
> CBL-109:  fix: remove specific branch name

- Swift/Conflict.swift
- Swift/ConflictResolver.swift
* swift was not finding the CBLConflict instance or so. and it was returning an empty instance when used class pointer as variable in struct.
* we suspect it might be due to the removal of private headers
* validated with a sample project
> fix: swift header missing issue

- Swift/Conflict.swift
- Swift/ConflictResolver.swift
* swift was not finding the CBLConflict instance or so. and it was returning an empty instance when used class pointer as variable in struct.
* we suspect it might be due to the removal of private headers
* validated with a sample project
> CBL-146: fix: swift header missing issue (to Cobalt)

- Objective-C/CBLReplicatorConfiguration.m
- Objective-C/Internal/Replicator/CBLWebSocket.mm
* set heartbeat and checkpoint interval
* timeout from the CBL side is removed, and litecore is handling the timeout of 5.0 seconds.
> fix: changes from cobalt

- CouchbaseLite.xcodeproj/project.pbxproj
- Objective-C/CBLDatabase.mm
- Objective-C/Internal/CBLTimer.h
- Objective-C/Internal/CBLTimer.m
* create a wrapper for dispatch source set timer, for all cbl timer tasks.
* for a test trial, check by replacing the document expiry code block.
Not sure, why those extra project file changes showing up. is it XCode automatically removed them?
> feat: add dispatch source set timer

- Objective-C/CBLReplicator.mm
* when replicator starts before its handle being created the nullptr was returned.
* fix by returning replicator handle, and then start the replicator
* agree with Blake on this. https://github.com/couchbase/couchbase-lite-java/pull/139#discussion_r322407475
> CBL-342: fix: race condition

- Objective-C/Internal/CBLTimer.h
* when starts the db with null instance, it causes a run time error.
> fix: run time error - arg null

- Scripts/generate_release_zip.sh
* remove the ee-repo obj-c in case of swift target and swift in case of objc target.
> CBL-373: fix: coverage report update

- Objective-C/CBLDatabase.mm
- Swift/Database.swift
* before deprecated means, no op. now we set console.log.domain and console.log.level from it.
> CBL-437: fix: deprecated setlog level method

- Objective-C/CBLConflict.m
- Objective-C/CBLDatabase.mm
- Objective-C/Tests/ReplicatorTest+CustomConflict.m
* if local and remote are deleted, automatically choose the remote revision. No need to send it to resolve. 
* remove assertion
> CBL-512: Local and remote deleted scenario 

- Objective-C/CBLDatabase.mm
* previously we were using Doc instance, which was expecting a alloc_slice, but we supply a FLSliceResult which was already owned, and it again retained and owned in the constructor.
* also the encode result FLSliceResult was not released after update/create the c4Doc.
> fix: memory leak due to holding fleecedata

- Objective-C/CBLBlob.mm
* `c4blob_getContents` returns C4SliceResult, which needs to be freed.
> fix: leak with blob contents

- Objective-C/CBLDatabase.mm
* get index also returned FLSliceResult which we pass to Doc, in turn cause extra retain count
> fix: FLSliceResult leak

- Swift/Tests/DatabaseTest.swift
- Swift/Tests/ReplicatorTest+CustomConflict.swift
* since objc doesnt support exception, program can end unexpectedly, this might not clear the object pools during an exception happens. which was the reason why objc tests got ignored. 
* Same leak is happening in case of swift but was hidden, so disabling the tests
> conflict object is leaking when NSException is thrown inside it.

- Objective-C/CBLDocument.mm
- Objective-C/CBLReplicator.mm
- Objective-C/Internal/CBLDocument+Internal.h
- Objective-C/Internal/CBLErrorMessage.h
- Objective-C/Internal/CBLErrorMessage.m
- Objective-C/Tests/ReplicatorTest+Main.m
* include revision-id with document
* check c4doc exists, if not return the revision-id
* include revision-id check with all filter unit tests
* update the revision-id signature form lite-core.
* when tries to create the c4doc_singleRevision, but deleted document returns nil with NotFound error. so in that case, we might again needs to save the revision-id and return. so not possible to create c4doc with revision-id, document-id and other info.
> CBL-520: include revision-id with filters

- Objective-C/CBLBlob.mm
* cbl-518 
* cbl-519
* when blob content not used, it is not closed. so release it in dealloc
* return nil, in case of contentStream property asks for it before getting the contents.
* make it in sync with .NET and Android
> CBL-518: CBL-519: blob

- Objective-C/CBLBlob.mm
- Objective-C/Tests/DocumentTest.m
* corrected objc test for blob with object stream
* when blob content not used, it is not closed. so release it in dealloc
* return nil, in case of contentStream property asks for it before getting the contents.
* make it in sync with .NET and Android
> CBL-518: CBL-519: fix: blob

- Objective-C/Internal/CBLTimer.m
* timer was repeating and not a single shot. which was causing the retry logic to run repeatedly.
> fix: retry timer repeating issue

- CouchbaseLite.xcodeproj/project.pbxproj
- xcconfigs/CBL ObjC Tests - iOS App.xcconfig
- xcconfigs/CBL ObjC Tests - iOS.xcconfig
* Include support file path for benchmark.hh file.
* Include Fleece API path in the search path for iOS Test target
* Map the Couchbase Inc, signing team for EE iOS App Target.
> CBL-570: Fix: iOS App Target Failure

- Objective-C/CBLReplicator.mm
- Objective-C/Internal/Replicator/CBLReachability.h
- Objective-C/Internal/Replicator/CBLReachability.m
* previously we were only initializing the replicator when there is some transient error happened.
* now refactored to initialize on start and start the observer when there is any transient error.
* move all reachability functions to a pragma mark.
* seems only the startReachability on dispatchQueue is only used, and run-loop is not used in code.
* convert the global variable "allowReachability" to a local one, since we are initializing on start.
* in case the reachability instance is not initialized, added a verbose log to print, for debugging.
> CBL-563: refac: reachability initialized on start

- Objective-C/CBLDatabase.mm
- Objective-C/CBLMutableDocument.mm
- Objective-C/Tests/ReplicatorTest+CustomConflict.m
* previously when blob throws an nsexception it was returned back to CBL side, recently the Fleece APIs are noexcept, so exceptions thrown can be ignored and only look for error object.
* remove try..catch since the methods are no longer throwable.
* use utility method when creating the CBLError.
* fetch Fleece Error Message before finishing the Encoding, so if there is any error happened, we can pass the error message too.
* related PR: https://github.com/couchbaselabs/fleece/pull/69
> fix: CBL-649: handle encode error

- Objective-C/Tests/PredictiveQueryTest.m
- Objective-C/Tests/ReplicatorTest+Main.m
- Objective-C/Tests/ReplicatorTest.m
- Swift/Tests/PredictiveQueryTest.swift
- Swift/Tests/ReplicatorTest.swift
* Workaround to ensure that replicator's background cleaning task
https://github.com/couchbase/couchbase-lite-core/issues/520
https://github.com/couchbase/couchbase-lite-core/issues/539
* Since CBL-671 is fixed, enable the testIndexMultiplePredictionValuesUsingValueIndex
* Updated the issue number from 652 to 704
> Fix: Remove TODOs (Easy PR)

- Objective-C/CBLDatabase.mm
- Objective-C/Internal/CBLDatabase+Swift.h
- Objective-C/Tests/DatabaseTest.m
- Swift/Database.swift
- Swift/Tests/DatabaseTest.swift
* in batch API when thrown exception(from block) was not cancelling the transaction.
* created separate method with throwable block and start handle when swift throws exception.
* in case of objc, same issue exists. 
* include unit tests
> CBL-717: Fix in..batch API

- CouchbaseLite.xcodeproj/project.pbxproj
- Objective-C/CBLReplicator.h
- Swift/Replicator.swift
- Swift/Tests/ReplicatorTest+PendingDocIds.swift
* copy pending document ids feature from previously reverted change.
* include unit tests for `pendingDocumentIDs` and `isDocumentPending` API
* include no-throw for swift, in objc header
* since the background and suspended state setting cannot be done from swift, skipping the offline test in swift. 
ref: #2583, #2567
> CBL-711: feat: swift pending document ids APIs

- Objective-C/CBLQueryExpression.m
- Objective-C/CBLQueryMeta.h
- Objective-C/CBLQueryMeta.m
- Objective-C/CBLQuerySelectResult.m
- Objective-C/Internal/CBLPropertyExpression.h
- Objective-C/Internal/CBLPropertyExpression.m
- Objective-C/Internal/CBLQuery+Internal.h
- Objective-C/Tests/QueryTest+Meta.m
- Objective-C/Tests/QueryTest.h
- Swift/Meta.swift
- Swift/Tests/CBLTestCase.swift
- Swift/Tests/QueryTest.swift
* Implemented Query’s Meta.revisionID in ObjC and Swift
* Removed obsolete code that was used for computing the column name on Meta and All properties.
> CBL-769 : Implement Query’s Meta.revisionID

- CouchbaseLite.xcodeproj/project.pbxproj
- Objective-C/CBLDatabase.mm
- Objective-C/Internal/CBLDatabase+Internal.h
* Link with libLiteCoreREST-static.a and libLiteCoreWebSocket.a.
* Add CBLDatabase’s getPublicUUID method.
#CBL-817
> Add support for implementing CBLURLEndpointListener

- xcconfigs/Project.xcconfig
The values are based on the VALID_ARCHS defined in LiteCore. 
Note: It's not cleared if 'arm64e' will be needed or not so I haven't included it.
CBL-942
> Add VALID_ARCHS to Project.xcconfig

- Objective-C/CBLReplicator.mm
Please not that this commit doesn’t implement the new Replicator.start(reset).
> Update to use the new repl_start

- CouchbaseLite.xcodeproj/project.pbxproj
- Objective-C/Tests/URLEndpointListenerTest.m
* add test for validating  ports.
* add tests for get URLs, but test fails due to wrong scheme in URLs
* add tests for connection status, but again fails the active connection count, lite core fails.
> CBL-817: Add unit tests for URLEndpointListener 

- CouchbaseLite.xcodeproj/project.pbxproj
- CouchbaseLite.xcodeproj/xcshareddata/xcschemes/CBL ObjC Tests - iOS App.xcscheme
- Objective-C/Tests/CBLTestCase.m
- Objective-C/Tests/TLSIdentityTest.m
- Objective-C/Tests/iOS/AppDelegate.m
- Swift/Tests/CBLTestCase.swift
- Swift/Tests/TLSIdentityTest.swift
- Swift/Tests/iOS/AppDelegate.swift
* Added TLSIdentityTest for Swift
* Changed how to check host app for tests
* Disabled testCreateIdentityFromData on macOS
CBL-913
> Add TLSIdentityTest for Swift

- CouchbaseLite.xcodeproj/project.pbxproj
- Objective-C/Tests/ReplicatorTest.h
- Objective-C/Tests/ReplicatorTest.m
- Objective-C/Tests/URLEndpointListenerTest.m
- Swift/CouchbaseLiteSwift-EE.modulemap
- Swift/Tests/CBLTestCase.swift
- Swift/Tests/ReplicatorTest.swift
- Swift/Tests/URLEndpointListenerTest.swift
* Added tests for Swift’s Client Cert Authentication.
* Added convenience run method that will create config and replicator at the same time.
* Fixed bugs not checking the error when running the Replicator in tests.
* Cleaned up some method signatures in tests.
> Add swift client cert auth tests

- Objective-C/Tests/PredictiveQueryTest.m
- Swift/Tests/PredictiveQueryTest.swift
* sqlite was optimized, which resulted in not running the query, since db was empty.
* dummy doc inserted before the query
> CBL-1032: fix: non supported test failure

- Objective-C/CBLReplicator.h
- Objective-C/CBLReplicator.mm
- Objective-C/Tests/ReplicatorTest+Main.m
- Objective-C/Tests/ReplicatorTest.h
- Objective-C/Tests/ReplicatorTest.m
- Swift/Replicator.swift
- Swift/Tests/ReplicatorTest.swift
* Implemented Replicator's start(reset) and deprecate resetCheckpoint()
* Fixed replicator not getting stopped in Objective-C unit tests
CBL-1012
> Implement Replicator's start(reset) and deprecate resetCheckpoint()

- Objective-C/Tests/URLEndpointListenerTest.m
* validate the error when pushing changes to readonly listener
* disabled the test since replicator is not ready to return error: open issue
> test: readonly listener error

- Objective-C/Tests/URLEndpointListenerTest.m
- Swift/Tests/URLEndpointListenerTest.swift
* Add test for URLEndpointListener.tlsIdentity property.
* Refactor how to clean up or stop the listener in tests by using stopListen or stopListener:.
> Add test for listener.tlsIdentity property and refactor listener clean up in tests

- Objective-C/CBLReplicator.mm
- Objective-C/Internal/Replicator/CBLReachability.h
- Objective-C/Internal/Replicator/CBLReachability.m
* Make sure to not set the internal state to others after the replicator is in stopping state.
* Make sure to not start the reachability in stopping state.
* Make sure to check whether the reachability is still mornitoring instead of checking if the instance is nil or not as now when we stop the reachability, we don’t set the reachability to nil.
#CBL-1053
> Fix missed handling the replicator in stopping state

- Objective-C/Tests/ReplicatorTest+MessageEndPoint.m
- Objective-C/Tests/Util/CBLMockConnection.h
- Objective-C/Tests/Util/CBLMockConnection.m
- Objective-C/Tests/Util/CBLMockConnectionErrorLogic.h
- Objective-C/Tests/Util/CBLMockConnectionErrorLogic.m
* Fixed threading and misordering of messages sent when closing the connection with error.
* Refactored to not use queue and ensure thread safe as necessary.
* Fixed code style formatting.
> Refactor CBLMockConnection to fix intermittently failure in tests

- CouchbaseLite.xcodeproj/project.pbxproj
- Objective-C/Tests/ReplicatorTest+Main.m
- Objective-C/Tests/ReplicatorTest+MessageEndPoint.m
- Objective-C/Tests/ReplicatorTest.h
- Objective-C/Tests/ReplicatorTest.m
- Scripts/generate_release_zip.sh
- Scripts/xctest_crash_log.sh
* Added crashWhenStoppedTimeoutOccurred property in ReplicatorTest
* Enabled crashWhenStoppedTimeoutOccurred in testMEP2PWithMessageStream and testMEP2PWithByteStream for investigating the replicator stalls issue.
* Added Scripts/xctest_crash_log.sh to print all xctest’s crash logs or delete all xctest crash logs.
* Used xctest_crash_log.sh in genearte_release_zip to print out the crash logs when test fails.
> Add option to crash when the replicator not stopped in tests

- Objective-C/Tests/ReplicatorTest+CustomConflict.m
- Swift/Logger.swift
- Swift/Tests/ReplicatorTest+CustomConflict.swift
* Added listener log domain to Swift
* Fixed tests that didn’t reset the custom logger back to nil
> Fix missing listener log domain in Swift

- Scripts/generate_release_zip.sh
* xcpretty was retuning zero status, bash default uses the exit code of the last command.
* now we use the exit code of the pipeline from pipestatus array
> fix: `generate script` succeeds even when `build_framework` script fails

- Objective-C/Internal/CBLNewDictionary.mm
- Objective-C/Tests/DocumentTest.m
* since the dictionary elements were not getting calls to cbl_toCBLObject. which was causing it to convert to respective type from fleece, which leads to fleece exception.
* unknown though, _dict inside CBLMutableDocument is converted to CBLNewDictionary than CBLMiutableDictionary during runtime?
> CBL-745: `CBLNewDictionary` elements where not converted to `cbl_toCBLObject`

- xcconfigs/Project_Release.xcconfig
* enable this to remove all absolute path from binary & dsym
* https://bugs.swift.org/browse/SR-12783?focusedCommentId=56548&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-56548
* But the issue(CBL-896, Couldn't IRGen expression) we encounter with XCode 11.x is not present in XCode 12 Beta. 
* i have tested only on my machine. probably needs to test this again, once the Jenkins job builds it.
> -no-serialize-debugging-options

- Objective-C/Tests/Util/CBLMockConnection.m
* The message could be sent out-of-order and that causes the tests to failed intermittently due to the error such as "CouchbaseLite Network ERROR: {BLIPIO#5489} Caught exception handling incoming BLIP message: BLIP protocol error: Bad incoming REQ #2 (too high)".
* Synchronizing the sending message to prevent message out-of-order.
CBL-1092
> Synchronize sending message in CBLMockConnection

- Objective-C/CBLReplicator.h
- Objective-C/CBLReplicator.mm
- Objective-C/Internal/CBLReplicator+Internal.h
- Objective-C/Internal/Replicator/CBLWebSocket.mm
- Objective-C/Tests/URLEndpointListenerTest.m
- Swift/Replicator.swift
- Swift/Tests/URLEndpointListenerTest.swift
* Implement Replicator.serverCertificate property that has the value updated from CBLWebSocket.
* Reset the serverCertificate when starting the replicator.
* For Objective-C, add the note the API doc that the serverCertificate should be explictly retained / released as the CF Object doesn’t get ARC by default.
CBL-1095
> Implement Replicator.serverCertificate property

- CouchbaseLite.xcodeproj/project.pbxproj
- Objective-C/CBLDatabase.mm
- Objective-C/CBLReplicator.mm
- Objective-C/Internal/CBLDatabase+Internal.h
- Objective-C/Internal/CBLLiveQuery+Internal.h
- Objective-C/Internal/CBLLiveQuery.mm
- Objective-C/Internal/CBLReplicator+Internal.h
- Objective-C/Internal/Replicator/CBLStoppable.h
- Objective-C/Tests/DatabaseTest.m
* listener, replicator, livequery can all implements stoppable protocol.
* so we can avoid duplication of code in case of more stoppable instances, like message-endpoint-listener(CBL-950).
> stoppable protocol

- Objective-C/Tests/Util/CBLMockConnection.h
- Objective-C/Tests/Util/CBLMockConnection.m
Ensure that the client reports open connection completion when the server has successfully open the connection.
> CBL-1114: Fix open connection handshake bug in CBLMockConnection

- Objective-C/CBLDatabase.mm
- Objective-C/CBLReplicatorConfiguration.m
- Objective-C/Internal/CBLReplicator+Internal.h
- Objective-C/Internal/Replicator/CBLWebSocket.mm
- Objective-C/Tests/ReplicatorTest+Main.m
- Objective-C/Tests/ReplicatorTest.h
- Objective-C/Tests/ReplicatorTest.m
- Objective-C/Tests/URLEndpointListenerTest.m
- Swift/ReplicatorConfiguration.swift
- Swift/Tests/ReplicatorTest.swift
- Swift/Tests/URLEndpointListenerTest.swift
* remove the enum and use a bool indicating whether only self-signed is accepted
* for every blip request, we look for cookies, if no cookies saved, we only print warning and not an error.
> cbl-1094: update the server verfication mode

- Jenkinsfile
Jenkins slave is configured with 2 executors now to allow official build & test running in parallel.
Hence, we need to disable concurrent build option in Jenkinsfile to ensure 2 PR build don't kick simultaneously.
-Ming Ho
> disable concurrent build in Jenkinsfile in case multiple PR kicks off at the same time

- Objective-C/Internal/CBLDatabase+Internal.h
This method returns nil when the db has no saved cookies, so its
return value should be nullable. (I hit an undefined-behavior
sanitizer warning on this today.)
> CBLDatabase.getCookies: should have nullable result

- Objective-C/Internal/CBLStatus.mm
- Objective-C/Tests/URLEndpointListenerTest.m
- Swift/Tests/ReplicatorTest.swift
- Swift/Tests/URLEndpointListenerTest.swift
* Fixed the error code for client cert auth error
* Added unit tests for testing failed cases for client cert auth.
* Shorten the test names
* Fixed crash check checking error in test.
CBL-1177
> Fix client cert auth error

- Objective-C/CBLDatabase.mm
* check for error, if error show a warning.
* check cookie exists, if not print a verbose log and return empty
> CBL-1194: update the get cookie log

- Scripts/generate_release_zip.sh
SHA is generated, instead, during s3 upload.  no need to generate md5 or sha here.
-Ming Ho
> CBD-3572, md5 is no longer needed for the release.

- Objective-C/Tests/URLEndpointListenerTest.m
- Swift/Tests/URLEndpointListenerTest.swift
- Added URLEndpointListenerTest.testStopLististener()
- Disabled the test until CBL-1243 is fixed
> Add URLEndpointListenerTest.testStopListener

- CouchbaseLite.xcodeproj/project.pbxproj
- Objective-C/Tests/ReplicatorTest+PendingDocIds.m
- Swift/Tests/ReplicatorTest+PendingDocIds.swift
* multiple change listener one which fulfills the expectation and second with getting pendingDocIds status, might cause first done, and second doesn't.
* result might be sometimes, getting replicator which is already finished. as well as leak in lite core objects.
> CBL-1224: fix: race condition with change listener

- Objective-C/Tests/URLEndpointListenerTest.m
- Swift/Tests/ReplicatorTest.swift
- Swift/Tests/URLEndpointListenerTest.swift
* Modified the stop listener according to the recent change in LiteCore to make GoingAway error non-transient error.
* Enabled the stop listener test
> Enable stop listener test

- Objective-C/Internal/Replicator/CBLWebSocket.h
- Objective-C/Internal/Replicator/CBLWebSocket.mm
- Objective-C/Tests/ReplicatorTest+Main.m
* previous parsing logic was wrong, corrected
* include a unit test to validate the parse method
* as per the documentation, https://tools.ietf.org/html/rfc6265#section-4.1.1, any ASCII except control characters can become cookie value, so I have used bell(^G) character
> CBL-1247: Correct the cookie logic

- Swift/Tests/MessageEndpointTest.swift
* avoid crashing but logs. 
* this doesn't happens consistently, and passing 5/5 times locally
> CBL-1206: flaky test: logs instead of crash

- Objective-C/Tests/URLEndpointListenerTest.m
- Swift/Tests/URLEndpointListenerTest.swift
* update test to ignore the local network, since the iphone simulator might pick up hostname instead of the localhost name
> skip local network in unit test

- Swift/ArrayObject.swift
- Swift/Document.swift
- Swift/DocumentFragment.swift
- Swift/Fragment.swift
- Swift/MutableArrayObject.swift
- Swift/MutableDictionaryObject.swift
- Swift/MutableDocument.swift
- Swift/MutableFragment.swift
- Swift/Result.swift
* Cast to the Objective-C Protocol type that defines the subscript method.
* The fix is harmless and works with XCode 11.7.
> CBL-1111 : Fix value type has no subscripts issue when building with XCode12 Beta

- Objective-C/Tests/URLEndpointListenerTest.m
- Swift/Tests/URLEndpointListenerTest.swift
* fix the connection count non-reliable check
* enable the test which are already fixed on lite core.
* somehow this test was not enabled when we close the master task.
> test: enable unit test

- Objective-C/Tests/URLEndpointListenerTest.m
Cleaning up the replicator and listener at the end of test
> test: race condition clenaup 

- Objective-C/Tests/iOS/Info.plist
- Swift/Tests/iOS/Info.plist
* include bonjour servcie name in info plist to grant permission  else will return NSNetServicesErrorCode  -72008
* only impacts the unit tests. 
* needs to cherry pick to Hydrogen branch too.
> test fix: bonjour service name add to InfoPlist

- Swift/ArrayObject.swift
- Swift/Blob.swift
- Swift/DictionaryObject.swift
- Swift/Document.swift
- Swift/Tests/ArrayTest.swift
- Swift/Tests/MessageEndpointTest.swift
* Fixed warning about hashValue deprecated
* Fixed warning about casting
* Fixed warning about default switch case
> Fix Swift Warnings

- Objective-C/Tests/TLSIdentityTest.m
- Scripts/generate_release_zip.sh
- Swift/Tests/TLSIdentityTest.swift
* setup and teardown were accessing the keychain, which will return exception.
* fix the generate zip script, to use iOS_App target instead of the Swift target since keychain unit tests also consider for code coverage
> CBL-1290: fix: keychain access denied for Swift_EE target

- Objective-C/Tests/URLEndpointListenerTest.m
* with unit tests, refactored the code to reuse the tlsIdentity creation and cleanup methods
* renamed the previous test : `testPasswordAuth` to `testNonTLSPasswordListenerAuthenticator`
> test: add null listener authenticator tests

- Objective-C/CBLDatabase.mm
- Objective-C/Tests/DatabaseTest.m
* Started using C4DatabaseConfig2
* disabled test for special database name
* Updated the APIs (1)c4db_getIndexesInfo, (2)c4db_deleteNamed, (3)c4db_copyNamed, (4)c4db_openNamed
* Parsed the indexInfo and return only name(since new lite core API includes more info)
* Fixes: CBL-1392
* Relates to: CBL-1315
> LiteCore API Update

- Scripts/generate_release_zip.sh
* slather was using wrong scheme name
* also, without cleaning and testing wsa resulting in similar coverage data not found issue
* code cleanup(single line to multi line)
http://mobile.jenkins.couchbase.com/job/couchbase-lite-ios-edition-test/266/
> fix: hydrogen - coverage data not found issue 

- Objective-C/CBLDatabase.mm
* config directory setting inside the static was causing the already released directory string to be used when c4config is used second time
* more details of the error : CBL-1395
> fix: stack memory usage after release

- Objective-C/Internal/Replicator/CBLTrustCheck.mm
- Objective-C/Tests/URLEndpointListenerTest.m
- Swift/Tests/URLEndpointListenerTest.swift
* add missing unit tests for URLEndpointListener - ObjC & Swift
* fixes: CBL-1477
> test: Add missing unit tests URLEndpointListener

- Swift/Tests/TLSIdentityTest.swift
- Swift/Tests/URLEndpointListenerTest.swift
* remove unnecessary function and use the single line deleteIdentity. 
* remove stopListen and make stopListener with default empty param.
* keeps the 10.3 instead of 10.0 in the tests file, so we can skip the enclosed check.
> test: cleanup 

- Swift/Tests/TLSIdentityTest.swift
- Swift/Tests/URLEndpointListenerTest.swift
* error accessing class var, instead of local var fixed
* cleanup dummy TLSIdentity before and after
* use dummy TLSIdentity, instead of using same tlsIdentity to avoid the duplicate cert error
> test: error accessing class var, instead of local var fixed

- Objective-C/CBLDatabase.mm
* This is part of CBL-795, clean up of state variables. 
* But this PR only replaces the state bool variables to a state variable CBLDatabaseState(closed, open, closing)
* Since this changes has bigger impact, another PR will include LiveQuery state variable update.
> Cleanup database state variable

- xcconfigs/Project.xcconfig
* make it consistent with LiteCore archs. https://github.com/couchbase/couchbase-lite-core/blob/master/Xcode/xcconfigs/Project.xcconfig#L34-L39
* binary not tested but the xcframework starts including arm64 with the macOS framework.
> add arm64 arch with the macosx for M1

- Objective-C/Tests/ReplicatorTest+CustomConflict.m
- Swift/Tests/ReplicatorTest+CustomConflict.swift
* since the concurrent conflict queue is executing the blocks. 'order.count' can change in between which ?might skip the thread sleep
> test: fix race

- Scripts/generate_release_zip.sh
- xcconfigs/Project.xcconfig
* this is temporary fix and only for testing purpose.
* will validate the xcframework from Apple M1 with this PR.
> testing-only: disable .framework and only create xcframework

- Scripts/build_framework.sh
- Scripts/generate_release_zip.sh
* to avoid failure with .framework build, skip arm64 for simulator build.
* XCFramework alone build changed to building combined binary build.
* remove objc directory once the build is done.
> .framework skip arm64 for simulator

- Objective-C/CBLDatabase.mm
- Objective-C/CBLDocument.mm
- Objective-C/CBLMutableDocument.mm
- Objective-C/Internal/CBLC4Document.h
- Objective-C/Internal/CBLC4Document.mm
- Objective-C/Internal/CBLDatabase+Debug.mm
- Objective-C/Internal/CBLDatabase+Internal.h
- Objective-C/Internal/CBLDocument+Internal.h
- Objective-C/Tests/DatabaseTest.m
- Objective-C/Tests/ReplicatorTest+CustomConflict.m
- Swift/Tests/DatabaseTest.swift
- Swift/Tests/ReplicatorTest+CustomConflict.swift
- xcconfigs/Project.xcconfig
I have made two separate commits when updating Lite-Core: Before and After enabling version-vector. Here are summary of the changes:
**Before enabling version-vector:**
* Used `c4doc_getProperties` instead of `c4doc.selectedRev.body` and ensured to retain the body through the life of the document according to its selected revision. This has been done in CBLC4Document that wraps and retains C4Document object.
* Moved `-encode:` method from `CBLMutableDocument` to `CBLDocument` itself as overriding is not needed anymore.
* Used `c4db_getDoc` instead of `c4doc_get` as `c4doc_get` is semi-deprecated.
* Used `C4DocContentLevel.kDocGetAll` when creating a conflicting doc in `CBLDatabase`’s `-resolveConflictInDocument:` as we need to select a conflicting revision.
* Added another constructor in …
> Update to use latest lite-core and enable version vector

- Objective-C/CBLDatabase.mm
- Objective-C/CBLDatabaseConfiguration.h
- Objective-C/CBLDatabaseConfiguration.m
- Swift/DatabaseConfiguration.swift
* Until SG supports version vector, disable version vector by default until ready.
* Add enableVersionVector flag to DatabaseConfiguration for enabling version vector. The enableVersionVector is temporary until we enable version vector from CBL to SGW.
> Disable Version Vector by Default

- Objective-C/Internal/CBLFullTextMatchExpression.m
- Objective-C/Tests/ReplicatorTest.h
- Objective-C/Tests/ReplicatorTest.m
- Objective-C/Tests/URLEndpointListenerTest.m
- Swift/Tests/ReplicatorTest.swift
- Swift/Tests/URLEndpointListenerTest.swift
1. testStopListener test: CBL-1664
* Since the default retry count was 3 for single shot, it was stopping before 10secs, and now the max-retry count changed to 9, it was in offline state which resulted in the failure of the test. Now we will include the maxRetry with the unit test run-replicator function.
* enabled the test 
2. testWhereMatch: CBL-1839
* corrected the MATCH()
> test: fix unit tests 

- Objective-C/CBLErrors.h
- Objective-C/Tests/URLEndpointListenerTest.m
- Swift/Tests/ReplicatorTest.swift
* when both replicators ran concurrently and false expectation to finish in similar time.
* now its running separately, and test validation for replicator and listener on same database also done.
> CBL-1455: Fix flaky test

- Swift/ReplicatorConfiguration.swift
- Swift/Tests/DatabaseTest.swift
- Swift/Tests/ReplicatorTest.swift
- Swift/Tests/URLEndpointListenerTest.swift
1. Ensure that all of the properties will be initialized correctly when using the new Configuration API.
- testSetDatabaseConfigurationProperties
2. Ensure that all non required properties are initialized with their default value correctly when they are not set.
-  testDefaultDatabaseConfiguration
3. Ensure that the configuration object specified to the target object’s constructor is copied and subsequent changes to the original configuration object will not affect the target object’s configuration.
-  testSetDatabaseConfigurationProperties
4. Ensure that the configuration object specified to the configuration’s constructor is copied and subsequent changes to the original configuration object will not affect the new configuration’s object.
- testCopyingDatabaseConfiguration**
1. Ensure …
> CBL-1879: Add unit tests to validate the Config API

- Objective-C/CBLReplicator.mm
` unused variable 'err'` 
* its an unnecessary check, or assert will fail.
> fix: build error

- Objective-C/CBLReplicator.mm
- Objective-C/CBLReplicatorConfiguration.h
- Objective-C/CBLReplicatorConfiguration.m
- Swift/ReplicatorConfiguration.swift
* property value is not set to the lite core, property is added to the class.
* linked the Jira ticket to track the set to lite core task - CBL-1976
> CBL-1972: Add enableAutoPurge property to replicatorConfig

- Objective-C/CBLDatabase.mm
* when config is empty, parent directory is set to empty which will fail the assertion check for parent. 
* will check for empty config, if so will set the default directory, since the directory will be default.
> fix: issue with empty config and empty parent directory 

- Objective-C/CBLQueryDataSource.m
- Objective-C/Tests/QueryTest+Main.m
- Swift/Tests/QueryTest.swift
* Litecore decided that the "FROM" clause would be required in the query. Hence manually, '*' transformed to default database-name. 
* CBL-1923, CBL-1888
* More details comments in the CBL-1888
> CBL-1888: FROM clause is mandatory

- Objective-C/CBLQueryFunction.h
- Objective-C/Tests/QueryTest+Main.m
- Swift/Function.swift
- Swift/Tests/QueryTest.swift
* latest litecore changes with atan2 function, updated documentation and unit tests
* https://github.com/couchbase/couchbase-lite-core/commit/356453cb37ac91be227e0d827fe7c1e51af2a1a9
> CBL-1991: atan2(y,x) instead of atan2(x,y)

- Objective-C/CBLReplicator.mm
- Objective-C/Tests/ReplicatorTest+Main.m
- Previously, we were saving the progress level to set in case replicator is stopped or not yet started. 
- But the same enum is causing the value to be reset to default when its set just after the start [here](https://github.com/couchbase/couchbase-lite-ios/blob/master/Objective-C/CBLReplicator.mm#L173)
- Now we are saving the progress level in both case and set second time, just after the start. Which will make the correct level to be set.
> fix: issue with delete event set with wrong value second time

- Objective-C/CBLQuery.mm
- Swift/Query.swift
- Swift/Tests/QueryTest.swift
* query instance is not save with database.
* add a unit test with validating the n1ql query crash
* description updated with n1ql as well as json string
> fix: issue with n1ql query instance

- xcconfigs/Project.xcconfig
* background monitor methods will be skipped in case of extension
https://github.com/snej/MYUtilities/blob/master/MYBackgroundMonitor.m#L47
https://github.com/snej/MYUtilities/blob/master/MYBackgroundMonitor.m#L67
https://github.com/snej/MYUtilities/blob/master/MYBackgroundMonitor.m#L81
https://github.com/snej/MYUtilities/blob/master/MYBackgroundMonitor.m#L95
* even though we access the UIApplication sharedApplication, its dynamically getting it via performSelector call.
https://github.com/snej/MYUtilities/blob/master/MYBackgroundMonitor.m#L33
> CBL-2168: Add flag for app extension safe APIs

- Objective-C/CBLDatabase.mm
- Objective-C/CBLQueryResultSet.mm
* Protect the `c4queryenum_release` from multiple threads accessing it
* comments about calling the thread-unsafe calls from locks.
> CBL-1920: Thread safety for LiteCore APIs

- Objective-C/CBLQuery.mm
- Objective-C/Internal/CBLQuery+Internal.h
Current lite-core will return the correct columnTitle, no need to hack in platform side.
> Remove the unnecessary check

- Objective-C/Tests/ReplicatorTest+Main.m
* index out of bounds error, due to unexpected idle status from replicator
* this needs to back port to Lithium.
> out of bounds due to multiple idle status

- Objective-C/Tests/ReplicatorTest+Main.m
* most common scenario will be app goes background while data is transferring. make sure it will resume the transfer when it becomes online and continue
> CBL-815: test: add replicator goes offline scenario

- Objective-C/CBLDatabase.mm
- Objective-C/Internal/CBLDatabase+Internal.h
- Objective-C/Internal/Replicator/CBLWebSocket.mm
* keep a state for the web socket to determine closing/closed
* if there is failure in getCookies will return the error, which will check for the state.
> [hydrogen] hotfix-11072

- Objective-C/Internal/Replicator/CBLTrustCheck.mm
- Objective-C/Internal/Replicator/CBLWebSocket.mm
- Objective-C/Tests/TLSIdentityTest.m
* SecTrustGetCertificateAtIndex > SecTrustCopyCertificateChain
* More accurate logs
> CBL-2621: Replace deprecated APIs

- Swift/Ordering.swift
* deprecate CouchbaseLiteSwift.SortOrder, if anyone is using it.
* replace with QuerySortOrder
> CBL-2691: SortOrder is ambiguous with latest iOS

- Objective-C/Tests/URLEndpointListenerTest.m
- Swift/Tests/URLEndpointListenerTest.swift
* JAK found flaky test issues with the pushAndPull replicator. Causing a race with replicators to pull/push before other one pushes it. Which end up in wrong DB.count.
* We are now validating the push and pull separately
> stabilize unit test

- Objective-C/CBLDocument.mm
- Objective-C/Tests/ReplicatorTest+Main.m
* get the attachment present flag check with this call as well c4doc_dictContainsBlobs()
* add a SG unit test, to validate the fix. Its not useful for lithium
> CBL-2825: Fix: [lithium] Attachment missing when doc updated

- Objective-C/CBLReplicatorConfiguration.h
- Objective-C/CBLReplicatorConfiguration.m
- Objective-C/Internal/Replicator/CBLWebSocket.mm
- Swift/ReplicatorConfiguration.swift
* Add network interface option in the replicator config
* cherry-pick - d71b4428d73756ef4f0d7e5ee4640aa09d8b71ae
* We should have a functional test for this feature. 
* tested and is connecting. 
* localhost + en0
* 127.0.0.1 + lo0 
* IPv4 + en0
* IPv6 + en0
* from the logs only difference is setting the network interface. 
```
CouchbaseLite Network Info: <CBLWebSocket: **> connecting thru network interface en0
```
> Add network interface option in the replicator config

- Objective-C/Internal/Replicator/CBLWebSocket.mm
The error code should be kCFHostErrorUnknown to match the logic in CBLStatus.mm.
> Fix addrinfo error to NSError conversion

- Swift/Expression.swift
- Swift/Tests/QueryTest.swift
- Add isValued/isNotValued APIs in Swift
- Also add tests to validate the same
- Seems like deprecated warnings cannot be suppressed in swift, which causes deprecation warnings in the test suite.
> Add isValued/isNotValued APIs in Swift

- Objective-C/CBLQueryResult.mm
- Swift/Tests/QueryTest.swift
* It was '1 << index' where '1' was Signed Int, which made it negative when beyond the Signed Int Max
* Fixed by making '1ULL << index', now its unsigned long long, it is safe up to 64 now.
> Fix CBL-3330: Support upto 64 select items

- Swift/Collection.swift
- Swift/Database.swift
- Swift/ReplicatorConfiguration.swift
- Swift/Scope.swift
* Used kCBLDefaultCollectionName and kCBLDefaultScopeName.
* Updated throwNotOpenEx to do fatalError() and return Never to indicate that the function will never return.
* Removes fatalError() hacks as it is not needed anymore after marking throwNotOpenEx as Never return.
* Fixed scope(name: String), defaultCollection(), collection(name: String, scope: String?) to being able to return nil.
> Some collection fixes in Swift

- Objective-C/CBLDatabase.h
- Objective-C/CBLDatabase.mm
- Objective-C/Internal/CBLCollection+Internal.h
- Objective-C/Tests/CollectionTest.m
- Objective-C/Tests/DatabaseTest.m
- Swift/Collection.swift
- Swift/Database.swift
- Swift/Scope.swift
- Swift/Tests/CollectionTest.swift
* Add unit tests for 8.1 & 8.2
* CBL-3477
Update the code to return nil with CBLErrorNotFound, in case of collection/scope is missing. So that,  swift can check and return nil. 
If not we might end up using a hack to check for 
```
if nsError.code == 0, nsError.domain == "Foundation._GenericObjCError" {
// handle empty error code! 
}
> [test] [swift] 8.1 default collection/scope & 8.2 collections

- Swift/Tests/CollectionTest.swift
* Add unit test about deleted scenario
* `testUseDatabaseAPIWhenDefaultCollectionIsDeleted`: Not added, since fatalError, we can't test from unit test.
> [test] [swift] collection/scope/db deleted scenario

- .gitignore
- CouchbaseLite-Swift.podspec
- CouchbaseLite.podspec
Spaces were changed to underscores in #2654, which broke the local podspec files. This fixes the scheme names and output framework paths.
Also .gitignore the framework builds and logs, as well as the AppCode .idea IDE configuration folder.
> Fix podspecs

- Objective-C/CBLLog.mm
- Objective-C/CBLReplicator.mm
- Objective-C/Tests/ReplicatorTest+Collection.m
* Add unit tests for replicator+collection support
* Use filter & conflict resolver from the collection config. 
* Not included - testCollectionDocumentReplicationEvents - CBL-3569
> [test] [objc] 8.14 Replicator collection tests

- Scripts/pull_request_build.sh
* Remove the CE scheme, since that's already tested via GH Actions
* Not much value with it, we are already checking CE combination for Mac/iOS/catalyst
> Remove the CE schemes from Jenkins validation

- Objective-C/Internal/Replicator/CBLTrustCheck.mm
- Scripts/pull_request_build.sh
- This was working fine on earlier Xcode, since the preprocessor was going through different flow. 
- Pull request script updated to use iPhone 8. Previous SE(2nd get) was unavailable
> [bug-fix] CBL-2973 - Xcode 13.x Update

- Objective-C/Tests/MessageEndpointTest.m
- Swift/Tests/MessageEndpointTest.swift
- Swift/Tests/QueryTest.swift
(1) multiple calls to the expectations  
(2) change listener called in multiple sets
3.1.0 - 235 build failures
```
3.1.0-EE-Swift
Failing tests:
CBL_EE_Swift_Tests:
MessageEndpointTest.testCollectionsContinuousPushPullReplication()
MessageEndpointTest.testCollectionsSingleShotPushPullReplication()
MessageEndpointTest.testMismatchedCollectionReplication()
Reason: Multiple calls made to expectation. 
3.1.0-CE-swift
testLiveQueryReturnsEmptyResultSet
Reason: change listener can be called in mutiple sets.  
3.1.0-EE-ObjC 
Failing tests:
CBL_EE_ObjC_Tests:
-[MessageEndpointTest testCollectionsContinuousPushPullReplication]
-[MessageEndpointTest testPullDoc]
-[MessageEndpointTest testPullDocContinuous]
-[MessageEndpointTest testPushDoc]
Reason: Multiple calls made to expectation. 
```
> fixes for the Jenkins failures

- Swift/Tests/QueryTest.swift
* avoid the change listener is firing immedietly in case of faster device/machine. Making the purge happen after 0.5 wil be enough time to receive both change sets.
> Stabilising unit test

- Scripts/generate_objc_release_zip.sh
- Scripts/generate_swift_release_zip.sh
* specify the destination in the jazzy to avoid the warnings
* specify the binary-basename in the slather to pick correct binary instead of first among the list. 
* Assume, this might be the cause of NaN result, it was selecting the CBL_Swift_Tests.app binary instead of CouchbaseLiteSwift binary.
> [fix] code coverage & doc

- Scripts/generate_objc_release_zip.sh
- Scripts/generate_swift_release_zip.sh
* While testing on Xcode 14, it got updated, and since the Jenkins has Xcode 13.x, we will revert it to iPhone 11
> [fix] ios simulator to use iPhone 11

- Objective-C/CBLReplicatorConfiguration.h
- Objective-C/CBLReplicatorConfiguration.m
- Objective-C/Internal/Replicator/CBLWebSocket.mm
- Swift/ReplicatorConfiguration.swift
* Added experimentNetworkInterfaceUseBindFunction option to the replicator configuration.
* In CBLWebSocket, use bind() function to bind network interface when experimentNetworkInterfaceUseBindFunction is enabled.
> Add experiment option to use bind function

- Objective-C/Internal/Replicator/CBLWebSocket.mm
SocketSecurityLevelKey is overriding the kCFStreamSSLValidatesCertificateChain prop
> Remove the SocketSecurityLevelKey

- CouchbaseLite.xcodeproj/project.pbxproj
- Scripts/build_xcframework.sh
- Scripts/generate_objc_release_zip.sh
- Scripts/generate_release_zip.sh
- Scripts/generate_swift_release_zip.sh
* Generate XCFramework instead of FAT binary
* Pointed the Helium scripts 
1. Scripts/build_xcframework.sh 
2. Scripts/generate_objc_release_zip.sh 
3. Scripts/generate_swift_release_zip.sh
* Updated the generate_release_script to use the above 2nd & 3rd.
> Generate XCFramework instead of FAT

- Objective-C/Tests/MessageEndpointTest.m
- Objective-C/Tests/ReplicatorTest+CustomConflict.m
- Objective-C/Tests/ReplicatorTest+Main.m
- Swift/Tests/MessageEndpointTest.swift
* disable the test
* minor test fix to avoid race with variable ccrCount
* cherry-pick the Helium changes - 30secs timeout for MessageEndpoint tests
> more fixes

- Objective-C/CBLReplicatorConfiguration.h
- Objective-C/Internal/Replicator/CBLDNSService.h
- Objective-C/Internal/Replicator/CBLDNSService.mm
- Objective-C/Internal/Replicator/CBLWebSocket.mm
[AddressInfo]
* Updated port to sockaddr directly by using const_cast - this is not the best practice but it is the simplest way to do.
* Added addrIn and addrIn6 for easier accessing to the ip address structure.
* Added host and interface for debugging and logging purpose.
[CBLDNSService]
* Renamed the class to CBLDNSService for consistency
* Added the logic to check whether the host is already IP Address and notify the result right away.
* Ensured to notify result or error on the dispatch queue.
* Remove kDNSServiceFlagsTimeout flas as we are doing our own timeout to better match the default litecore connection timeout of 15 seconds.
* Used dispatch after instead of NSTimer as NSTimer does work in dispatch queue correctly.
* Updated log messages.
* Updated license
[CBLWebSocket]
* …
> Fix DNS Service, Socket Connect and Cleanup

- Objective-C/CBLDefaults.h
- Objective-C/CBLDefaults.m
- Objective-C/CBLReplicatorConfiguration.m
- Objective-C/Tests/ReplicatorTest+Main.m
- Swift/Defaults.swift
- Swift/ReplicatorConfiguration.swift
- Swift/Tests/ReplicatorTest.swift
* Add the acceptOnlySelfSignedCert from defaults file. 
* Update the latest Defaults file as well
* Unit test updated to include the new default value
> CBL-3912: Use acceptOnlyServerSelfSign from defaults file

- Objective-C/Internal/Replicator/CBLDNSService.mm
error: implicit conversion from integral type 'unsigned int' to 'BOOL' [-Werror,-Wobjc-signed-char-bool-implicit-int-conversion] probably the lower Xcode error, its not happening locally
> fix: build error on Xcode 13.x

- Objective-C/Internal/Replicator/CBLDNSService.mm
values of type 'UInt32' should not be used as format arguments; add an explicit cast to 'unsigned int' instead [-Werror,-Wformat]
> Fix: UInt32 not a format argument

- Objective-C/Internal/Replicator/CBLDNSService.mm
Increased wait interval from 0.5 to 2 seconds for waiting for IPv4 result after getting IPv6 to avoid unexpected delay.
> Increase Wait Interval in CBLDNSService

- Objective-C/Internal/Replicator/CBLWebSocket.mm
Jenkins failure: 
/****-lite-ios-ee/****-lite-ios/Objective-C/Internal/Replicator/CBLWebSocket.mm:447:25: values of type 'UInt32' should not be used as format arguments; add an explicit cast to 'unsigned int' instead [-Werror,-Wformat]
17:47:55 
17:47:55                   self, info.interface);
17:47:55                         ^~~~~~~~~~~~~~
17:47:55 
17:47:55 
17:47:55 
/****-lite-ios-ee/****-lite-ios/Objective-C/Internal/Replicator/CBLWebSocket.mm:490:113: values of type 'UInt32' should not be used as format arguments; add an explicit cast to 'unsigned int' instead [-Werror,-Wformat]
17:47:55 
17:47:55             NSString* msg = $sprintf(@"Failed to connect via the specified network interface %u with errno %d", info.interface, errNo);
17:47:55 …
> fix build error

- Objective-C/CBLCollection.h
- Objective-C/CBLCollection.mm
- Objective-C/Tests/CollectionTest.m
- Swift/Collection.swift
- Swift/Tests/CollectionTest.swift
* NonExisting document shouldn't throw NotFound error inside documentWithID, will skip the error populating. 
* Default Swift API from ObjC overriden(NS_SWIFT_NOTHROW) to avoid throw nilError; 
* ObjC API ending with ':(NSError**)' treated as throwable compulsory return type, but we need nullable(optional) return type.
> CBL-3953: documentWithID shouldn't throw, if document doesn't exists

- Objective-C/CBLCollection.mm
- Objective-C/CBLDatabase.mm
- Objective-C/CBLIndex.h
- Objective-C/CBLIndex.m
- Objective-C/CBLIndexable.h
- Objective-C/Internal/CBLIndex+Internal.h
- Objective-C/Tests/DatabaseTest.m
- Swift/Collection.swift
- Swift/Index.swift
- Swift/IndexConfiguration.swift
- Swift/Indexable.swift
- Swift/Tests/DatabaseTest.swift
* Convenience to deprecate
* Updated the unit tests - swift and objc
> CBL-4080: Separate createIndex(index:) & createIndex(config:)

- Objective-C/CBLCollection.mm
- Objective-C/CBLDatabase.h
- Objective-C/CBLDatabase.mm
- Objective-C/Internal/CBLCollection+Internal.h
- Objective-C/Internal/CBLScope+Internal.h
- Objective-C/Tests/CollectionTest.m
- Objective-C/Tests/DatabaseTest.m
- Swift/Database.swift
- Swift/Tests/CBLTestCase.swift
- Swift/Tests/CollectionTest.swift
- Swift/Tests/QueryTest+Collection.swift
- Swift/Tests/ReplicatorTest+Collection.swift
* As we do not allow to delete the default collection, getting the default collection should return non-null collection for swift.
* Fixed -defaultCollection: collection logic in CBLDatabase to return error correctly, and made getting default collection lazily.
* Cleaned up get collection and get scope implementation in both objective-c and swift, and ensured that there is no NotFound error returned when the collection or scope doesn’t exist.
> CBL-4190 : Fix getDefaultCollection returning nullable

- Objective-C/CBLCollection.h
- Objective-C/CBLCollection.mm
- Objective-C/CBLDatabase.h
- Objective-C/CBLDatabase.mm
- Objective-C/Tests/FragmentTest.m
- Swift/Collection.swift
- Swift/Database.swift
- Swift/Tests/CBLTestCase.swift
- Swift/Tests/FragmentTest.swift
* We have a subscript function in the Database class for getting a document from the database using the subscript syntax such as database[“doc1”]. This is Apple platform only API.  The subscript function in the database class should be deprecated and there should be the same functionality implemented in the Collection class for an alternative API.
* Deprecated subscript function the in Database class for both Swift and Objective-C.
* Implemented subscript function in Collection class.
> CBL-4308 : Add subscript function to Collection class

- Objective-C/CBLCollection.h
- Objective-C/CBLCollection.mm
- Objective-C/CBLDatabase.h
- Objective-C/CBLDatabase.mm
- Objective-C/Tests/FragmentTest.m
- Swift/Collection.swift
- Swift/Database.swift
- Swift/Tests/CBLTestCase.swift
- Swift/Tests/FragmentTest.swift
* Ported the fix (6dbd9d65d5cea7556cd88ab380c10428796913a6) from release/3.1 branch (CBL-4308)
* We have a subscript function in the Database class for getting a document from the database using the subscript syntax such as database[“doc1”]. This is Apple platform only API.  The subscript function in the database class should be deprecated and there should be the same functionality implemented in the Collection class for an alternative API.
* Deprecated subscript function the in Database class for both Swift and Objective-C.
* Implemented subscript function in Collection class.
> CBL-4336 : Add subscript function to Collection class

- CouchbaseLite.xcodeproj/project.pbxproj
* Disabled MessageEndpointTests from the test target as the MultipeerConnectivity that the tests are using stops working on Jenkins’s mac machine. All the tests are passed on my mac.
* Created CBL-4417 for tracking and solving the issue.
> Disable MessageEndpointTests from the test target

- Swift/Tests/CBLTestCase.swift
- Swift/Tests/DatabaseEncryptionTest.swift
- Swift/Tests/DatabaseTest.swift
- add defaultCollection within CBLTestCase so it can be accessed in every test
- update calls in:
- DatabaseEncryptionTest
- DatabaseTest 
defaultCollection should be optional such that it gets released and set to nil prior to database reset/deletion. Otherwise, some tests which involve the operations above would fail.
> CBL-4401: Update tests to avoid use of deprecated api 1

- Swift/Tests/DocumentExpirationTest.swift
- Swift/Tests/FragmentTest.swift
- Swift/Tests/LogTest.swift
- Swift/Tests/MessageEndpointTest.swift
- DocumentExpirationTest
- FragmentTest
- Logtest
- MessageEndpointTest
For the moment, listener tests contain workaround in place to deal with [CBL-4438](https://issues.couchbase.com/browse/CBL-4438) - so is safe to merge. 
Will revise those tests once when the issue is fixed.
> CBL-4403: Update tests to avoid use of deprecated api 3

- Swift/Tests/NotificationTest.swift
- Swift/Tests/PredictiveQueryTest+CoreML.swift
- Swift/Tests/PredictiveQueryTest.swift
- Swift/Tests/QueryTest.swift
- NotificationTest
- QueryTest
- PredictiveQueryTest
Same mention, tests in which listeners are used will be updated for 3.1.1 according to the future changes.
> CBL-4404: Update tests to avoid use of deprecated api 4

- Package.swift
swift-tools-version is a minimum target swift tool version so reverting it back to version 5.3.
> Use Swift tools version 5.3

- Scripts/build_framework.sh
- Scripts/build_xcframework.sh
- Scripts/pull_request_build.sh
* Apple doesn’t allow to include bitcode in the binary and framework anymore. Also when using XCode 14, bitcode is not generated by default.
* Removed the BITCODE_GENERATION_MODE from the build scripts.
* Used the same command as the command used in Github Action to get the lowest version of the simulator to run the test on Jenkins's PR validation.
> CBL-4487 : Remove bitcode flag from the build scripts

- Scripts/build_framework.sh
- Scripts/build_xcframework.sh
- Scripts/pull_request_build.sh
* Apple doesn’t allow to include bitcode in the binary and framework anymore. Also when using XCode 14, bitcode is not generated by default.
* Removed the BITCODE_GENERATION_MODE from the build scripts.
> CBL-4510 : Remove bitcode flag from the build scripts

- Objective-C/CBLCollection.mm
- Objective-C/Internal/CBLCollection+Internal.h
- Objective-C/Internal/CBLDocumentChangeNotifier.h
- Objective-C/Internal/CBLDocumentChangeNotifier.mm
- Objective-C/Tests/CollectionTest.m
- Swift/Tests/CollectionTest.swift
* Made collection weak reference in CBLDocumentChangeNotifier so that there is no cirular reference b/w colletion and its CBLDocumentChangeNotifier objects.
* Added warning when skipping the notification as the collection object has been released and improved warning logs in CBLDocumentChangeNotifier.
* Added tests to ensure that there is no memory leak when not removing listener token in collection (Note : we have checked for C4 Object Leaks in Tests’ teardown).
> CBL-4440 : Fix collection leaks when not removing document change listener token

- Scripts/build_framework.sh
- Scripts/build_xcframework.sh
- Scripts/pull_request_build.sh
* Apple doesn’t allow to include bitcode in the binary and framework anymore. Also when using XCode 14, bitcode is not generated by default.
* Removed the BITCODE_GENERATION_MODE from the build scripts.
* Used the same command as the command used in Github Action to get the lowest version of the simulator to run the test on Jenkins's PR validation.
* Ported from 84018f18375a6b5e5cbcc6f9b08767b0d49620cd in master branch.
> CBL-4486 : Remove bitcode flag from the build scripts

- Swift/Tests/CBLTestCase.swift
- Swift/Tests/ReplicatorTest+Collection.swift
- Swift/Tests/ReplicatorTest+CustomConflict.swift
- Swift/Tests/ReplicatorTest+PendingDocIds.swift
- Swift/Tests/ReplicatorTest.swift
- Swift/Tests/URLEndpointListenerTest+Collection.swift
- Swift/Tests/URLEndpointListenerTest.swift
- replicator tests
- url endpoint listener tests
- small adjustments to base class and aux - the majority is name changing
> CBL-4405: Update tests to avoid use of deprecated api 5

- xcconfigs/Project.xcconfig
According to the support matrix, the iOS 10.0 is deprecated but is still supported.
> Set iOS deployment target version to 10.0

- Objective-C/CBLDatabase.mm
- Objective-C/CBLReplicator.mm
- Objective-C/Internal/CBLDatabase+Internal.h
* Differentiated error message b/w open error and the other errors when getting the default collection.
* Reduced repetitive code that get and use the default collection and handle the error.
> CBL-4327 : Refactor code when using default collection in CBLDatabase

- Objective-C/CBLCollection.mm
- Objective-C/Internal/CBLCollection+Internal.h
- Objective-C/Internal/CBLDocumentChangeNotifier.h
- Objective-C/Internal/CBLDocumentChangeNotifier.mm
- Objective-C/Tests/CollectionTest.m
- Swift/Tests/CollectionTest.swift
Ported the fix from 9ad6715aecdfb12bc3857c11602bdd4dd430bb96 in master branch.
* Made collection weak reference in CBLDocumentChangeNotifier so that there is no circular reference b/w collection and its CBLDocumentChangeNotifier objects.
* Added tests to ensure that there is no memory leak when not removing listener token in collection. The check for memory leak is in the tests’ teardown.
> CBL-4443 : Fix collection leaks when not removing document change listener token

- Objective-C/Internal/CBLDocumentChangeNotifier.mm
Fixed a typo in the warning message found from the previous fix for CBL-4443.
> CBL-4443 : Fix a typo in the warning message

- Swift/Collection.swift
* Ported the fix b48ba0e524b884d6455b3f4fab171fdaa3373784 from master branch.
* Changed to weak self and added warning log when collection ref has been released.
> CBL-4438 : Prevent crash when notifying doc change for already-released collection

- Objective-C/CBLDocument.mm
- Objective-C/Tests/DocumentTest.m
- Swift/Tests/DocumentTest.swift
Fixed CBLDocument’s containsValueForKey: to call the right function when checking if the key exists in the document.
> CBL-4580 : Fix Document’s contains(key:) returning wrong result

- Objective-C/CBLDocument.mm
- Objective-C/Tests/DocumentTest.m
- Swift/Tests/DocumentTest.swift
* Ported the fix (2f8335879b3701f1c0e8d72d8b5c4a07d365ae69) from release/lithium branch.
* Fixed CBLDocument’s containsValueForKey: to call the right function when checking if the key exists in the document.
> CBL-4582 : Fix Document’s contains(key:)

- Objective-C/CBLDocument.mm
- Objective-C/Tests/DocumentTest.m
- Swift/Tests/DocumentTest.swift
* Ported the fix (2f8335879b3701f1c0e8d72d8b5c4a07d365ae69) from release/lithium branch.
* Fixed CBLDocument’s containsValueForKey: to call the right function when checking if the key exists in the document.
> CBL-4581 : Fix Document’s contains(key:)

- CouchbaseLite.xcodeproj/project.pbxproj
- README.md
- xcconfigs/Project.xcconfig
Besides the relevant project config change, the rest of updates are within tests or utility functions - so no affect on the product itself
> CBL-4627: Update Deployment Target to iOS 11.0 and macOS 10.14

- CouchbaseLite.xcodeproj/project.pbxproj
- Objective-C/Internal/Replicator/CBLWebSocket.mm
- Objective-C/Tests/PredictiveQueryTest+CoreML.m
- Objective-C/Tests/ReplicatorTest.m
- Objective-C/Tests/TLSIdentityTest.m
- Objective-C/Tests/URLEndpointListenerTest+Main.m
- Objective-C/Tests/URLEndpointListenerTest.h
- Objective-C/Tests/URLEndpointListenerTest.m
- README.md
- Swift/Tests/PredictiveQueryTest+CoreML.swift
- Swift/Tests/TLSIdentityTest.swift
- Swift/Tests/URLEndpointListenerTest+Collection.swift
- Swift/Tests/URLEndpointListenerTest.swift
- xcconfigs/Project.xcconfig
- ported #3162 from `release/3.1`
- removals of redundant api availability checks
> CBL-4626:  Update Deployment Target to iOS 11.0 and macOS 10.14

- Objective-C/Tests/TLSIdentityTest.m
https://mobile.jenkins.couchbase.com/job/couchbase-lite-ios-objc-edition-build/4756/console
`'SecCertificateCopyPublicKey' is deprecated: first deprecated in macOS 10.14`
- will port to `release/3.1` for 3.1.1 once merged and Jenkins is green
> Fix Jenkins release build

- Objective-C/Tests/TLSIdentityTest.m
https://mobile.jenkins.couchbase.com/job/couchbase-lite-ios-objc-edition-build/4760/
- port from master
- due to version bump of macos
> Fix Jenkins release build (#3166)

- Objective-C/Internal/Replicator/CBLTrustCheck.mm
- Objective-C/Internal/main.m
- Objective-C/Tests/CBLTestCase.m
- Objective-C/Tests/QueryTest+Main.m
- Objective-C/Tests/TLSIdentityTest.m
[CBL-4523](https://issues.couchbase.com/browse/CBL-4523)
[CBL-4524](https://issues.couchbase.com/browse/CBL-4524)
[CBL-4525](https://issues.couchbase.com/browse/CBL-4525)
Decided to make a single PR such that it will be easier and cleaner to port (will also require only 1 new ticket)
This can be safely merged with the following mentions:
**CE** side
- LiteCore **CE** needs update when the final commit for Analysis Warning is merged
**EE** side
- LiteCore **EE** needs update to include https://github.com/couchbase/couchbase-lite-core-EE/pull/35
> Build with XCode 14.3

- Objective-C/CBLQuery.mm
- Objective-C/Tests/LogTest.m
- Swift/Tests/LogTest.swift
As a result of:
- [CBL-4331](https://issues.couchbase.com/browse/CBL-4331), removed options param from use
- [CBL-4621](https://issues.couchbase.com/browse/CBL-4621), updated logging tests
> Update Litecore + misc

- Objective-C/CBLLog.mm
- port of f616eec318a7070be484ea3be415c6396eec65b1
> CBL-4981: Remap Changes LiteCore Log Domain to Database Domain (port)

- CouchbaseLite.xcodeproj/project.pbxproj
- Objective-C/CBLReplicator.mm
- Objective-C/Internal/CBLReplicator+Internal.h
- Objective-C/Internal/Replicator/CBLReplicator+Backgrounding.h
- Objective-C/Internal/Replicator/CBLReplicator+Backgrounding.m
- Objective-C/Tests/ReplicatorTest+Main.m
- Objective-C/Tests/Util/CBLBlockConflictResolver.h
- Objective-C/Tests/Util/CBLBlockConflictResolver.m
* The extending background task shouldn’t be ended if there are still pending conflict resolutions.
* When the app was suspended by the background monitor, any current pending conflict resolutions should be canceled. All cancelled conflict resolutions will be notified and put into the queue again when the replicator is resumed or is restarted.
* Fixed bug that the backgrounding monitor may not be restarted after it was ended.
* Renamed some methods and add comments to code.
* Added test to test suspending conflict resolution.
> CBL-5035 : Fix backgrounding logic to cover conflict resolution

- Objective-C/CBLReplicator.mm
* Fix bad bug of missing the array initialization.
* Added additional check to ensure that there are no more conflicts scheduled after the replicator is stopped. This is not expected to happen as LiteCore will not be stopped event before sending the doc ended notification but to be sure.
> CBL-5035 : Fix missing pending conflict array initialization.

- Objective-C/CBLDatabase.mm
When signal the database thread to wake up and check for the close, the close condition needs to be locked first to avoid race condition.
> CBL-5067 : Fix close database could hang waiting for active components to close.

- Objective-C/CBLCollection.h
- Objective-C/CBLCollection.mm
- Objective-C/Internal/CBLCollection+Internal.h
- Objective-C/Internal/Replicator/CBLConflict+Internal.h
- Objective-C/Tests/CollectionTest.m
- Objective-C/Tests/DatabaseTest.m
- Swift/Collection.swift
- Swift/Tests/CollectionTest.swift
* Implemented Collection’s fullName accessor in Objective-C and Swift.
* Fixed XCode static analysic warning in CBLCoflict+Internal.h
* Fixed XCode static analysic warning in DatabaseTest.m.
> CBL-5203 : Collection’s full name accessor

- Objective-C/CBLQuery.mm
- Objective-C/Internal/CBLQueryObserver.h
- Objective-C/Internal/CBLQueryObserver.m
- Objective-C/Tests/QueryTest+Main.m
- Swift/ListenerToken.swift
- Swift/Query.swift
- Swift/Tests/QueryTest.swift
* Background: Based on LiteCore’s thread safety doc, c4queryobs_* (except c4queryobs_create which is thread-safe) functions should be called under database-exclusive lock. Without doing that, when creating and starting multiple live queries concurrently, there could be a race condition as each live queries try to get the background database at the same time. The result of the race is that multiple background databases could be created but only the lastone stays and the rest will be freed. Therefore, some live queries will hold on to the bad background database which will cause the crash when the database is used.
* Fixed CBLQueryObserver to follow thread-safety instruction by calling c4queryobs_* functions under the database exclusive lock.
* Fixed Swift Query’s ListenerToken’s remove() …
> CBL-4428 : Fix crash when starting multiple live queries concurrently

- Objective-C/CBLBlob.mm
- Objective-C/CBLCollection.h
- Objective-C/CBLCollection.mm
- Objective-C/CBLDatabase.mm
- Objective-C/CBLDocument.mm
- Objective-C/CBLDocumentChange.m
- Objective-C/CBLQuery.mm
- Objective-C/CBLReplicatorConfiguration.m
- Objective-C/CBLScope.h
- Objective-C/CBLScope.mm
- Objective-C/Internal/CBLCollection+Internal.h
- Objective-C/Internal/CBLDocument+Internal.h
- Objective-C/Internal/CBLScope+Internal.h
- Objective-C/Tests/CollectionTest.m
- Swift/Collection.swift
- Swift/DataSource.swift
- Swift/ReplicatorConfiguration.swift
- Swift/Scope.swift
- Swift/Tests/CollectionTest.swift
* Implemented Collection and Scope Database Accessor.
* The database object is retained in the collection and scope object unless the collection object is cached in the database object to avoid the circular reference.
* Only the default collection is cached in the database object as it’s commonly used in the old decrecated functions that are redirected to the default collection.
* Refactor the code as now the database object from collection will not be null. This made a lot of code simpler.
* Additonal : fixed collection's hash function.
* Companion PR: https://github.com/couchbaselabs/couchbase-lite-ios-ee/pull/190
> CBL-5209 : Implement Collection and Scope Database Accessor

- Objective-C/CBLReplicator.mm
- Objective-C/Tests/ReplicatorTest+Main.m
- Swift/Tests/ReplicatorTest.swift
Fixed the bug that the Replicator’s ListenerToken was created without the CBLRemovableListenerToken delegate being set.
> CBL-5291 : Fix Replicator ListenerToken.remove()

- CouchbaseLite.xcodeproj/project.pbxproj
- Scripts/remove_private_module.sh
* Private Module contains the internal objective-c headers used in the Swift Code and for EE, it could also need COUCHBASE_ENTERPRISE Macro Variable defined.
* Same as before we remove the privte module and headers. We are doing this in the build phrases.
> CBL-5364 : Remove Private Module

- Objective-C/CBLDatabase.mm
- Objective-C/Internal/CBLDatabase+Swift.h
- Swift/Database.swift
* Detect vector search extension framework with bundle id “com.couchbase.vectorSearchExtension”.
* Set the extension path to the vector search extension bundle’s path.
* Group checkFileLogging and setExtensionPath call together in CBLInit and remove checkFileLogging call from Swift code.
> Detect Vector Search Extension and Set Extension Path

- Objective-C/CBLFullTextIndexConfiguration.h
- Objective-C/CBLValueIndexConfiguration.h
- Swift/IndexConfiguration.swift
* Instead of using class, use struct for all index configuration types.
* Update API doc.
> CBL-5374 : Use struct for all index configuration types

- xcconfigs/Project.xcconfig
We are bumping the iOS Deployment Target to 12.0 for Beryllium.
> Update iOS Deployment Target to 12.0

- CouchbaseLite.xcodeproj/project.pbxproj
- Objective-C/CBLLog.mm
- Resources/PrivacyInfo.xcprivacy
* Added Privacy Manifest File and bundled it into the framework (In Build Phrases, add Copy Bundle Resources Task to copy PrivacyInfo.xcprivacy).
* Made the code that configuring console logging from UserDefaults available only in the Debug build. This means that we don’t need to put the NSUserDefault API usage in the Privacy Manifest file.
> CBL-5343 : Add Privacy Manifest File

- CouchbaseLite.xcodeproj/project.pbxproj
- Objective-C/CBLReplicator.mm
- Objective-C/Internal/CBLReplicator+Internal.h
- Objective-C/Internal/Replicator/CBLReplicator+Backgrounding.h
- Objective-C/Internal/Replicator/CBLReplicator+Backgrounding.m
- Objective-C/Tests/CBLTestCase.m
- Objective-C/Tests/ReplicatorTest+Collection.m
- Objective-C/Tests/ReplicatorTest+Main.m
- Objective-C/Tests/TLSIdentityTest.m
- Objective-C/Tests/URLEndpointListenerTest.h
- Objective-C/Tests/URLEndpointListenerTest.m
- Objective-C/Tests/Util/CBLBlockConflictResolver.h
- Objective-C/Tests/Util/CBLBlockConflictResolver.m
- Swift/Tests/ReplicatorTest+Collection.swift
* Cherry-Picked the fixes from lithium branch (9f194b81f70c626c774a817ac6d7dd2d942e1d02 and 0f33a19784041ca2feab8f17380efe46f7b91734) for CBSE-15077. There were conflicts during the cherry-pick but they are easy to resolve. Below are the commit messages copied from the original fixes.
* The extending background task shouldn’t be ended if there are still pending conflict resolutions.
* When the app was suspended by the background monitor, any current pending conflict resolutions should be canceled. All cancelled conflict resolutions will be notified and put into the queue again when the replicator is resumed or is restarted.
* Fixed bug that the backgrounding monitor may not be restarted after it was ended.
* Renamed some methods and add comments to code.
* Added test to test suspending …
> CBL-5074 : Fix backgrounding logic to cover conflict resolution

- CouchbaseLite.xcodeproj/project.pbxproj
- Objective-C/CBLLog.mm
- Resources/PrivacyInfo.xcprivacy
* Added Privacy Manifest File and bundled it into the framework.
* Made the code that configuring console logging from UserDefaults available only in the Debug build. This means that we don’t need to put the NSUserDefault API usage in the Privacy Manifest file.
> CBL-5383 : Add Privacy Manifest File

- Scripts/Support/Docs/Theme/templates/nav.mustache
* The Jazzy (doc generation tool) doesn’t generate the HTML pages for all sections’ header in the navigation pane. Also the generated section header pages are not useful as they just list all the links shown in the section.
* Updated the template by removing the href link from the section headers on the nagivation pane.
> CBL-5371 : Remove section header nav link from API doc template

- CouchbaseLite.xcodeproj/project.pbxproj
- Objective-C/CBLReplicator.mm
- Objective-C/Internal/CBLReplicator+Internal.h
- Objective-C/Internal/Replicator/CBLReplicator+Backgrounding.h
- Objective-C/Internal/Replicator/CBLReplicator+Backgrounding.m
- Objective-C/Tests/ReplicatorTest+Main.m
- Objective-C/Tests/URLEndpointListenerTest.h
- Objective-C/Tests/URLEndpointListenerTest.m
- Objective-C/Tests/Util/CBLBlockConflictResolver.h
- Objective-C/Tests/Util/CBLBlockConflictResolver.m
* Cherry-Picked the fixes from lithium branch (9f194b81f70c626c774a817ac6d7dd2d942e1d02 and 0f33a19784041ca2feab8f17380efe46f7b91734) for CBSE-15077. There were conflicts during the cherry-pick but they are easy to resolve. Below are the commit messages copied from the original fixes.
* The extending background task shouldn’t be ended if there are still pending conflict resolutions.
* When the app was suspended by the background monitor, any current pending conflict resolutions should be canceled. All cancelled conflict resolutions will be notified and put into the queue again when the replicator is resumed or is restarted.
* Fixed bug that the backgrounding monitor may not be restarted after it was ended.
* Renamed some methods and add comments to code.
* Added test to test suspending …
> CBL-5075 : Fix backgrounding logic to cover conflict resolution

- Objective-C/CBLDatabase.mm
* Cherry-Pick the fix (7daff8e9a5bff94fd6938149451d891e08b7fab1) from lithum branch.
* When signal the database thread to wake up and check for the close, the close condition needs to be locked first to avoid race condition.
> CBL-5399 : Fix close database could hang waiting for active components to close

- Objective-C/Internal/Replicator/CBLWebSocket.mm
* For CBSE-16151
* It is possible that the dispose() function is called by the c4socket before the disconnect() function is called. One of the cases is when c4socket calls the dispose() as the close timeout is reached.
* The fix ensures that when the dispose() is called, the disconnect() function will be called if the connection hasn’t been not closed yet.
* The fix also make sure that the crash doesn’t happen after the c4socket is freed while there are pending tasks in the queue being run at the same time and might access it after it’s freed. This requires to use a lock to prevent this.
* Added message to the assertions.
* Note : Got confirmation from the customer that the VF with this fix doesn't cause the crash issue.
> CBL-5362 : Ensure to disconnect from the remote before CBLWebSocket getting dealloc

- Objective-C/CouchbaseLite.exp
* Removed CBLDatabaseChangeObservable and CBLIndexable symbols from CouchbaseLite.exp as those are protocol.
* This issue was uncovered when building with XCode 15.2 on Jenkins with the error as `framework CoreAudioTypes not found`.
> CBL-5415 : Remove non-symbols from CouchbaseLite.exp

- Objective-C/CouchbaseLite.exp
* Removed CBLDatabaseChangeObservable and CBLIndexable symbols from CouchbaseLite.exp as those are protocol.
* This issue was uncovered when building with XCode 15.2 on Jenkins with the error as framework CoreAudioTypes not found.
> CBL-5414 : Remove non-symbols from CouchbaseLite.exp

- Objective-C/Tests/VectorSearchTest.m
- as per the last spec, the whole obj-c vector index api test suite is now complete
- 16/26 are currently running, the rest being disabled and have their respective ticket at the start of the test (in a comment)
- update TestVectorMatchOnNonExistingIndex off spec to check for consistency with fts
- added 2 more index related tests to confirm behaviour - I think we can leave them here as they don't require the creation of a query such that to be moved under the query tests... and also not so many that we need to have a separate file for now
> CBL-5434: Vector Index API Tests 21-26 [Obj-C]

- Scripts/generate_objc_release_zip.sh
- Scripts/generate_swift_release_zip.sh
* There is a change in the scripts of the Jenkin’s build configuration for building objective-c and swift binary to use the same script to build CE and EE.
* Update the scripts to accomidate the changes. Also this changes have been made in the master branch.
* Note : This shouldn't be merged until 3.1.6 is released or there is a new RC required for 3.1.6.
> CBL-5485 : Update build script per changes in Jenkins's scripts

- CouchbaseLite.xcodeproj/project.pbxproj
- Objective-C/Tests/VectorSearchTest.m
- Swift/Tests/CBLTestCase.swift
- Swift/Tests/DatabaseTest.swift
- Swift/Tests/Util/WordEmbeddingModel.swift
- Swift/Tests/VectorSearchTest.swift
- WordEmbeddingModel impl
- Init method changes in CBLTestCase (same was done for Obj-C) so that we can override and import words_db
- Added the VS extension framework to Swift EE tests (mac and ios) targets
- Fixed Embed&Sign setting
- Fixed building error of test target because it cant find CBLDatabaseConfiguration (obj-c type)... i dont know how this got through pipeline?
- First 10 tests for VS on Swift
> CBL-5435: Implement Tests for Vector Index API 1-10 Swift

- Resources/PrivacyInfo.xcprivacy
Reported in #257 that NSPrivacyAccessedAPITypes and NSPrivacyCollectedDataTypes are required for generating the App’s privacy report even though in the Apple doc, the only required key for 3rd party SDK is NSPrivacyAccessedAPITypes. This commit adds all keys in case the other keys are required in the future by Apple.
> CBL-5524: Add all keys to the Privacy Manifest file

- Resources/PrivacyInfo.xcprivacy
`NSPrivacyAccessedAPITypes` and `NSPrivacyCollectedDataTypes` are required for generating the App’s privacy report. This commit adds all keys in case the other keys are required in the future by Apple.
#3257
> CBL-5527 : Add all keys to the Privacy Manifest file

- Objective-C/Tests/CustomLogger.h
- Objective-C/Tests/CustomLogger.m
- Objective-C/Tests/VectorSearchTest.m
- Swift/Tests/CustomLogger.swift
- Swift/Tests/VectorSearchTest.swift
* Test 5, 6, 10, 11, 12, 13, 14, 16, 17, 18, 20, 22, 23, 24, 25 : Use centroids = 8.
* Test 5, 6, 7, 8, 9, 10, 11, 12, 14, 17, 18, 20, 22, 24, 25 : Verify that the index is trained.
* Test16 : Verify that the index is untrained.
* Test 20 : Add the step to create the query after the index was deleted.
> CBL-5541 : Update vector search test per changes in v1.8

- CouchbaseLite-Swift.podspec
- CouchbaseLite.podspec
- Package.swift
- README.md
As we branched for a new release, have Podspecs updated to target 3.3.0 and Package.swift/README point to the latest public release available
> Podspec and Swift Package updates 

- Scripts/generate_objc_release_zip.sh
- Scripts/generate_swift_release_zip.sh
* Without explicitly set the version, the tool intelligently but unexpectedly picks the version number from the podspec file in the repo. As we generate the API during the build time, this is causing a problem (as happened with 3.2.0-beta.1, the API doc shows version as 3.1.0) when we cannot update the version in the podspec until the release time.
* Explicitly set the version number when generating the doc. If the version is not specified when running the script, there will be no version shown in the doc.
> Set API Doc Version in the generate release zip script

- Scripts/generate_objc_release_zip.sh
- Scripts/generate_swift_release_zip.sh
* Port the change from release/3.2 branch (9b6e07da2872f1049c612b5cb02467f8f1ccc52b)
* Without explicitly set the version, the tool intelligently picks the version number from the podspec file. This may be OK unless we forgot to update the version in the podspec or we cannot update the version until the release time.
* Explicitly set the version number when generating the doc. If the version is not specified, there will be no version shown in the doc.
> Set API Doc Version in generate release zip script

- CouchbaseLite.xcodeproj/project.pbxproj
- Objective-C/Internal/CBLContextManager.h
- Objective-C/Internal/CBLContextManager.m
- Objective-C/Internal/CBLQueryObserver.h
- Objective-C/Internal/CBLQueryObserver.m
- Objective-C/Tests/QueryTest+Main.m
Implemented CBLContextManager class for retaining and mapping the object with its pointer value which can be used as the context for LiteCore's callbacks (e.g. use when creating c4queryobserver objects). The implementation simply stores the object in a map by using its memory address as the key and returns the memory address as the pointer value.
Updated CBLQueryObserver to use CBLContextManager to register its query context and unregister the context when the C4QueryObserver is disabled. The C4QueryObserver's callback now can verified that the query context is still valid before using it. Also when using the query context, the query context is retained in the callback itself.
Updated CBLQueryObserver to get the C4QueryEnumerator object inside the callback as the enumerator object to …
> CBL-5659 : Fix a released query context may be used in observer callback

- Scripts/generate_objc_release_zip.sh
- Scripts/generate_swift_release_zip.sh
CBL-5674 : Fixed missing “then” in elif in generate release zip scripts.
CBL-5675 : Set —module-version when generating API doc.
> Fix error and set API doc version in generate release scripts

- Objective-C/Tests/DocumentTest.m
- Swift/Collection.swift
- Swift/Document.swift
- Swift/MutableDocument.swift
- Swift/Tests/DocumentTest.swift
- change Document.collection API to have a private setter
- set collection on save
- add 1 tests for each side (Obj-C and Swift)
> CBL-5514: Swift MutableDocument's collection is not set when a new document is saved

- CouchbaseLite.xcodeproj/project.pbxproj
- Objective-C/Internal/CBLContextManager.h
- Objective-C/Internal/CBLContextManager.m
- Objective-C/Internal/CBLQueryObserver.h
- Objective-C/Internal/CBLQueryObserver.m
- Objective-C/Tests/QueryTest+Main.m
* Ported the fix directly from release/3.1 branch.
* Implemented CBLContextManager class for retaining and mapping the object with its pointer value which can be used as  the context for LiteCore's callbacks (e.g. use when creating c4queryobserver objects). The implementation simply stores the object in a map by using its memory address as the key and returns the memory address as the pointer value.
* Updated CBLQueryObserver to use CBLContextManager to make sure that the released query context can be detected and not be used. When using the query context, the query context is retained.
* Added a test for CBSE-16662 which is related to this issue and two tests to check that there are no notification received without crash (CBL-5660) after removing the token.
* Added an internal debug …
> CBL-5660 : Fix a released query context may be used in observer callback

- Objective-C/Tests/VectorSearchTest.m
- Swift/Tests/CBLTestCase.swift
- Swift/Tests/DictionaryTest.swift
- Swift/Tests/DocumentTest.swift
- Swift/Tests/QueryTest.swift
- add a couple of tests for some API methods that weren't already tested.
- update LiteCore to fix orphan commit
- update VS ext
This is what I've found to be the fastest way to increase the code coverage. There's a big portion of MessageEndpoint class in Swift that is not tested at all but I have to give it time to understand how that works and how to properly test it as there's some setup from what I could grasp from the Obj-C code lines. 
This should get Swift to 80% or very very close. It takes a good amount of time to generate the whole release zip on local for all platforms so that it generates the code coverage as well. Hence, if needed, I will follow up with another PR after the new API impl as there will be new tests there as well.
> CBL-5668: Get Code Coverage at least 80%

- .github/workflows/xcodebuild-ios.yml
- .github/workflows/xcodebuild-mac.yml
- Jenkinsfile
- Scripts/pull_request_build_test.sh
Due to having a couple of test constantly being flaky in Actions, mostly iOS, but we've seen some in macOS as well, due to the machine being very slow: 
- we will only build via Actions from now on
- we will build and test in Jenkins for both macOS and iOS as EE scheme includes all CE tests alongside EE specific ones
Unfortunately, we cannot run iOS and macOS on parallel as we only have 1 machine for Jenkins. After Beryllium, we will try and get another one so it speeds up the process and run these in parallel.
Caveat: I am not sure if all macOS tests are part of the iOS scheme and until I can confirm this, I prefer to have the test run on both in Jenkins - it will be slower ~30min (and I hope it wont hang as much as LiteCore did in the past from unknown reasons)
> Change PR Validation

- CouchbaseLite.xcodeproj/project.pbxproj
- Objective-C/CBLArray.h
- Objective-C/CBLCollection.h
- Objective-C/CBLCollection.mm
- Objective-C/CBLDictionary.h
- Objective-C/CBLIndexable.h
- Objective-C/CBLQueryIndex.h
- Objective-C/CBLQueryIndex.mm
- Objective-C/Exports/CBL.txt
- Objective-C/Exports/CBL_EE.txt
- Objective-C/Exports/Generated/CBL.exp
- Objective-C/Exports/Generated/CBL_EE.exp
- Objective-C/Tests/CollectionTest.m
- Objective-C/Tests/LazyVectorIndexTest.m
- Objective-C/Tests/VectorSearchTest.h
- Objective-C/Tests/VectorSearchTest.m
- Swift/ArrayObject.swift
- Swift/Collection.swift
- Swift/CouchbaseLiteSwift.private.modulemap
- Swift/DataConverter.swift
- Swift/DictionaryObject.swift
- Swift/Indexable.swift
- Swift/QueryIndex.swift
- Swift/Result.swift
- Swift/Tests/CollectionTest.swift
- Swift/Tests/DocumentTest.swift
- Swift/Tests/LazyVectorIndexTest.swift
- Swift/Tests/VectorSearchTest.swift
* Implemented Lazy Vector Index and Test for Swift.
* Fixed missing symbols.
* Refactored VectorSearchTest in both Swift and Objective-C to reduce duplicate codes.
* Updated some API docs.
* The companion change commit is in the EE repo.
> CBL-5803 : Implement Lazy Vector Index and Test for Swift

- Objective-C/CBLReplicator.mm
- Objective-C/Internal/Replicator/CBLReplicator+Backgrounding.m
* Implemented Replicator log heiroglyphics by using symbols to describe replicator.
* Removed ":" that separates log meesage and the replicator heiroglyphics as it seems to be redundant.
> CBL-5567 : Implement log replicator heiroglyphics

- CouchbaseLite.xcodeproj/project.pbxproj
- Objective-C/CBLDatabase.mm
- Objective-C/CouchbaseLite.h
- Objective-C/Exports/CBL_EE.txt
- Objective-C/Tests/VectorSearchTest.h
- Objective-C/Tests/VectorSearchTest.m
- Swift/Tests/VectorSearchTest.swift
* Implemented Extension.enableVectorSearch in both Objective-C and Swift.
* Moved the logic from CBLDatabase.mm to CBLExtension in ee repo.
* Used LiteCore 61cfa302d61b8baef2c2cfeeb79c24653e1603a0 temporarily to allow the function to be implemented.
> CBL-5859 : Allow explicitly enable vector search

- CouchbaseLite.xcodeproj/project.pbxproj
Made the CBLErrors.h a private header for CBL_Swift and CBL_EE_Swift target.
> CBL-5928 : CBLErrors.h is not included in the umbrella header

- CouchbaseLite.xcodeproj/project.pbxproj
- Objective-C/CBLCollection.h
- Objective-C/CBLCollection.mm
- Objective-C/CBLIndexable.h
- Objective-C/CBLQueryIndex.h
- Objective-C/Tests/DatabaseTest.m
- Objective-C/Tests/DocumentTest.m
- Swift/Collection.swift
* Fixed the circular reference b/w CBLCollection and CBLQueryIndex.
* Fixed warning in tests.
> CBL-5927 : Fix Duplicate CBLQueryIndex Interface Definition

- Objective-C/Tests/VectorLazyIndexTest.m
- Included Test 27 into Test 26: `count()`, `valueAtIndex()`, `setVector()`, `skipVector()` and `finish()` will throw an NSException if the updater is already finished.
- Updated to LiteCore 3.2.0-211
> CBL-5893: Throw exception for everything if finish() was successfully called beforehand

- Objective-C/CBLReplicator.mm
- Objective-C/Tests/ReplicatorTest+Main.m
- Swift/Tests/ReplicatorTest.swift
* Fixed the bug that the Replicator’s ListenerToken was created without the CBLRemovableListenerToken delegate being set.
* Ported the [fix](https://github.com/couchbase/couchbase-lite-ios/commit/b17116c75033b38474b37446a44ee4aa38f94685) from release/3.2 branch.
> CBL-5329 : Fix Replicator ListenerToken.remove() (#3213)

- Objective-C/Internal/CBLQueryObserver.m
* Make sure the query is retained and not nil when using it.
* Port the [fix](https://github.com/couchbase/couchbase-lite-ios/pull/3292/commits/7656730f3f22ded3e02454f37627fbb176eeaa59) from releae/3.2 branch.
> CBL-6023 : Sometimes query becomes nil before is stopped

- Objective-C/Tests/DocumentTest.m
- Swift/Collection.swift
- Swift/Document.swift
- Swift/MutableDocument.swift
- Swift/Tests/DocumentTest.swift
Port the [fix](https://github.com/couchbase/couchbase-lite-ios/commit/87d307b0b8c005a2dc29d52691e0a1cf33c20af1) from release/3.2 branch.
> CBL-6024: Swift MutableDocument's collection is not set when a new document is saved

- Objective-C/CBLMutableDocument.mm
- Objective-C/Internal/CBLLog+Admin.h
Ported from 3.2
* init logging for MutableDocument
* fix typo
> CBL-5222: MutableDocument should be usable before creating a database instance

- Swift/Collection.swift
- Swift/Database+Query.swift
- Swift/From.swift
- Swift/FullTextFunction.swift
- Swift/Function.swift
- Swift/GroupBy.swift
- Swift/Having.swift
- Swift/Index.swift
- Swift/IndexBuilder.swift
- Swift/Indexable.swift
- Swift/Joins.swift
- Swift/MutableDocument.swift
- Swift/OrderBy.swift
- Swift/Query.swift
- Swift/QueryFactory.swift
- Swift/Replicator.swift
- Swift/ReplicatorConfiguration.swift
- Swift/Scope.swift
Ported from 3.2
* fix obj-c ref in swift api
* fix some other mistakes or spacing within Swift API Docs
> CBL-6025: Swift API docs for Scope using Obj-c reference

- Objective-C/CBLDatabase.mm
- Objective-C/CBLDatabaseConfiguration.h
- Objective-C/CBLDatabaseConfiguration.m
- Objective-C/CBLDefaults.h
- Objective-C/CBLDefaults.m
- Objective-C/Exports/CBL.txt
- Objective-C/Exports/Generated/CBL.exp
- Objective-C/Exports/Generated/CBL_EE.exp
- Objective-C/Internal/CBLDatabase+Internal.h
- Objective-C/Tests/DatabaseTest.m
- Swift/DatabaseConfiguration.swift
- Swift/Defaults.swift
- Swift/Tests/DatabaseTest.swift
- Implemented FullSync DatabaseConfiguration property.
- Only Obj-C tests do check for c4db_config2 kC4DB_DiskSyncFull flag
- Updated LiteCore to 3.1.9-5
> CBL-6066: Implement Database Full-Sync Option

- Objective-C/CBLDatabase.mm
- Objective-C/CBLDatabaseConfiguration.h
- Objective-C/CBLDatabaseConfiguration.m
- Objective-C/CBLDefaults.h
- Objective-C/CBLDefaults.m
- Objective-C/Exports/CBL.txt
- Objective-C/Exports/Generated/CBL.exp
- Objective-C/Exports/Generated/CBL_EE.exp
- Objective-C/Internal/CBLDatabase+Internal.h
- Objective-C/Tests/CollectionTest.m
- Objective-C/Tests/DatabaseTest.m
- Swift/DatabaseConfiguration.swift
- Swift/Defaults.swift
- Swift/Tests/DatabaseTest.swift
- cherry picked 5c10248b9ecaf27c08b8f43d7f7f5996d9d54eb7 from `release/3.1` branch. A couple of small, easy-to-resolve conflicts - nothing important
- Implemented FullSync DatabaseConfiguration property.
- Only Obj-C tests do check for c4db_config2 kC4DB_DiskSyncFull flag
- Update to LiteCore 3.2.0-223
> CBL-6070: Implement Database Full-Sync Option

- Objective-C/Tests/ConcurrentTest.m
- port ee8b753424854cf70f0a923f68d54125c058b832 from `release/3.1`
- re-enable 2 additional tests
> CBL-6144: Add testConcurrentCreateAndQuery to verify query's lock

- Objective-C/Tests/CollectionTest.m
- Objective-C/Tests/ConcurrentTest.m
- port https://github.com/couchbase/couchbase-lite-ios/commit/ee8b753424854cf70f0a923f68d54125c058b832 from release/3.1
- re-enable 2 additional tests
> CBL-6147: Add testConcurrentCreateAndQuery to verify query's lock

- Objective-C/Internal/Replicator/CBLHTTPLogic.m
NSURL cannot be created with only host and port anymore starting from iOS 17. Changed to use CFURLCreateWithString directly.
> CBL-6191 : Fix null URL when creating proxy CONNECT request

- Objective-C/Internal/Replicator/CBLHTTPLogic.m
NSURL cannot be created with only host and port anymore starting from iOS 17. Changed to use CFURLCreateWithString directly.
> CBL-6191 : Fix null URL for proxy CONNECT request (#3324)

- Objective-C/CBLArrayIndexConfiguration.m
- Objective-C/CBLIndexConfiguration.m
- nil wasn't correctly captured and it would've been overwriting, causing a crash in getIndexSpecs - caught by Jenkins on release build pipeline
- runtime warning is ONLY shown on CE target... don't know why that's the case
> Fix ArrayIndexConfiguration constructor

- Objective-C/CBLDatabase.mm
- Objective-C/CBLDatabaseConfiguration.h
- Objective-C/CBLDatabaseConfiguration.m
- Objective-C/CBLDefaults.h
- Objective-C/CBLDefaults.m
- Objective-C/Tests/DatabaseTest.m
- Swift/DatabaseConfiguration.swift
- Swift/Defaults.swift
- Swift/Tests/DatabaseTest.swift
Includes:
- LiteCore 3.2.1-9.
- both Obj-C and Swift impl and tests.
- Defaults re-generated to include both fullSync and mmap.
> CBL-6307: Database MMap Configuration API and tests

- Swift/IndexConfiguration.swift
- Swift/Tests/UnnestArrayTest.swift
raised from reviewing docs snippets.. now ArrayIndexConfiguration needs explicit attr name expressions on set
> ArrayIndexConfiguration constructor fix

- Jenkinsfile
- Objective-C/CBLConflictResolver.m
- Objective-C/CBLDatabase.mm
- Objective-C/CBLDocument.h
- Objective-C/CBLDocument.mm
- Objective-C/CBLMutableDocument.mm
- Objective-C/Internal/CBLDocument+Internal.h
- Objective-C/Tests/DatabaseTest.m
- Objective-C/Tests/DocumentTest.m
- Objective-C/Tests/ReplicatorTest+CustomConflict.m
- Objective-C/Tests/ReplicatorTest+Main.m
- Objective-C/Tests/UnnestArrayIndexTest.m
- Objective-C/Tests/VectorSearchTest.m
- Swift/Document.swift
- Swift/Tests/DocumentTest.swift
- Swift/Tests/ReplicatorTest+CustomConflict.swift
- Swift/Tests/UnnestArrayTest.swift
- Swift/Tests/VectorSearchTest.swift
- [CBL-6215](https://jira.issues.couchbase.com/browse/CBL-6215)
- [CBL-6219](https://jira.issues.couchbase.com/browse/CBL-6219)
- [CBL-6223](https://jira.issues.couchbase.com/browse/CBL-6223)
- removed `generation` API which was used for tests
- LiteCore 4.0.0-26
- removed test for -1 and 0 LIMIT boundaries
[CBL-6215]: https://couchbasecloud.atlassian.net/browse/CBL-6215?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[CBL-6219]: https://couchbasecloud.atlassian.net/browse/CBL-6219?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[CBL-6223]: https://couchbasecloud.atlassian.net/browse/CBL-6223?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Enable Version Vectors

- CouchbaseLite.xcodeproj/project.pbxproj
- Objective-C/CBLFullTextIndexConfiguration.h
- Objective-C/CBLFullTextIndexConfiguration.m
- Objective-C/CBLValueIndexConfiguration.h
- Objective-C/CBLValueIndexConfiguration.m
- Objective-C/Tests/PartialIndexTest.m
- Objective-C/Tests/VectorSearchTest.h
- Objective-C/Tests/VectorSearchTest.m
- Swift/IndexConfiguration.swift
- Swift/Tests/PartialIndexTest.swift
- Swift/Tests/VectorSearchTest.swift
- CBL-5193
- CBL-5194
For Swift, `where` is a reserved keyword. So I had to escape it via backticks. There is no impact for the user.
- LiteCore 3.2.2-8
- update testVectorMatchLimitBoundary to expect exception only on more than 10k
> CBL-5193 : Partial Index API

- Objective-C/CBLLog.mm
- Objective-C/Internal/CBLLogSinks+Internal.h
- Objective-C/LogSink/CBLLogSinks.mm
The class initialize method is + initialize instead of + init.
> Fix LogSinks using wrong class initialize method

- CouchbaseLite.xcodeproj/project.pbxproj
- Objective-C/CBLCollection.mm
- Swift/Collection.swift
- Swift/Tests/CustomLogger.swift
- Swift/Tests/PublisherTest.swift
- CBL-6709 Collection Change
- CBL-6710 Document Change
Will add more tests when I have the Test Spec ready. These are just confirm that the listener is actually added and that its token gets removed successfully on completion.
> Collection.publish() Swift Enhancement APIs

- xcconfigs/CBL_ObjC_Tests_iOS_App.xcconfig
Added a required `$(SRCROOT)/vendor/couchbase-lite-core/vendor/fleece/API` to the header search paths of the `CBL_ObjC_Tests_iOS_App` target for the `TunesPerfTest`.
> Fix build error as fleece/PlatformCompat.hh not found

- Objective-C/Tests/URLEndpointListenerTest.m
- Swift/Tests/URLEndpointListenerTest.swift
Disable URLEndpointListener Tests until CBL - 7038 is resolved.
> Disable URLEndpointListener Tests

- CouchbaseLite.xcodeproj/project.pbxproj
- Objective-C/Internal/Replicator/CBLAppBackgroundingMonitor.h
- Objective-C/Internal/Replicator/CBLAppBackgroundingMonitor.m
- Objective-C/Internal/Replicator/CBLConflictResolverService.m
- Objective-C/Tests/MultipeerReplicatorTest.m
* When the app is backgrounding, the multipeer replicator will be auto suspended (stopped) unless . Likewise, when the app is foregrounding, the multipeer replicator will be auto resumed (started) unless the replicator is stopped.
* Implement CBLAppBackgroundingMonitor by extracting the code from CBLReplicator+Backgrounding.m so that the code can be shared between CBLReplicator and MultipeerReplicator in the future but not in 3.3.0 release as updating CBLReplicator code could introduce risk to the release.
* Update LiteCore to the latest to uptake the notification fix.
* Companion PR : https://github.com/couchbaselabs/couchbase-lite-ios-ee/pull/271
> CBL-7030 : Backgrounding support in Multipeer Replicator

- Objective-C/Internal/Replicator/CBLConflictResolverService.h
- Objective-C/Internal/Replicator/CBLConflictResolverService.m
* Allowed resolver to be nil to use default conflict resolver.
* Simplified and fixed circular retain cycle in the dispatch block.
* No conflict resolution tests included as it's currently flaky with some workaround implemented due to CBL - 7099 and CBL - 7100.
* Companion PR : https://github.com/couchbaselabs/couchbase-lite-ios-ee/pull/276
* Note: testSanityReplication is very flaky. I will look into this more once all of the current LiteCore's issues have been resolved.
> CBL-7103 : Fix default conflict resolver not being used in MultipeerReplicator

- CouchbaseLite.xcodeproj/project.pbxproj
- Objective-C/CBLLog.mm
- Objective-C/Internal/CBLLog+Logging.h
- Objective-C/Internal/CBLPrecondition.h
- Objective-C/Internal/CBLPrecondition.m
- Objective-C/Tests/CBLTestCase.h
- Objective-C/Tests/CBLTestCase.m
- Objective-C/Tests/MultipeerReplicatorTest.m
- Objective-C/Tests/TrustCheckTest.m
- Swift/Collection.swift
- Swift/CouchbaseLiteSwift.private.modulemap
- Swift/Precondition.swift
- Swift/Tests/CBLTestCase.swift
- Swift/Tests/MultipeerReplicatorTest.swift
* Added MultipeerReplicator tests (v1.1.0) both objective-c and swift but all tests are disabled now until all of the LiteCore issues have been solved and verified.
* Fixed crash in cblLog when domain is NULL.
* Companion PR : https://github.com/couchbaselabs/couchbase-lite-ios-ee/pull/278
> Add MultipeerReplicator tests and fix bugs

- Objective-C/Tests/DocumentExpirationTest.m
- Objective-C/Tests/MultipeerReplicatorTest.m
- Objective-C/Tests/ReplicatorTest+Main.m
- Objective-C/Tests/ReplicatorTest.m
- Swift/Tests/DocumentExpirationTest.swift
- Swift/Tests/MultipeerReplicatorTest.swift
- Swift/Tests/ReplicatorTest.swift
* Updated testWhetherDatabaseEventTrigged to have higher timeout and remove unnecessary check.
* Increased default replicator test timeout from 10 seconds to 20 seconds.
* Removed testAddRemoveChangeListenerAfterReplicatorStart as it’s flaky, complicated and doesn’t add much value.
* Added a bit of delay in testNeighborPeers as the peer’s online status might not get propagated immediately.
> Fix flaky tests and increase default timeout for replicator tests

- Objective-C/Internal/CBLChangeNotifier.h
- Objective-C/Internal/CBLChangeNotifier.m
* Like the regular replicator, set the progress level to overall by default and bump it to per-doc when there is a document replication listener added.
* Add a method in CBLChangeNotifier to check whether it contains the token or not.
* Companion PR : https://github.com/couchbaselabs/couchbase-lite-ios-ee/pull/283
> CBL-7151 : Adjust progress level in MultipeerReplicator

- Objective-C/Tests/TLSIdentityTest.m
- Swift/Tests/TLSIdentityTest.swift
* The current API for retrieving a TLSIdentity by persistent label throws or returns a NotFound error when the identity does not exist in the keychain. However, this behavior contradicts the API’s signature, which suggests it should return nil if the identity is missing.
* The actual fix is in the EE repo. This commit only updates the tests according to the fix.
* Companion PR : https://github.com/couchbaselabs/couchbase-lite-ios-ee/pull/285
> CBL-7167 : Fix getting non-existing identity throws an error

- Swift/DocumentEncoder.swift
- Swift/FleeceEncoder.swift
- Swift/Tests/CodableTest.swift
Override encodeIfPresent to encode if not present.
> CBL-7179: Swift Codable nil values are skipped from encoding

- Objective-C/Tests/CBLTestCase.h
- Objective-C/Tests/CBLTestCase.m
- Objective-C/Tests/DatabaseTest.m
- Objective-C/Tests/PartialIndexTest.m
- Objective-C/Tests/PredictiveQueryTest.m
- Swift/Tests/CBLTestCase.swift
- Swift/Tests/DatabaseTest.swift
- Swift/Tests/PartialIndexTest.swift
- Swift/Tests/PredictiveQueryTest.swift
* CBL-7196: Predictive Queries test failing when running with CBL 3.3.0
* CBL-7200: LITECORE_VERSION_STRING should be set to 0.0.0 in Project.xcconfig
* CBL-7195: Upgrade SQLite to the latest release, 3.50.3
* Per changes in SQLite's explain plan (since v3.48.0), update USING INDEX assertions to include COVERING INDEX in Query and Predictive tests.
> Update LiteCore to 3.3.0-112

- Objective-C/CBLDatabase.mm
- Objective-C/CBLQuery.mm
- Objective-C/Internal/CBLDatabase+Internal.h
- Objective-C/Internal/CBLQuery+JSON.h
- Objective-C/Tests/DatabaseTest.m
- Objective-C/Tests/QueryTest+Main.m
- Objective-C/Tests/ReplicatorTest+Main.m
- Objective-C/Tests/ReplicatorTest+MessageEndPoint.m
- Objective-C/Tests/TLSIdentityTest.m
- Swift/Database.swift
- Swift/Query.swift
- Swift/Tests/QueryTest.swift
* Updated database APIs to return NotOpen instead of throwing exception :
- (BOOL) inBatch:(NSError**)outError usingBlockWithError:(void (NS_NOESCAPE ^)(NSError**))block
- (BOOL) delete:(NSError**)outError
- (BOOL) performMaintenance:(CBLMaintenanceType)type error:(NSError**)outError (nullable CBLQuery*) createQuery:(NSString*)query error:(NSError**)error
* Refactor / Clean up :
- Used CBLPrecondition in CBLDatabase.
- Reset closing state when closing database fails.
- Ensured to lock when calling to free c4db to avoid crash.
- Renamed CBLQuery’s JSONRepresentation property to just json.
- Fixed warnings from static analysis in TLSIdentityTest and ReplicatorTest.
* Related PR : https://github.com/couchbaselabs/couchbase-lite-ios-ee/pull/302
> CBL-7348 : Update Database APIs to return NotOpen error for closed database cases

- Objective-C/CBLLog.mm
- Objective-C/Internal/CBLLog+Logging.h
- Objective-C/LogSink/CBLConsoleLogSink.mm
- Objective-C/LogSink/CBLFileLogSink.mm
- Objective-C/LogSink/CBLLogSinks.mm
- Objective-C/LogSink/CBLLogTypes.h
- Swift/ConsoleLogger.swift
- Swift/Log.swift
- Swift/LogSinks.swift
- Swift/Logger.swift
- Swift/Tests/LogSinkTest.swift
- Swift/Tests/MultipeerReplicatorTest.swift
* Added mdns logging domain to both objective-c and swift.
* Reserved 128 and 256 value for bluetooth and wifi-aware that we may have in the future for multipeer replicator.
* Changed Swift LogDomain type from UInt8 to UInt for enum values > 256 (Need a release note for this)
* Fixed missing switch cases in CBLFileLogSink.mm.
* Skip testConfigurationValidation as precondition cannot be asserted. We use Swift’s precondition() for parameter validation in Precondition.swift. Since it traps like fatalError, it cannot be asserted in tests, so the test is left disabled for manual runs.
* Will need to be ported to 4.0 after this is merged.
* Note: Adding a logging domain needs to touch multiple places and is easily to be missed - we should think about improving this.
> CBL-7394 : Add mdns logging domain

- Objective-C/CBLCollectionConfiguration.h
- Objective-C/Internal/Replicator/CBLCollectionConfiguration+Internal.h
- Objective-C/Tests/ReplicatorTest+Collection.m
- Swift/CollectionConfiguration.swift
- Swift/Tests/ReplicatorTest+Collection.swift
- moved `[CBLCollectionConfig fromCollections: config:]` to internal
- removed the Swift equivalent because CollectionConfiguration is struct and the block cannot modify the config. I have not yet found a good solution without adding a Mutable option, which I don't really like.
- LiteCore 4.0.0-85
> Update LiteCore submodule
