Source/API/Extras/CBLIncrementalStore.m

* Fixed NSIncrementalStore not firing fault when adding a new document from sync. The solution (calling willAccessValueForKey: method with nil value on an NSManagedObject) to ensure that fault is firing was suggested by https://github.com/couchbase/couchbase-lite-ios/pull/383 posted by @Rostmen. The solution is inline with what Apple suggests in the willAccessValueForKey: API doc.
* Fixed crash when deleting an nsmanaged object.
#576

Fix fault has not been fired when adding a new doc from sync

---

Source/CBL_Puller.m

If a permanent error occurrs during bulk downloading, the completion block will get called twice, one from the error itself and the other one from cancelling the request when setting the error (strongSelf.error == error).
To prevent the above to happen, move the removeRequest to the top of the block so that the request will not get cancelled.
#613

Fix CBLPuller crash (#613)

---

Source/API/Extras/CBLIncrementalStore.h
Source/API/Extras/CBLIncrementalStore.m

Fixed cblis coding style to have only one coding style and inline with the other source codes the project.

Fix cblis coding style

---

Source/API/Extras/CBLIncrementalStore.m

* Change type key from 'CBLIS_Type' to 'type'. For an existing app, will continue to use CBLIS_type. There is no custom type key at this moment.
* Store metadata property in a local doc instead of a normal document.
* Clean up error generation code and some very long length code.
#591

CBLIS Change type key from CBLIS_Type to type

---

Source/API/Extras/CBLIncrementalStore.m
Unit-Tests/IncrementalStore_Tests.m

Add support for NSFetchRequest.includesSubentities property. If the includesSubentities value is YES (default value is YES) so the fetch result should includes its child entity object. On the other hand, if the includesSubentities is set to NO, the fetch result shouldn't includes its child entity objects.
#605

Add CBLIS support for NSFetchRequest.includesSubentities

---

Source/API/CBLReplication.m

- Ensure to remove the progress change notification in the replication thread before forgetting the CBLReplication self object.
- Remove previous crash fix that added retainSelf in the bg_updateProgress method.
#624

Fix crash due to notification race condition in CBLReplication

---

Source/API/Extras/CBLIncrementalStore.m
Unit-Tests/IncrementalStore_Tests.m

* With the current approach of using inverse relationship view for storing to-many relationship, we are not supporting ordered many relationship. This commit prints warning messages when detecting that the core data model uses ordered many relationship.
* Removed non-used codes. 
#637

Add ordered relationship warning message to CBLIS

---

Source/API/CBLManager.m

- Refactored the -upgradeOldDatabaseFiles method by extracting out the upgrade logic into the -upgradeDatabaseNamed method.
- In -replaceDatabaseNamed, call -upgradeDatabaseNamed method when replacing a sqlite database to ensure that the old version db get upgraded.
#678

Fix -replaceDatabaseNamed method to upgrade the old version db

---

Source/API/CBLManager.m

According to http://www.sqlite.org/wal.html, WAL database cannot be used when the database is opened in the READONLY mode. When getting the schema version, open the database in READWRITE mode instead.
#687

Open db in READWRITE mode when querying the schema version

---

Source/API/Extras/CBLIncrementalStore.m
Unit-Tests/IncrementalStore_Tests.m

Not templating comparison predicate with nil value.
#745

Fix CBLIS query with nil value

---

Unit-Tests/IncrementalStore_Tests.m

Predicate with nil relationships filter crash.

Added tests for nil relationships (NSPredicate)

---

Unit-Tests/IncrementalStore_Tests.m

Sort descriptors with keyPath as key returns empty result.

add failing test for sort descriptiors with keyPaths

---

Source/CBLMultipartUploader.m

Create a new writer after closing stream.
#752

Fix CBLMultipartUploader connection:needNewBodyStream

---

Source/API/Extras/CBLIncrementalStore.m

use rangeOfString instead of containsString ios8 only method

CBLIS use a ios7 compatible method

---

Source/API/CBLManager.h
Source/CBLManager+Internal.h

Move CBLManager.storageType property to public

---

Unit-Tests/P2P_Tests.m

- The connectionCount value is updated asynchronously on a background thread so it's possible after the replicator finishes running, the connectionCount value is set to 0 before the expectation is created.
- The keyValueObservingExpectationForObject:'s expectation will be fullfilled only when the observed value is changed.
- Moved connectionCount check to its parent runReplication:expectedChangesCount: method and created the expectation before running the replication.

Fix P2P Blip Tests connectionCount race condition

---

Source/API/Extras/CBLIncrementalStore.h
Source/API/Extras/CBLIncrementalStore.m
Unit-Tests/IncrementalStore_Tests.m

Implemented CBLIncrementalStoreDelegate.storeWillSaveDocument that will allow an application to add additional properties to the CBL documents before they are saved into the database.

CBIS CBLIncrementalStoreDelegate.storeWillSaveDocument

---

Source/API/Extras/CBLIncrementalStore.m

CBLIS refresh objects with to-one relationships

---

CouchbaseLite.xcodeproj/project.pbxproj
Source/API/CBLManager.m
Source/CBLDatabase+Internal.m
Source/CBLForestBridge.h
Source/CBLForestBridge.mm
Source/CBLRestReplicator+Backgrounding.m
Source/CBLRestReplicator.h
Source/CBLRestReplicator.m
Source/CBL_ForestDBStorage.mm
Source/CBL_ForestDBViewStorage.mm
Unit-Tests/DatabaseEncryption_Tests.m
Unit-Tests/DatabaseInternal_Tests.m
Unit-Tests/ViewInternal_Tests.m

This enables auto-compaction for ForestDB databases, and switches to the new ForestDB encryption API (as opposed to the one I implemented outside ForestDB as a plug-in.)
Please see the commit notes for the individual commits. It's probably best to review the two commits separately, as they do different things. (They're dependent on each other, which is why I'm submitting them as one PR.)
Fixes #922

ForestDB auto-compact and better encryption (#922)

---

Unit-Tests/DatabaseEncryption_Tests.m

Fixes #957 by altering unit test

Fixes #957

---

Source/API/CBLManager.h
Source/API/CBLManager.m
Source/CBLDatabase+Internal.m
Unit-Tests/CBLTestCase.m
Unit-Tests/Database_Tests.m

Added constant strings, kCBLSQLiteStorage and kCBLForestDBStorage.

Add constant strings for "SQLite" and "ForestDB" storage type

---

Source/API/Extras/CBLIncrementalStore.m

In multiple context env, such as parent (root, private) and child (main) context, each context operates on its own context. In most case, CBLIS operates on the root context's dispatch queue. However it's possible that the main context attached to the UI could access CBLIS directly for newValuesForObjectWithID and newValueForRelationship.
This commit make sure that any CBL operations on those 2 methods are executed on the root context or database dispatch queue.
#958

Fixed #958 Handle accessing CBLIS from multiple dispatch queues

---

Source/API/Extras/CBLIncrementalStore.m

- Not using view prefix for relationship views.
- Call view's -updateIndex and check lastSequenceIndexed if the view index was changed or not. If not changed, return the cached result if it's available.
#960

Fixed #960 CBLIS: Optimize relationship query cache

---

Source/API/Extras/CBLIncrementalStore.h
Source/API/Extras/CBLIncrementalStore.m
Unit-Tests/IncrementalStore_Tests.m

Added -(BOOL) purgeObject: (NSManagedObject*)object error: (NSError**)outError method.
#879

CBLIS: Add purge object API

---

Source/CBLDatabaseUpgrade.m

noAtts column index is 6 no 4.
#1025

Fixed #1025 : selecting wrong noAtts column index in CBLDatabaseUpgrade

---

CouchbaseLite.xcodeproj/project.pbxproj

Add CBLRegisterJSViewCompiler in the Extras folder

---

Source/API/CouchbaseLite.h

Remove CBLRegisterJSViewCompiler.h from CouchbaseLite.h

---

Source/API/Extras/CBLIncrementalStore.h
Source/API/Extras/CBLIncrementalStore.m
Unit-Tests/IncrementalStore_Tests.m

These include all CBLIS fixes from the master branch since 10/19/2015.

Cherry pick CBLIS fixes from master branch

---

Listener/CBLHTTPResponse.m

When read-only, the listener disallows POST requests by default except to specific paths. This commit adds `/*/_changes` to those exceptions.
I've switched to comparing selectors directly rather than as NSStrings, because it's cheaper. But it does require pre-declaring the corresponding methods, so the compiler knows those selectors are valid.
Fixes #1106

Read-only listener should allow POST to _changes

---

Listener/CBLHTTPConnection.m

Sets the `source` property of the CLBChangeListener when a revision gets added by a remote peer using the listener (most likely pushing to me.)
The old code only set the URL if the connection had an authenticated username, and the URL was just `user:username`. I've changed it into an HTTP URL that includes the IP address of the connection.
Fixes #1100

Set CBLDatabaseChange.source for changes made by peer via listener

---

Source/CBL_ForestDBViewStorage.mm
Source/CBL_SQLiteViewStorage.m
Unit-Tests/ViewInternal_Tests.m

Also added a warning when user-provided keys/values can't be converted
to JSON.
Fixes #1120

Warn (but don't crash/throw) if map fn calls emit(nil

---

Source/API/Extras/CBLIncrementalStore.h
Source/API/Extras/CBLIncrementalStore.m
Unit-Tests/IncrementalStore_Tests.m

- CBLIS now creates its own dispatch queue and set to its CBLManager instance.
- CBLManager set to CBLIS requires to have a dispatch queue set.
- All CBL database operations are redirected to the dispatch queue.
#1129 , #1085 , #1075

Fix CBLIS accessed by multiple dispatch queue issue

---

Source/API/CBLQuery.m
Source/API/CBLView.h
Source/API/CBLView.m
Source/API/Extras/CBLIncrementalStore.m
Source/CBLView+Internal.h
Source/CBL_Router+Handlers.m
Unit-Tests/ViewInternal_Tests.m
Unit-Tests/View_Tests.m

There was already a private `-updateIndex` method, but it returns a CBLStatus, so I renamed that one `_updateIndex`.
Fixes #1148

Added public CBLView methods -updateIndex and -updateIndexAsync:.

---

Source/ChangeTracker/CBLChangeTracker.m

CouchDB also supports POST to _changes, but expects most of the parameters
to still be in the URL, not the request body.
Fixes #1139

Fixed incompatibility with CouchDB's _changes feed

---

Source/CBLRestReplicator+Backgrounding.m

Fixed a race condition in replicator foreground/background transitions

---

CouchbaseLite.xcodeproj/project.pbxproj
Source/API/CBLManager.m
Source/API/CBLRemoteLogging.h
Source/API/CBLRemoteLogging.m
Source/API/CBLTimeSeries.h
Source/API/CBLTimeSeries.m
Source/CBLRestPusher.h
Source/CBLRestPusher.m
Source/CBL_Replicator.h
Source/CBL_ReplicatorSettings.h
Source/CouchbaseLite.exp
Test-Mac/DemoAppController.h
Test-Mac/DemoAppController.m
Test-Mac/DemoQuery.m
Test-Mac/ShoppingDemo.xib
Unit-Tests/Replication_Tests.m
Unit-Tests/TimeSeries_Tests.m

* Implemented CBLTimeSeries and CBLRemoteLogging
* Implemented two new push replicator options, "purgePushed" and "allNew"
* Added remote-logging support to the Mac test app
It's probably best to review the three commits one by one since they each do different things.
Fixes #881

Time-series and remote logging

---

Source/ChangeTracker/CBLWebSocketChangeTracker.m

I still don't know why the first error occurs. But after that, the
ChangeTracker wouldn't be able to recover, because it would reconnect
but keep using the same GZip decoder, which wouldn't be in an initial
state. So it would keep getting gzip errors every time. I fixed this
by nil-ing out _gzip in the -start method.
I also improved the flow of control so, after it gets an error and
decides to close the WebSocket, it will ignore subsequent queued
messages to avoid getting confused by them and logging more errors.
For #1074

Partially fixed CBLWebSocketChangeTracker unzip errors

---

Source/CBLRestPusher.m

If a call to _bulk_docs returns an error for one of the docs (other
than 401 or 403) we propagated that error to the replicator's error
property, which stops the replication. Unfortunately there have been
situations (due to bugs in either CBL or SG) where a specific document
always triggers a 400 error. This doc would then always abort the
replication, preventing any newer revisions from being pushed
Instead, we now just keep going. The affected revision still isn't
removed from the "pending" list, so the checkpoint won't advance past it
and we'll attempt to push it again the next time.
Fixes #1279

Don't stop replicator if a bulk-uploaded doc gets an error

---

BuildScripts/InstallFatLibrary.sh
CouchbaseLite.xcodeproj/project.pbxproj

Implemented the same fix in 1.2.1 (331e529f9a8644f68cb8b7a91c542dd85b3e1cd5).
#1316

Fix archive binaries of CBLForestDBStorage.a and CBLJSViewCompiler.a

---

Unit-Tests/Replication_Tests.m

This includes the fix for #1316 that libCBLForestDBStorage.a doesn't work with the simulator.

Merge dev into master

---

Source/CBL_SQLiteStorage.m

The system SQLite on 10.12 reports that it has the SQLITE_HAS_CODEC
compile option; however, 'PRAGMA key' does not work.
To work around this, also call `PRAGMA cipher_default_kdf_iter',
which is SQLCipher-specific. If that doesn't return a value, we know
we're not talking to SQLCipher.
Fixes #1406

Work around macOS 10.12 problem with SQLCipher detection

---

Source/CBLRestReplicator+Backgrounding.m

Make strong self to the weakSelf in the blocks to retain the self.
#1498

Fix #1498 crash onAppBackgrounding

---

Source/CBL_ForestDBStorage.mm
Source/CBL_SQLiteStorage.m

* Ported the fix from https://github.com/couchbase/couchbase-lite-net/pull/790.
#1440

Fix #1440 attachment revpos after delete and recreate doc

---

Source/CBL_ForestDBStorage.mm

* when a doc is deleted and recreated, inPrevRevID will be nil so the previous code to fix the attachment revpos doesn’t get executed.
* Simplify the code.
#1568 #1440

Fix #1568 forestdb att revpos when doc is deleted and recreated

---

CouchbaseLite.podspec
Objective-C/CouchbaseLite.h

Create a podspec that builds the binary from source. Need to change the umbrella header file to include with flat structure.

Add CouchbaseLite.podspec

---

Source/CBL_SQLiteStorage.m
Unit-Tests/Router_Tests.m

* From the REST API, when getting a purged doc, the result returns with deleted as a result. It should be returnning as missing. The issue happens on on SQLite but no ForestDB.
* Fixed CBL_SQLiteStorage’s getDocumentWithID to correctly differentiate between deleted and not-found.
#1580

Fixed #1580 get purged doc returning wrong reason

---

CouchbaseLite.xcodeproj/project.pbxproj
Swift/Database.swift
Swift/Document.swift
Swift/Properties.swift
Swift/Subdocument.swift
Swift/Tests/DocumentTest.swift
Swift/Tests/SubdocumentTest.swift

* Cached both Swift Document and Subdocument inside CBLDocument and CBLSubdocument respectively.
* Implement Swift Subdocument by wrapping the CBLSubdocument.
#1624

Fixed #1624: Implement Swift Subdocument

---

Objective-C/CBLDatabase.h
Objective-C/CBLQuery.h
Objective-C/CBLQuery.m
Objective-C/CBLQueryDataSource.h
Objective-C/CBLQueryExpression.h
Objective-C/CBLQueryExpression.m
Objective-C/CBLQueryOrderBy.h
Objective-C/CBLQueryOrderBy.m
Objective-C/CBLQueryRow.h
Objective-C/CBLQuerySelect.h
Objective-C/Internal/CBLQuery+Internal.h
Objective-C/Tests/QueryTest.m
Swift/Expression.swift
Swift/From.swift
Swift/Query.swift
Swift/Tests/QueryTest.swift
Swift/Where.swift

* Fixed #1688, wrong expression validation
* Fixed selectDistinct method name typos.
* Improved documentation

Misc fixes to ObjC and Swift Query API

---

CONTRIBUTING.md

Add link to [Couchbase Code of Conduct](https://www.couchbase.com/code-of-conduct).

Update CONTRIBUTING.md w/ code of conduct

---

CouchbaseLite.xcodeproj/project.pbxproj
Objective-C/CBLArray.m
Objective-C/CBLDocument.h
Objective-C/CBLDocument.mm
Objective-C/Tests/ConflictTest.m
Objective-C/Tests/DocumentTest.m
Objective-C/Tests/MiscTest.m

* Moved ConflictTest into its own file.
* Updated DocumentTest
* Fixed bugs in CBLArray

Reorganize test and update DocumentTest

---

Objective-C/CBLDatabase.mm
Objective-C/Internal/CBLInternal.h
Objective-C/Tests/DatabaseTest.m

Test plan for DatabaseTest: https://github.com/couchbaselabs/couchbase-lite-apiv2/wiki/DatabaseTest

Fixed #1732 - Rewrote DatabaseTest.m

---

CouchbaseLite.xcodeproj/project.pbxproj
Objective-C/CBLArray.m
Objective-C/Tests/ArrayTest.m
Objective-C/Tests/DocumentTest.m
Objective-C/Tests/SubdocumentTest.m

* Added Array Unit Tests
* Cleaned up DocumentTest and SubdocumentTest

Add Array Unit Tests

---

Source/CBL_SQLiteStorage.m
Source/CBL_SQLiteViewStorage.m

I’ve also added explicit JOIN syntax in a few places, since it’s said
to give the optimizer more insight into the meaning of the query.
I also removed several unnecessary indexes, where SQLite already
indexes the column in question to implement a UNIQUE constraint. This
was recommended by SQLite gurus to avoid confusing the optimizer.
Fixes #1737 
NOTE: If you're not familiar with it, the unary "+" operator in SQLite tells the query optimizer to avoid using an index on the referenced column. It's otherwise a no-op.

Prevent bad optimization of SQLite queries for view indexing & changes

---

Objective-C/CBLArray.m
Objective-C/Tests/ArrayTest.m

* Copied data from fleece when needed
* Bring array code closer to dictionary code

Optimize array by lazy copy data from fleece

---

Objective-C/CBLDocument.mm

c4doc_update() is faster because it uses the existing C4Document
instead of reading it from the database. It fails if the document has
been updated on disk, but that's what we want here anyway.

Use the new c4doc_update() function, to save documents more efficiently

---

docs/examples/objc-api-walkthrough/Cartfile
docs/examples/objc-api-walkthrough/Cartfile.resolved
docs/examples/objc-api-walkthrough/objc-api-walkthrough/ViewController.m

@pasin updated Carthage to DB13. Didn't need any code change to compile with DB13. Replication is working with 1.5 477. Added a replication change listener snippet.
Could you review and merge?

DB13 Objc example proj

---

Objective-C/CBLQueryFunction.h
Objective-C/CBLQueryFunction.m
Objective-C/Internal/CBLQuery+Internal.h
Objective-C/Tests/QueryTest.m
Swift/Function.swift
Swift/Tests/QueryTest.swift

Implemented Array, Math, String, and Type functions to ObjC and Swift.
#1842

Add array, math, string, and type functions

---

docs/examples/objc-api-walkthrough/Cartfile
docs/examples/objc-api-walkthrough/Cartfile.resolved
docs/examples/objc-api-walkthrough/objc-api-walkthrough/ViewController.m
docs/examples/swift-api-walkthrough/Cartfile
docs/examples/swift-api-walkthrough/Cartfile.resolved
docs/examples/swift-api-walkthrough/README.md
docs/examples/swift-api-walkthrough/api-walkthrough.xcodeproj/project.pbxproj
docs/examples/swift-api-walkthrough/api-walkthrough/ViewController.swift
docs/examples/swift-api-walkthrough/install-canned-db.sh

db14 examples

---

CouchbaseLite.xcodeproj/project.pbxproj
Objective-C/CBLDatabase.h
Objective-C/CBLDatabase.mm
Objective-C/CBLIndex.h
Objective-C/CBLIndex.mm
Objective-C/CBLQueryCollation.h
Objective-C/CouchbaseLite.exp
Objective-C/CouchbaseLite.h
Objective-C/Internal/CBLFTSIndex.h
Objective-C/Internal/CBLFTSIndex.m
Objective-C/Internal/CBLIndex+Internal.h
Objective-C/Internal/CBLValueIndex.h
Objective-C/Internal/CBLValueIndex.m
Objective-C/Tests/DatabaseTest.m
Objective-C/Tests/PredicateQueryTest.m
Objective-C/Tests/QueryTest.m
Swift/Database+Query.swift
Swift/Index.swift
Swift/Tests/DatabaseTest.swift
Swift/Tests/PredicateQueryTest.swift
Swift/Tests/QueryTest.swift

* Implemented a new index API for both value and full-text search index.
* Disabled testCreateSameNameIndexes as the test is failed due to two different type indexes are allowed to create with the same name.
#1666

Implement a new index API

---

Source/CBLRestReplicator+Backgrounding.m

* Currently some variables (_active, _filesystemUnavailable, and _deepBackground) could be accessed from different threads (main thread and replicator thread). Fixing this by always executes background/forground handling codes on the replicator thread.
* This is also fixed the issue that the replicator (especially pull replicator) is suspended immediately when starting it in the background. Basically there is a race when accessing the _active variable (#1898)

Fixed #1898 threading issue in replicator backgrounding

---

Source/CBLAttachmentDownloader.m
Source/CBL_BlobStoreWriter.m

Submitting a pull request, as requested by @pasin

Fix assert failure with attachment download failure on retry #1853

---

Source/API/CBLDocument.m
Source/CBLDatabase+Attachments.h
Source/CBLDatabase+Attachments.m
Source/CBLDatabase+Insertion.h
Source/CBLDatabase+Insertion.m
Source/CBLDatabaseUpgrade.m
Source/CBLRestPuller.m
Source/CBL_Router+Handlers.m
Unit-Tests/DatabaseAttachment_Tests.m
Unit-Tests/DatabaseInternal_Tests.m
Unit-Tests/Replication_Tests.m
Unit-Tests/ViewInternal_Tests.m

New pull request rebased on master to replace #1635

Fix issue with deferred download of attachments #1354

---

Source/ChangeTracker/CBLSocketChangeTracker.m

* There could be a lot of data available in the stream especially when pulling a lot of documents from the local server. When reading the data from the stream, also check if it needs to pause or not.
* The different from previous fixes (16c975e27c70f3d95200e8627736e4ec0e872b59 and f4c13176916e6c279e0ade50ea5168071f90933d) are that the _readyToRead needs to be set to false first in readFromInput and the end stream case needs to be handle.
#1707

Fixed #1707 high mem usage when pulling a log of docs

---

Source/API/CBLManager.m
Unit-Tests/DatabaseInternal_Tests.m

Users could set the dir that also contains non database files such as temp or app group directory. So when changing the file protections, we should skip non database files.
#1622

Fixed #1622: changing file protection level should skip non database dirs or files

---

Objective-C/CBLReplicator.mm
Objective-C/Internal/CBLLiveQuery.mm

Fix for https://github.com/couchbase/couchbase-lite-ios/issues/2005

Fix for #2005. Make CBLDB Query/replicator access thread safe

---

Objective-C/Tests/QueryTest.m
Swift/Tests/QueryTest.swift

Fix for #2047 . Ported the tests from .Net to ObjC and Swift.

Ported cross join and left join tests from .Net

---

Objective-C/CBLReplicator.mm
Objective-C/Tests/ReplicatorTest.m

* Made the replicator thread-safe by using lock.
* Fix the stop status not getting reported when calling replicator.stop() after the replicator is in the offline state.
#1981

Fixed #1981 Make replicator thread-safe and fix stop after offline

---

Objective-C/Internal/Replicator/CBLWebSocket.mm

- Ensured to close read/write socket when an error occurs; the stream task might no close the socket when an error such as operation timed out (60) occurs.
- Increased the default read/write timeout to the value (320 seconds) which is greater than the default heartbeat of 300 seconds.
#2078

Fix socket leaks and increase idle timeout (#2078)

---

Objective-C/Internal/Replicator/CBLWebSocket.mm

- The crash happened when canceling the task after read/write socket was closed.
- In -checkError:, also ignore the ENOTCONN error if there was a request socket close.
- In -readHTTPResponse, also call checkError: the same way as in -receive and -writeAndFree:. This is not directly related to the crash but make the error check going the same path.
#2085

Fix #2085 crash when canceling NSURLSession task

---

docs/modules/ROOT/pages/objc.adoc
docs/modules/ROOT/pages/swift.adoc

[docs] remove mention of official tvOS support

---

Swift/Expression.swift

I couldn't find anywhere else to document that. It's quite a low level detail to go into the general docs. May need confirmation from Jens on type coercion if you are not sure about what I wrote.
Taken from https://issues.couchbase.com/browse/DOC-3218

[docs] .and() clause

---

Objective-C/Tests/SampleCodeTest.m
Swift/Tests/SampleCodeTest.swift
docs/antora.yml
docs/modules/ROOT/pages/objc.adoc
docs/modules/ROOT/pages/swift.adoc

[docs] 2.1 updates

---

Objective-C/Internal/Replicator/CBLWebSocket.mm

CFNetwork in iOS 11 has a bug where multiple pending writes to an NSURLSessionStreamTask
can be written in the wrong order (but only if going through an HTTP proxy...!)
To work around this, we're ensuring that we only have one outstanding write at a time,
as suggested by Apple’s Quinn.

Fix CBLWebSocket proxy bug using Apple workaround

---

Objective-C/CBLQuery.h
Objective-C/CBLQuery.mm
Objective-C/CBLQuerySelectResult.m
Objective-C/Internal/CBLQuery+Internal.h
Objective-C/Tests/QueryTest.m
Swift/Query.swift
Swift/Tests/QueryTest.swift

Reverts couchbase/couchbase-lite-ios#2219

Revert "Allow creating Query from JSON, and getting JSON [API CHANGE]"

---

Objective-C/CBLQueryMeta.h
Objective-C/CBLQueryMeta.m
Objective-C/Tests/QueryTest.m

* add similar methods like sequence for isDeleted
* add 3 test cases for empty, single-delete, and multi-delete document.
#2232

Feat: Meta.isDeleted implement

---

Objective-C/Tests/QueryTest.m
Swift/Tests/QueryTest.swift

* placeholder change not reflected in the test cases
* quick fix

fix: Build Error Fix

---

Objective-C/CBLDatabase.mm

* Convert from sec to msec when setting expiration date
* Convert from msec to sec when getting expiration date

Fixed #2270 : Convert from sec to msec and vice versa

---

Objective-C/Tests/DocumentExpirationTest.m
Swift/Tests/DocumentExpirationTest.swift

* add query after expiration including deleted docs.
* add immediate delete by setting now() test case.
links: #2267

Add more tests

---

Objective-C/Tests/DocumentExpirationTest.m
Swift/Tests/DocumentExpirationTest.swift

* checking whether the change.database instead of the self.db

fix: jenkins failure

---

Objective-C/CBLDatabase.mm

* Need to check whether database (_c4db) is still opened before purging the expired doc in the background.
* Add error log when purging is failed.

Check database opened before purge expired docs in background

---

CouchbaseLite.xcodeproj/project.pbxproj
Swift/Tests/DateTimeQueryFunctionTest.swift

* add test case for date time function in Swift
* include basic test cases

Add test case for DateTimeFunction - Swift

---

Objective-C/Tests/ReplicatorTest.m

* add two unit tests for replication eventing.
* expiration with push and pull.
link: #2264

Add Test for Replication Eventing - ObjC

---

Swift/Tests/ReplicatorTest.swift

* adds the replication eventing expiry test. 
link: #2264

Add Test for Replication Eventing - Swift

---

Objective-C/CBLFileLogger.mm

* set the header key with user agent
fix: #2309

feat: set header as user agent in the file options

---

Swift/Tests/LogTest.swift

* check default location
* check default log format
* check plain text format
link: #2302

test: add continuous logging unit tests for swift

---

Objective-C/Tests/LogTest.m
Swift/Tests/LogTest.swift

* check for filename format for ObjC and Swift
link: #2302

test: check filename format 

---

CouchbaseLite.xcodeproj/project.pbxproj
Objective-C/CBLFileLogger.h
Objective-C/CBLFileLogger.mm
Objective-C/CBLLogFileConfiguration.h
Objective-C/CBLLogFileConfiguration.m
Objective-C/CouchbaseLite-EE.exp
Objective-C/CouchbaseLite.exp
Objective-C/CouchbaseLite.h
Objective-C/Internal/CBLLogFileConfiguration+Internal.h
Objective-C/Tests/LogTest.m
Swift/CouchbaseLiteSwift-EE.modulemap
Swift/CouchbaseLiteSwift.modulemap
Swift/FileLogger.swift
Swift/LogFileConfiguration.swift
Swift/Tests/LogTest.swift

- Implemented a new file logger API a refactor log file related settings into a single configuration file, LogFileConfiguration.
- Updated unit tests.
#2321

Implement a new file logger API

---

Objective-C/Tests/ReplicatorTest.m
Swift/Tests/ReplicatorTest.swift

* check the removed doc with the replication filter
* add tests for both swift and objc
* disabled all tests. 
link: #2303

test: check replication filter with removed doc

---

Objective-C/Tests/ReplicatorTest.m
Swift/Tests/ReplicatorTest.swift

* add test cases for checking the deleted docs in the push filter,.
* add for swift and objc
link: #2303

test: check replication filter with deleted docs

---

Objective-C/Tests/LogTest.m
Swift/Tests/LogTest.swift

* check maxRotateCount, disable file logging, enable and disable file logging
* maxSize & maxRotateCount not working as expected.
* check header snippet include `CouchbaseLite/`,`Commit/` and `Build/`
link: #2302

test: logging tests add

---

Objective-C/Tests/ReplicatorTest.m
Swift/Tests/ReplicatorTest.swift

* progress completeed issue is fixed and hence enabled the tests.
* enabled for both swift and objc
link: #2303

fix: deleted doc progress issue

---

Objective-C/Tests/ReplicatorTest.m
Swift/Tests/ReplicatorTest.swift

* check stop and restart scenario
* add tests in swift and objc
* since the continuous pull is showing error, disabled those tests.
link: #2303

test: check stop and restart the replication with filter

---

Objective-C/Tests/ReplicatorTest.m
Swift/Tests/ReplicatorTest.swift

* swift test case was using un-edited document instance, corrected it.
* enabled test in swift
* removed push test case for removed document.
fix: #2303

fix: removed doc test

---

Objective-C/Tests/LogTest.m
Swift/Tests/LogTest.swift

* check non-ascii character set in the logs.
* add tests for swift and objc
* checking with a Hebrew sentence
fix: #2323

test: check non-ASCII character set

---

.travis.yml

fix: travis yml file add

---

.travis.yml

* Added master to the safe-list branch in .travis.yml.
* Note: I have enabled build push branch in `https://travis-ci.org/couchbase/couchbase-lite-ios`.

Update .travis.yml to build only master branch

---

.travis.yml

* made the ObjC and Swift as parallel process
* added xcpretty

ci: adds the xcpretty

---

Swift/ConsoleLogger.swift
Swift/Tests/LogTest.swift

Instead of using Set\<LogDomain\>, changed to use OptionSet.

Change to use OptionSet type for ConsoleLogger.domains

---

Objective-C/CBLDatabase.mm

* added the null check for parameters.
link: #2353

feat: add non-null check for parameters

---

Objective-C/CBLDictionary.mm

fix: assert non-nullable param check for DictionaryClass

---

Objective-C/CBLDocumentFragment.m

link: [2353](https://github.com/couchbase/couchbase-lite-ios/issues/2353)

fix: assert the parameter non-null check

---

Objective-C/CBLQueryResult.mm

fix: assert param for non-null

---

.slather.yml
CouchbaseLite.xcodeproj/project.pbxproj
Objective-C/Tests/AuthenticatorTest.m

* avoid unit tests files, which was improving the test results by 10-15%
* add more tests for Authenticator.
ref:  #2376

unit: update slather script

---

Objective-C/Tests/QueryTest.m

* increase code coverage for the CBLQueryBuilder from 25% to 37.50%
* total impact is 0.45%

unit: improve coverage for QueryBuilder

---

Objective-C/Tests/QueryTest.m

* add join where tests
* add distinct join tests
Ref: #2376

unit: add more query builder tests

---

Objective-C/Tests/QueryTest.m

* add tests for selectFromWhere(GroupBy, OrderBy, GroupByHaving)
* respective Distinct Methods also added in unit tests.  
* total improvement = 0.59%; CBLQueryBuilder = 37.50% to 54.17%. 
Ref: #2376

unit: improve query builder code coverage 

---

Objective-C/Tests/QueryTest.m

* add test for select(distinct) from join where groupby having.
* select from join where groupby having orderby limiyt
* select from join where orderby
Ref: #2376

unit: query builder join tests

---

Objective-C/Tests/ReplicatorTest.m

* verify the add document listener returns a non null reference to token.
Ref: #2376

unit: check replicator listener

---

Objective-C/Tests/ReplicatorTest.m

* creation of CBLDocumentReplicator and CBLReplicatedDocument.
Ref: #2376

unit: check creation of document replicator

---

Objective-C/CBLMutableDocument.mm
Objective-C/Tests/DictionaryTest.m
Objective-C/Tests/DocumentTest.m

* add tests for CBLMutableDictionary
* add tests for type setter methods for CBLMutableDocument. 
* corrected the pragma. 
Ref: #2376

unit: dict and doc type setter methods

---

Objective-C/Tests/FragmentTest.m

* add fragment test cases
Ref: #2376

unit: fragment missing test cases

---

CouchbaseLite.xcodeproj/project.pbxproj
Swift/Tests/QueryTest.swift
xcconfigs/Project.xcconfig

I ran the Xcode migration tool to convert this project to Swift 5.0. Only one real line of code change was needed.

Convert to Swift 5.0

---

Objective-C/Tests/QueryTest.m

* add coverage for query result array
Ref: #2376

unit: query result array add coverage

---

Objective-C/Tests/QueryTest.m

* check the JSON conversion with different types of input.
* validate if there is any invalid type is passed in.
Ref: #2376

unit: validate value expression

---

Objective-C/CBLQueryParameters.mm
Objective-C/Tests/QueryTest.m

* fix issue with the Date in QueryParameter. 
* wrote a loadStudents method for validating different types.
* remaining are dictionary, blob and array which will be added as separate function
Ref: #2376

unit: query params set method

---

Objective-C/Tests/QueryTest.m

* add checking for query result for array, dictionary, 
* subscripted with index and key, 
* check for query result keys.
Ref: #2376

unit: check query result 

---

Objective-C/Tests/MiscTest.m

* check for dataWithJSONObject and stringForJSONObject
Ref: #2376

unit: check the method with init tests

---

Objective-C/Tests/LogTest.m

* made the max-rotate-count to 2 and validated with 2KB of logs.
Ref: #2376

unit: check the maxRotateCount

---

Objective-C/Tests/ReplicatorTest.m

* add replicator config setter methods verification.
* helper method kept in helper section.
Ref: #2376

unit: replicator config setter methods

---

Objective-C/Tests/QueryTest.m

* add pragma marks, group the related functions
* will separate the class into multiple classes if needed, after discussing.
Ref: #2376

refact: code cleanup

---

Objective-C/CBLDatabase.mm

* removed the unwanted check, which always succeed.

fix: unsigned integer value always greater than or equal to zero

---

README.md

* update version for all samples, documentation etc to 2.5

doc: update readme 2.5

---

Objective-C/Tests/QueryTest.m

* add check for number, integer, longLong, boolean, date, and float

unit: add check for remaining query result

---

Objective-C/Tests/ReplicatorTest.m
Swift/Tests/ReplicatorTest.swift

* enable logging since the replicator is showing some intermittent issue
ref: #2420

 debug: replicator intermittent issue

---

Objective-C/Tests/QueryTest.m

* validated the result when checking for not null or not missing with  function.
Ref: #2376

unit: add unary missing checks

---

Objective-C/CBLDatabase.h
Objective-C/CBLDatabase.mm

* add method to save with conflict handler.
Ref: #2429

feat: database save conflict handler implementation in ObjC

---

README.md

* update the 2.5.0 information 
merge this if you feel okay.

doc: update readme for master 

---

Objective-C/CBLReplicatorConfiguration.m

Fix for heartbeat, checkpoint intervals not getting set

---

Objective-C/Internal/Replicator/CBLWebSocket.mm

LiteCore is handling WebSocket timeouts now. It will time out:
* if connection doesn’t open in 15 sec
* if no PONG response to PING received in 10 sec
* if no response received to CLOSE in 5 sec
The last of these should fix the problem of replicators not closing when told to stop.
Note: The fixes are in LiteCore; the CBL code change is to _remove_ the existing timeout code in CBLWebSocket, since it's now redundant.

Improved replicator timeouts

---

Swift/DictionaryObject.swift
Swift/Fragment.swift

feat: expose dictionary

---

Objective-C/CBLDatabase.mm

* on save handler false - return conflict error
* it was not added in objc. 
ref: #2429

fix: on save handler false - return conflict error

---

Objective-C/CBLDatabase.h
Objective-C/CBLDatabase.mm

* pass nullptr with c4doc_docExpiry() api
* update sub-module

fix: get doc expiry cause an error

---

Objective-C/CBLDatabase.mm

* while reading the latest document from the db. no need for transaction since c4doc_get doesn't require it.

fix: no transaction required

---

Objective-C/Tests/ReplicatorTest+CustomConflict.m

* revision-id for the remote wins should always be same.
* sequence should always be remote greater than local doc.

unit: verify the sequence-id to check whether to push resolved 

---

CouchbaseLite.xcodeproj/project.pbxproj
Swift/Tests/ReplicatorTest+CustomConflict.swift
Swift/Tests/ReplicatorTest.swift

- copy paste custom conflict tests and helper class from `ReplicatorTest` to `ReplicatorTest+CustomConflict`
- separated Replicator class into ReplicatorTest_Main(all tests) and ReplicatorTest(all helper methods)

refact: replicator test

---

Objective-C/Tests/ReplicatorTest+CustomConflict.m

* check for generation, revID and deleted scenarios with default resolution.
Ref: #2428

unit: default resolution check

---

Objective-C/Tests/DatabaseTest.m

* check if return true and when some updates are done.
ref: #2430

unit: test conflict resolver

---

Objective-C/Tests/DatabaseTest.m

* keeping the new doc when old doc is deleted.
* keeping the old deleted doc, and ignoring the new changes.
ref:  #2430

unit: deleted old doc

---

Objective-C/Tests/ReplicatorTest+CustomConflict.m

* check when blob is added to local and remote, but resolved remote and local.
* check when resolved local or remote with blob.
* check when resolved with newly created doc with blob.

unit: blob test

---

Objective-C/CBLReplicator.mm
Objective-C/Internal/CBLReplicator+Internal.h
Objective-C/Tests/ReplicatorTest+CustomConflict.m

* changed the replicator to use an independent serial queue instead of the database queue.
* added test to verify the database operations are not blocked due to this serial queue.
* reverted the replicator to use separate queue

fix: replicator queue add

---

Objective-C/Tests/ReplicatorTest+CustomConflict.m

fix: remove invalid test

---

Swift/Tests/ReplicatorTest+CustomConflict.swift

* check whats the behavior when resolver returns the doc with and without blob.
* since the doc.toDictionary() comparison is not working, we did validated the contents via key-values.
ref: #2428

unit: check resolver returning blob

---

Swift/Tests/ReplicatorTest+CustomConflict.swift

* make sure, conflict resolution is not blocking any db opertions.
* for swift
#2428

CBL-73: unit: non blocking db operation

---

Swift/Tests/DatabaseTest.swift

* save handler when document is already purged, should return NotFound error, since the file already purged.
#2430

CBL-72: unit: when document purges - save handler - swift

---

Swift/Tests/DatabaseTest.swift

* check the deleted old doc test in swift
* check for keeping deleted and non-deleted doc.
#2430

CBL-72: unit: check save handler with deleted old doc

---

Swift/Tests/DatabaseTest.swift

* check scenario with save handler called twice.
#2430

CBL-72: unit: save handler twice

---

Objective-C/CBLDatabase.h
Objective-C/CBLDatabase.mm
Swift/Database.swift
Swift/Tests/DatabaseTest.swift

* when exception thrown in save handler, it should show a warning log. and fail the save.
* add warning message.
#2430

CBL-72: unit: throws an exception in save-handler

---

Objective-C/CBLReplicator.mm

Removed suspending cancel state and change the logic to use _cancelSuspending variable to signal resuming after suspended.

Remove suspending cancel state

---

Objective-C/Tests/ReplicatorTest+CustomConflict.m
Swift/Tests/ReplicatorTest+CustomConflict.swift

* removed this test previously, since we updated the logic to incorporate this. so adding it back.
* add swift and objc

CBL-73: unit: non blocking conflicts

---

Objective-C/Tests/ReplicatorTest+CustomConflict.m

* check which one saves the doc
* check second one is throwing a warning with no conflict.

unit: double conflict

---

Objective-C/CBLDatabase.mm

* update error message with more clear

CBL-73: fix: error message update

---

Objective-C/Tests/ReplicatorTest+CustomConflict.m

* check purge during conflict resolver returns NotFound error

CBL-73: unit: purge during conflict resolution

---

Swift/Tests/ReplicatorTest+CustomConflict.swift

* check behavior of purge doc during resolver
* needs a CBLErrorNotFound

CBL-73: unit: purge when resolver - swift

---

Objective-C/CBLDatabase.mm
Objective-C/CBLDocumentReplication.mm
Objective-C/CBLReplicator.mm
Objective-C/Internal/Replicator/CBLDocumentReplication+Internal.h
Objective-C/Tests/ReplicatorTest+CustomConflict.m
Objective-C/Tests/ReplicatorTest+Main.m

* only one log per conflict skipping.

fix: only one warning about skip resolution

---

Swift/ArrayObject.swift
Swift/Fragment.swift
Swift/MutableArrayObject.swift
Swift/MutableDictionaryObject.swift
Swift/MutableFragment.swift

fix: expose protocols

---

Objective-C/CBLConflictResolver.m
Objective-C/CBLDatabase.mm
Objective-C/CBLDocument.h
Objective-C/CBLDocument.mm
Objective-C/Internal/CBLDocument+Internal.h
Objective-C/Tests/DatabaseTest.m
Objective-C/Tests/DocumentTest.m
Swift/Document.swift
Swift/Tests/DocumentTest.swift

CBL-148: feat: revision id add to document

---

Objective-C/CBLDatabase.mm
Objective-C/CBLReplicator.mm

* previous retry was not cancelled, in case retry already scheduled.
* used the CBLTimer to schedule it.
* CBL-138
* #2525

CBL-138: fix: retry logic

---

Swift/Tests/QueryTest.swift

* add unit test to fail the FTS issue.

CBL-369: unit: FTS and alias issue with db.db.rowid

---

Scripts/generate_release_zip.sh
xcconfigs/Project.xcconfig

* version to 2.6.1 
* fix the simulator name.

bump version

---

Swift/Tests/QueryTest.swift

* include all types in the parameters

CBL-373: test parameter all types 

---

CouchbaseLite.xcodeproj/project.pbxproj
Swift/Tests/ArrayTest.swift
Swift/Tests/QueryTest.swift
Swift/Tests/ReplicatorTest+CustomConflict.swift

* array object set and add method verification tests added
* conflict resolver default
* CBL-373

CBL-373: fix: swift coverage

---

Jenkinsfile
Scripts/pull_request_build.sh

pr-validation

---

Objective-C/CBLReplicator.h
Objective-C/CBLReplicator.mm

* is-document-pending implementation added.
* unit test,will be added, once this #2564 is merged.

CBL-449: IsDocumentPending ObjC

---

CouchbaseLite.xcodeproj/project.pbxproj
Objective-C/CBLReplicator.h
Objective-C/CBLReplicator.mm
Objective-C/Tests/ReplicatorTest+PendingDocIds.m

* add implementation for getting the Pending Document ID in ObjC
* add one unit test

CBL-449: Pending Document ID ObjC

---

Objective-C/CBLReplicator.h
Objective-C/CBLReplicator.mm
Swift/Replicator.swift

* swift implementation - pending document ids
* add attribute for marking nonnull error to throw in objc function declaration.

CBL-449: swift implementation - pending document ids

---

Objective-C/Internal/Replicator/CBLWebSocket.mm

* when setting CFsetproperty method crashed, but input stream property set is working fine.

fix: core foundation SSL Settings crashed with Charles proxy

---

Objective-C/CBLBlob.mm

Reverts couchbase/couchbase-lite-ios#2586

Revert "CBL-518: CBL-519: blob"

---

Objective-C/Internal/Replicator/CBLWebSocket.mm

* trust check was done before the proxy write data to socket
* cbl-535

fix: trust check in proxy connection

---

Objective-C/CBLReplicator.mm

* Only retry if there is any network issues
* previously we were setting observer in case of all errors.

CBL-556: Only retry if there is any network issues 

---

Objective-C/CBLDatabase.mm

CBL-582: Fix: FLDoc memory fix

---

Scripts/Support/License/LICENSE_enterprise.txt

* updated the license from `LA v5: 03262019` to `LA v7: 12Nov2019`

CBL-534: update enterprise license(mercury branch)

---

Scripts/Support/License/LICENSE_enterprise.txt

* updated the license from `LA v5: 03262019` to `LA v7: 12Nov2019`

CBL-534: update enterprise license(master)

---

Objective-C/CBLDatabase.mm
Objective-C/CBLDocument.mm
Objective-C/Internal/CBLC4Document.h
Objective-C/Internal/CBLC4Document.mm
Objective-C/Tests/ReplicatorTest+CustomConflict.m

* fixed the issue with attachment flag not carrying over
* corrected the revisionFlag property, inside isDeleted and selectConflictingRevision methods.

CBL-624: fix: flags not carrying over(master branch)

---

CouchbaseLite.xcodeproj/project.pbxproj
Objective-C/CBLReplicator.h
Objective-C/CBLReplicator.mm
Objective-C/Tests/ReplicatorTest+PendingDocIds.m

* include pending document ids API
* include unit tests

CBL-703: Pending Document Ids

---

Objective-C/Internal/CBLReplicator+Internal.h
Objective-C/Tests/ReplicatorTest+Main.m

* remove platform defined close code

Fix: CBL-704 platform side

---

Objective-C/Tests/ReplicatorTest+PendingDocIds.m

* include tests to validate continuous replicator. for idle, offline states

CBL-711: test: offline, idle tests for pending document id API

---

CouchbaseLite.xcodeproj/project.pbxproj
Objective-C/Tests/CBLTestCase.h
Objective-C/Tests/CBLTestCase.m
Objective-C/Tests/ReplicatorTest+CustomConflict.m
Objective-C/Tests/ReplicatorTest+Main.m
Objective-C/Tests/ReplicatorTest+PendingDocIds.m
Objective-C/Tests/ReplicatorTest.h
Objective-C/Tests/ReplicatorTest.m
Swift/Tests/CBLTestCase.swift
Swift/Tests/MessageEndpointTest.swift
Swift/Tests/ReplicatorTest+CustomConflict.swift
Swift/Tests/ReplicatorTest+PendingDocIds.swift
Swift/Tests/ReplicatorTest.swift

* Moved otherDB to the base test class. The otherDB needs to explicitly open.
* Fixed missing header search path to fleece API.

Move otherDB to the base test class

---

Objective-C/Tests/ReplicatorTest+Main.m

* testSwitchBackgroundForeground, is done with expectations, which will wait for app to go to background and then comes to foreground. this will not check the immediate switching to foreground.
ref: CBL-729

CBL-729: Switch to foreground immedeiately after going to background

---

Objective-C/Tests/TLSIdentityTest.m
Swift/Tests/CBLTestCase.swift
Swift/Tests/TLSIdentityTest.swift

* Updated TLSIdentityTest for latest API changes
* Cleaned up some debugging code in tests
CBL-959

CBL-959: Update TLSIdentityTest for latest API changes

---

CouchbaseLite.xcodeproj/project.pbxproj
Objective-C/Tests/URLEndpointListenerTest.m

* Added a unit test for ListenerPasswordAuthenticator
* Refactored URLEndpointListenerTest class
CBL-818

CBL-818: Add unit test for CBLListenerPasswordAuthenticator

---

CouchbaseLite.xcodeproj/project.pbxproj

Add URLEndpointListener class for swift

CBL-914: Add URLEndpointListener class for swift

---

Objective-C/Internal/Replicator/CBLWebSocket.mm

fix: build error for EE-only lite core function call

fix: build error for ee only lite core function call

---

Objective-C/Internal/CBLErrorMessage.h
Objective-C/Internal/CBLErrorMessage.m

related: https://github.com/couchbaselabs/couchbase-mobile-tools/pull/26

CBL-962: updated common error message

---

Objective-C/Tests/URLEndpointListenerTest.m

* include a test with basic network interface
* since the IPV6 addresses are not accessible disabled
* also due to addresses with scheme http not wss , stops it from enabling

network interface unit test

---

Objective-C/CBLReplicatorConfiguration.h
Objective-C/CBLReplicatorConfiguration.m
Objective-C/Internal/Replicator/CBLTrustCheck.h
Objective-C/Internal/Replicator/CBLTrustCheck.m
Objective-C/Internal/Replicator/CBLWebSocket.mm
Objective-C/Tests/ReplicatorTest.h
Objective-C/Tests/ReplicatorTest.m
Objective-C/Tests/URLEndpointListenerTest.m
Swift/ReplicatorConfiguration.swift
Swift/Tests/ReplicatorTest.swift
Swift/Tests/URLEndpointListenerTest.swift

* Implement ServerCertificateVerificationMode
* Updated TLS setup and trust logic in CBLWebSocket and CBLTrustCheck
* Added tests
CBL-822

Implement Replicator's ServerCertificateVerificationMode

---

Objective-C/CBLReplicator.mm
Objective-C/Tests/ReplicatorTest+Main.m

* Restored Reachability fix
* Prevented race condition between retry and stop due to reachability report in testStopReplicatorAfterOffline_SG.
CBL-983

Fix testStopReplicatorAfterOffline_SG intermittently fails

---

Objective-C/Tests/URLEndpointListenerTest.m

* when replicating from multiple replicators to same database.
* two listener on same database

CBL-957: multiple replicators/listeners test

---

CouchbaseLite.xcodeproj/project.pbxproj
Objective-C/Internal/Cert/CBLCert.h
Objective-C/Internal/Cert/CBLCert.mm
Objective-C/Internal/Cert/CBLKeyChain.h
Objective-C/Internal/Cert/CBLKeyChain.mm
Objective-C/Internal/Replicator/CBLTrustCheck.mm

* Used c4cert_isSelfSigned() to check if the certificate is self-signed.
* Moved CBLCert and CBLKeyChain from EE to CE.
* Adjusted API_AVAILABLE in CBLCert as appropriate.
CBL-1027

Fixed checking self-signed cert in CBLTrustCheck

---

xcconfigs/Project.xcconfig

Linked LiteCore PR:  https://github.com/couchbase/couchbase-lite-core/pull/965

CBL-1007: Support 32-bit arch

---

Objective-C/Tests/PredictiveQueryTest.m

Used the right assertion. Not sure how it was passed before.

Fix testEuclidientDistance failure

---

Objective-C/Tests/URLEndpointListenerTest.m

* listener and replicator on same db.
* continuous replicator till data is finished replicating.

CBL-957: Listener and Replicator on same database

---

Objective-C/CBLDatabase.mm
Objective-C/Internal/CBLDatabase+Internal.h
Objective-C/Tests/URLEndpointListenerTest.m

* database close should stop the listener; feature implemented
* include a unit test validate same

database close should stop active listener

---

Objective-C/CBLDatabase.h
Objective-C/CBLDatabase.mm
Objective-C/Tests/ConcurrentTest.m
Objective-C/Tests/DatabaseTest.m
Swift/Database.swift
Swift/Tests/DatabaseTest.swift

* Implemented Database’s performMaintenance(type:)
* Deprecate compact method.
CBL-991

Implement Database’s performMaintenance(type:)

---

Objective-C/Tests/URLEndpointListenerTest.m
Swift/Tests/CBLTestCase.swift
Swift/Tests/URLEndpointListenerTest.swift

* port basic tests
* urls, connection status
* fix: objc test for urls

tests: listener port, urls, status

---

Swift/Tests/URLEndpointListenerTest.swift

unit tests are copied from objc
* testMultipleListenersOnSameDatabase
* testReplicatorAndListenerOnSameDatabase
* testCloseWithActiveListener

tests: unit tests copied from objc

---

Swift/Tests/URLEndpointListenerTest.swift

* readonly listener
* empty network interface
* multiple replicators to a listener

CBL-957: final unit tests copied from objc

---

Objective-C/Tests/URLEndpointListenerTest.m
Swift/Tests/URLEndpointListenerTest.swift

* skip link local, and validate the remaining addresses
* update lite core, so that the ipv6 changes are taken

enable empty network interface

---

Objective-C/Tests/URLEndpointListenerTest.m

validate invalid interface name

CBL-1018: invalid interface name

---

Objective-C/Tests/CBLTestCase.h
Objective-C/Tests/CBLTestCase.m
Objective-C/Tests/ReplicatorTest+Main.m
Objective-C/Tests/ReplicatorTest.m

* available from XCode 11.4; so it is compatible with latest XCode

Use XCTSkip: Cleaner code

---

.slather.yml
.travis.yml
CouchbaseLite.xcodeproj/project.pbxproj
Jenkinsfile
Scripts/pull_request_build.sh

* fix Jenkins PR validation
* also fix couple of travisCI failures. But not CBL Swift([CBL-1109](https://issues.couchbase.com/browse/CBL-1109)) is failing on travis, which needs to be taken care separately. 
* remove some dead file reference from project.

CBL-935: Fix Jenkins PR Validation

---

xcconfigs/Project_Release.xcconfig

* enable this to remove all absolute path from binary & dsym
* CBL-1106

cherry-pick: no-serialize-debugging-option swift (#2693)

---

Objective-C/CBLLog.mm
Objective-C/CBLLogger.h
Swift/Logger.swift

CBL-1120: Make listener logs EE only

---

Objective-C/Tests/URLEndpointListenerTest.m
Scripts/generate_release_zip.sh
Swift/Tests/URLEndpointListenerTest.swift

* validate and coverage data works fine locally
* disable tests which are causing trouble

enable coverage data collection

---

Objective-C/Tests/URLEndpointListenerTest.m

* use importIdentity method to create a TLSIdentity and use it  to start a listener
* verify by replicating a doc
Reference: https://github.com/couchbase/couchbase-lite-ios/pull/2721

test: add listener test with import identity

---

Objective-C/CBLReplicator.h
Swift/Replicator.swift

Add a note indicating that the listenres need to be added before starting the replicator.
CBL-1233

Update add document listener api doc

---

Objective-C/CBLDatabase.h
Swift/Database.swift

Update documentation for close and delete database

CBL-1249: Update documentation for close and delete database

---

Objective-C/Tests/URLEndpointListenerTest.m
Swift/Tests/URLEndpointListenerTest.swift

test: update the unit test to skip local network

---

Objective-C/Tests/MessageEndpointTest.m
Swift/Tests/MessageEndpointTest.swift

add delay for stop sending message before the server connection opens

test: delay before sending message 

---

Scripts/build_xcframework.sh
Scripts/generate_release_zip.sh

* include dsym with the xcframework for debugging
* remove the objc xcframework zip creation.
* update usage section 
* probably need to merge to hydrogen (probably after Xcode 12 GA)

dSYM with XCFramework

---

Objective-C/Tests/URLEndpointListenerTest.m
Swift/Tests/URLEndpointListenerTest.swift

* include tests to validate the close and delete of the database associated with the listener as well as replicator. 
* test with (1)replicator + multiple listeners and (2) multiple replicators + listener

CBL-1297: Include the missing unit tests

---

CouchbaseLite.xcodeproj/project.pbxproj
Scripts/generate_package_manifest.sh
Scripts/generate_release_zip.sh

* Update build script to generate package.swift with checksum in the output directory
* CBL-1313: Fix the issue when creating xcframework alone, it was tring to generate objc, swift documentation which end up failing.

Update build script 

---

Swift/Tests/URLEndpointListenerTest.swift

* add null listener test
* refactor to reuse tlsIdentity and cleanupIdentity method
* rename the test > testNonTLSPasswordListenerAuthenticator
porting objc > https://github.com/couchbase/couchbase-lite-ios/pull/2752

test: add null authenticator test

---

Objective-C/Tests/URLEndpointListenerTest.m

* restructure TLSIdentity unit test
* include negative test (pinned cert) with different cert and no cert.

test: tls unit test updated

---

Objective-C/Tests/URLEndpointListenerTest.m

*add tls-password-auth-listener test

test: add tls-password-auth-listener test

---

Package.swift

- package manifest for hydrogen branch (2.8.0)

spm: add package manifest 2.8.0 CE

---

Swift/ReplicatorConfiguration.swift

* accidentaly included the property in ReplicatorConfiguration

CBL-1362: remove unused/unwanted property

---

Scripts/generate_release_zip.sh

* ObjC XCFramework include in Release Script 
* Fix the issue with script, when running xcframework alone. (more aligned with master https://github.com/couchbase/couchbase-lite-ios/pull/2751)
* Tested the XCFramework on Todo ObjC App(Sim).

ObjC XCFramework include in Release Script 

---

CouchbaseLite.xcodeproj/xcshareddata/xcschemes/CBL_ObjC.xcscheme
CouchbaseLite.xcodeproj/xcshareddata/xcschemes/CBL_Swift.xcscheme

Disable code coverage for CBL_ObjC & CBL_Swift scheme

---

Objective-C/Tests/URLEndpointListenerTest.m
Swift/Tests/URLEndpointListenerTest.swift

* race with active connection count was fixed with pull filter

test-fix: race condition

---

Swift/Tests/URLEndpointListenerTest.swift

Skip keychain access if not iOS App target

test-fix: skip keychain access if not iOS App target

---

Scripts/generate_package_manifest.sh
Scripts/generate_release_zip.sh

* Cherry-pick: #2765 #2768
* Update package.swift filename, and create it for both objc and swift xcframework

Cherry-Pick from Hydrogen

---

Swift/Tests/URLEndpointListenerTest.swift

Copy objc tests
https://github.com/couchbase/couchbase-lite-ios/commit/c24b1610432e6e15a1dcf67ff8d75e32fd806114
https://github.com/couchbase/couchbase-lite-ios/commit/de4f50c93929c1715a724f9089e47327fd174bb3

test: add missing unit tests

---

Objective-C/Internal/Replicator/CBLTrustCheck.mm

CBL-1477: only accept self signed(acceptSelfSignedOnly option) > 2.8.x 

---

Objective-C/Tests/QueryTest+Main.m
Swift/Tests/QueryTest.swift

* validate the division function precision

CBL-1426: test: validate the division function precision

---

Objective-C/Internal/CBLLiveQuery.mm

* update status : live query update status is collected to make it as a update status variable.
* state : query state is defined by observing, stopping and stopped.
* Fixes part 2 : CBL-795

Cleanup: LiveQuery: state variables instead of booleans

---

README.md

CBL-990: Update README.md

---

Objective-C/Internal/Replicator/CBLTrustCheck.mm
Scripts/build_xcframework.sh
xcconfigs/Project.xcconfig

* fix the deprecation warnings with catalyst
* make sdkroot=iphoneos

make catalyst compatible

---

Scripts/build_xcframework.sh
xcconfigs/Project.xcconfig

related: 
https://github.com/couchbase/couchbase-lite-core/pull/1109
https://github.com/couchbaselabs/fleece/pull/84

include catalyst support flag and enable catalyst with xcframework build

---

Objective-C/Tests/TLSIdentityTest.m

* updated function: SecCertificateCopyPublicKey > SecCertificateCopyKey

fix: Catalyst unavailable function

---

Scripts/generate_release_zip.sh

* x86_64 + macosx
* x86_64 + catalyst
* arm64 + macosx (when ran on arm64 machine, it will test for the arm64 destination. )
* arm64 + catalyst (same ^)
* swift + objc combination for above

CBL-1610: 

---

Objective-C/CBLReplicatorConfiguration.h
Objective-C/CBLReplicatorConfiguration.m
Objective-C/Internal/CBLReplicator+Internal.h
Objective-C/Tests/ReplicatorTest+Main.m

* implement the heartbeat settable and use default 300 secs .
* add unit tests to validate the default secs and invalid values

feat: customizable heartbeat interval (hydrogen branch)

---

Swift/ReplicatorConfiguration.swift
Swift/Tests/CBLTestHelper.h
Swift/Tests/CBLTestHelper.m
Swift/Tests/ReplicatorTest.swift

* implementation and unit test to validate the exception

heartbeat for swift

---

Objective-C/Tests/ReplicatorTest+Main.m
Swift/Tests/ReplicatorTest.swift

* check when setting a custom heartbeat value
* CBL-1601

test: custom heartbeat

---

Objective-C/CBLReplicatorConfiguration.h
Objective-C/CBLReplicatorConfiguration.m
Objective-C/Tests/ReplicatorTest+Main.m
Objective-C/Tests/URLEndpointListenerTest.m
Swift/Tests/URLEndpointListenerTest.swift

* add property for retry count and retry wait time
* set the lite core replicator option

feat: retry count & wait time objc

---

Swift/ReplicatorConfiguration.swift
Swift/Tests/ReplicatorTest.swift

* implement the swift retry logic and add unit tests associated with it.

feat: retry swift

---

Objective-C/Tests/ReplicatorTest+Main.m

test: retry objc

---

.github/workflows/xcodebuild.yml

test PRs and push to master on CBL-ObjC and CBL-Swift scheme tests

GH Actions: Xcode build for ObjC and Swift tests

---

Objective-C/CBLBlob.h
Objective-C/CBLBlob.mm
Objective-C/Tests/DocumentTest.m

* implement the function to return the json string
* add test to check the inconsistency exception and document save, then toJSON

feat: toJSON results from blob

---

Objective-C/CBLDictionary.h
Objective-C/Internal/CBLNewDictionary.mm
Swift/ArrayObject.swift
Swift/Blob.swift
Swift/Database.swift
Swift/DictionaryObject.swift
Swift/Document.swift
Swift/MutableArrayObject.swift
Swift/MutableDictionaryObject.swift
Swift/MutableDocument.swift
Swift/Result.swift

* add toJSON functions to Document, Dictionary, Blob, Array classes
* add save, get Blob function to Database class

feat: Swift API for JSON Support toJSON

---

Swift/MutableArrayObject.swift
Swift/MutableDictionaryObject.swift
Swift/MutableDocument.swift

* add initializer and setJSON functions for the swift classes.

feat: Swift API for JSON Support setJSON

---

Jenkinsfile

Clean up simulator, DerivedData, and tmp files.
-Ming Ho

CBL-1717, clean up unwanted data potentially left behind by older builds

---

Objective-C/CBLBlob.mm
Objective-C/Tests/DocumentTest.m

remove @type from blob getProperties()

remove @type from blob properties

---

Objective-C/Tests/MessageEndpointTest.m

* make sure the connection opened before replicator is started

test: fix the intermittent issue with connection

---

Swift/Database.swift
Swift/DatabaseConfiguration.swift
Swift/Replicator.swift
Swift/ReplicatorConfiguration.swift
Swift/Tests/CBLTestCase.swift
Swift/Tests/DatabaseEncryptionTest.swift
Swift/Tests/DatabaseTest.swift
Swift/Tests/MessageEndpointTest.swift
Swift/Tests/ReplicatorTest+CustomConflict.swift
Swift/Tests/ReplicatorTest+PendingDocIds.swift
Swift/Tests/ReplicatorTest.swift
Swift/Tests/URLEndpointListenerTest.swift

* change the DBConfig and ReplicatorConfig to struct
* remove the readOnly flag
* add couple of tests to validate the update
* tests chnges  to make config a 'var', so we can update the properties.

feat: enhanced config API

---

Objective-C/Tests/ReplicatorTest+Main.m

* validate the add/remove listener after the replicator starts
* CBL-1599

objc test: validate the add/remove listener after the replicator start

---

Objective-C/Internal/Replicator/CBLWebSocket.mm

* this should ideally add new cookies with semi-colons.
* https://developer.apple.com/documentation/foundation/nsmutableurlrequest/1408793-setvalue

fix: cookie being appended with comma

---

Objective-C/Tests/URLEndpointListenerTest.m
Swift/Tests/URLEndpointListenerTest.swift

* remove the test, since the client auth with root certs are already covered in testClientCertAuthWithRootCerts
* validating via cert chain and root cert from chain, is a gray area. so only consider the basic test via client cert vs cert

CBL-1510: Remove the root certs vs clientAuth

---

CouchbaseLite.xcodeproj/project.pbxproj
Objective-C/Internal/main.m

* add a module initializer
* called the c4log_fatalException from it.
* ref: CBL-1852, CBL-1567

CBL-1567: Module initializer

---

Objective-C/CBLQueryExpression.h
Objective-C/CBLQueryExpression.m
Objective-C/Internal/CBLUnaryExpression.h
Objective-C/Internal/CBLUnaryExpression.m
Objective-C/Tests/DatabaseEncryptionTest.m
Objective-C/Tests/PredictiveQueryTest.m
Objective-C/Tests/QueryTest+Main.m

* add new API isValued/isNotValued API
* deprecate isNullOrMissing/isNotNullOrMissing
* update the unit tests

isValued/isNotValued API

---

CouchbaseLite.xcodeproj/project.pbxproj
Objective-C/CBLDatabase.h
Objective-C/CBLDatabase.mm
Objective-C/CBLQuery.mm
Objective-C/Internal/CBLQuery+N.h
Objective-C/Tests/QueryTest+Main.m

* createQuery added
* add a sanity unit test

Support N1QL Query (ObjC)

---

CouchbaseLite.xcodeproj/project.pbxproj
Swift/CouchbaseLiteSwift-EE.modulemap
Swift/CouchbaseLiteSwift.modulemap
Swift/Database.swift
Swift/Query.swift
Swift/Tests/QueryTest.swift

* select query addition with a basic sanity unit test

Select N1QL Query Swift

---

CouchbaseLite.xcodeproj/project.pbxproj
Objective-C/Tests/DatabaseTest.m
Swift/CouchbaseLiteSwift-EE.modulemap
Swift/CouchbaseLiteSwift.modulemap
Swift/Database+Query.swift
Swift/IndexConfiguration.swift
Swift/Tests/DatabaseTest.swift

* create index for swift
* need to include a unit test too & add IndexConfiguration.swift file to project

Support N1QL Create Index Swift

---

Swift/Tests/QueryTest.swift

* Submodule update with the LiteCore fix
* Unit test to validate the failure.

CBL-2036: Add unit test to validate 

---

Objective-C/Tests/DatabaseTest.m
Objective-C/Tests/ReplicatorTest+CustomConflict.m

* ignoreException for c4doc_update and c4doc_resolve
CBL-2167
CBL-1928

CBL-1928: enable the test with ignoreException

---

Objective-C/Internal/CBLFleece.mm

* in case of dictionary and array the valueWouldChange returns true;
* but the check was mistakenly check for only CBLArray and not CBLDictionary
* fixes: #2865

fix: valueWouldChange comparison

---

Objective-C/Internal/CBLStatus.mm
Objective-C/Tests/MiscCppTest.mm

* Update the error codes in the CF to C4 conversion function

Update the POSIX error codes

---

Swift/Tests/QueryTest.swift

* add unit test for FTS Match ( JSON & N1QL )
* N1QL back tick is for quoting it as identifier

test: add FTS Match for JSON & N1QL

---

Swift/Tests/QueryTest.swift

CBL-2284: Verify the offset without limit unit test

---

Objective-C/Tests/DatabaseTest.m
Objective-C/Tests/QueryTest+Meta.m
Objective-C/Tests/ReplicatorTest+MessageEndPoint.m

Jira issues: CBL-2404, CBL-2392, CBL-2364

Disable the flaky tests

---

Objective-C/CBLDatabase.h
Objective-C/Tests/ReplicatorTest+Main.m
Swift/Database.swift

Provide note about copying encrypted database in API doc

CBL-2376: Provide note about copying encrypted database in API doc

---

Objective-C/CBLReplicatorConfiguration.h
Swift/ReplicatorConfiguration.swift

Add note about notification when disabling autoPurge

CBL-2437: Add note about notification when disabling autoPurge

---

Objective-C/Tests/CBLTestCase.h
Objective-C/Tests/CBLTestCase.m
Objective-C/Tests/DatabaseTest.m
Objective-C/Tests/QueryTest+Meta.m
Objective-C/Tests/ReplicatorTest+Main.m
Objective-C/Tests/ReplicatorTest+MessageEndPoint.m
Objective-C/Tests/URLEndpointListenerTest.m
Swift/Tests/CBLTestCase.swift
Swift/Tests/DatabaseTest.swift
Swift/Tests/URLEndpointListenerTest.swift

* disable unit tests
* fix unit test failure

CBL-2442: Backport to Lithium

---

Objective-C/Tests/DocumentExpirationTest.m

* will use this PR to check whether there are any more tests failing!
* will backport to Lithium as well.

disable test: doc expiry CBL-2392

---

Scripts/build_xcframework.sh
Scripts/generate_release_zip.sh

* remove combined/framework build setup, since we will only create XCFramework from now on.
* keep --nodocs flag for API docs free binary creation.
* update the instrucments command to use xctrace
* ~~we need this to be cherry-picked to Lithium Beta03 as well~~.

Update build script

---

Objective-C/Internal/Replicator/CBLWebSocket.mm

* Extract the cookie from the header dictionary and add it to the cookie string with Session/LC cookies
* Fix: CBL-2418

Add cookie from header dict

---

Objective-C/Tests/ReplicatorTest+PendingDocIds.m
Swift/Tests/ReplicatorTest+PendingDocIds.swift

Enabling the test, since the CBL-2448 is closed.

enable unit test

---

Objective-C/CBLBlob.h
Objective-C/Tests/DocumentTest.m
Swift/Blob.swift
Swift/Tests/DocumentTest.swift

* add documentatation for each properties
* expose the swift corresponding property keys
* update tests to include those values instead of the hard coded values
* fixes: CBL-2549

CBL-2549: Expose blob type property in swift

---

CouchbaseLite.xcodeproj/project.pbxproj
Objective-C/CBLErrors.h
Swift/Errors.swift
Swift/Tests/DatabaseEncryptionTest.swift
Swift/Tests/DatabaseTest.swift
Swift/Tests/DocumentExpirationTest.swift
Swift/Tests/DocumentTest.swift
Swift/Tests/QueryTest.swift
Swift/Tests/ReplicatorTest+CustomConflict.swift
Swift/Tests/ReplicatorTest.swift
Swift/Tests/TLSIdentityTest.swift

* Error description in swift & objc

CBL-2546: Error description in swift & objc

---

CouchbaseLite.xcodeproj/project.pbxproj
Objective-C/CBLDatabase.h
Objective-C/CBLDatabase.mm
Objective-C/CBLQuery.mm
Objective-C/Internal/CBLQuery+N1QL.h
Objective-C/Tests/QueryTest+Main.m
Swift/CouchbaseLiteSwift-EE.modulemap
Swift/CouchbaseLiteSwift.modulemap
Swift/Database+Query.swift
Swift/Database.swift
Swift/Query.swift
Swift/Tests/QueryTest.swift

Back-port the two commits: #2896 #2901

CBL-2581: Backport to lithium

---

Objective-C/CBLDatabase.h

Add note on Save/Get Blob APIs

CBL-2633: Add note on Save/Get Blob APIs

---

Objective-C/CBLDatabase.mm
Objective-C/Internal/CBLDatabase+Internal.h
Objective-C/Internal/Replicator/CBLWebSocket.mm

CBL: 2657: Fix the crash during connect/close race -11072

---

README.md

* should we need to update the class reference documentation to this latest?

Update README to 3.x

---

CouchbaseLite.xcodeproj/project.pbxproj
Scripts/generate_objc_release_zip.sh
Scripts/generate_swift_release_zip.sh

* separated out the swift and objc
* this require enterprise script to updated similarily
* ref: CBL-654
Note: This change requires changes in the Jenkins config

Simplify script

---

Objective-C/CBLLog.mm

SQL = Database;
Changes = Replicator;
BLIPMessages = Network;
TLS = Network
Zip=Network

Enable all log domains and map it with existing domains

---

Objective-C/CBLDocument.mm
Objective-C/Tests/ReplicatorTest+Main.m

Reverts couchbase/couchbase-lite-ios#2941
Need to update the swift package manifest file and then will commit the change to 3.0.1

Revert "CBL-2825: Fix: [lithium] Attachment missing when doc updated"

---

Objective-C/CBLMutableArray.mm
Objective-C/CBLMutableDictionary.mm
Objective-C/CBLReplicator.mm
Objective-C/Internal/CBLFleece.hh
Objective-C/Internal/CBLFleece.mm
Objective-C/Internal/CBLNewDictionary.mm
Objective-C/Internal/Replicator/CBLWebSocket.mm

* Replace the FLValue_FromData() with FLDoc_FromData()
* Include FLExpert.hh for using the AllocedDict

Fleece API update

---

Objective-C/Tests/DatabaseTest.m
Objective-C/Tests/MessageEndpointTest.m
Objective-C/Tests/ReplicatorTest+MessageEndPoint.m
Swift/Tests/LogTest.swift

* Xcode 13.3 build errors.
* Dsiable all the MessageEndpoint tests - CBL-2959

Fix build issues

---

Objective-C/CBLDatabase.mm
Objective-C/Internal/Foundation+CBL.h
Objective-C/Internal/Foundation+CBL.mm
Objective-C/Tests/DatabaseTest.m
Objective-C/Tests/ReplicatorTest+MessageEndPoint.m

* fix crash with hostname as deallocated silce
* some minor test fixes
cherry-pick the changes to other branches

fix crash with hostname as deallocated silce

---

CouchbaseLite.xcodeproj/project.pbxproj
Objective-C/CBLCollection.h
Objective-C/CBLCollection.mm
Objective-C/CBLDatabase.h
Objective-C/CBLDatabase.mm
Objective-C/CBLScope.m
Objective-C/CBLScope.mm
Objective-C/Internal/CBLCollection+Internal.h
Objective-C/Internal/CBLScope+Internal.h
Objective-C/Tests/DatabaseTest.m
Objective-C/Tests/MessageEndpointTest.m
Objective-C/Tests/ReplicatorTest+CustomConflict.m
Objective-C/Tests/ReplicatorTest+PendingDocIds.m
Objective-C/Tests/URLEndpointListenerTest.m

* Add collection index functions & unit tests to validate. 
* Add collection management functions & unit tests to validate.
* CBLCollection internal constructor updated. 
* Kept database property in Scope & Collection. 
* Code cleanup - header include ordered

Collection Indexable functions

---

Objective-C/CBLCollection.mm
Objective-C/CBLCollectionChange.m
Objective-C/CBLCollectionChangeObservable.h
Objective-C/CBLDatabase.mm
Objective-C/CBLQuery.mm
Objective-C/CBLReplicator.mm
Objective-C/Internal/CBLChangeListenerToken.h
Objective-C/Internal/CBLChangeListenerToken.m
Objective-C/Internal/CBLChangeNotifier.h
Objective-C/Internal/CBLChangeNotifier.m
Objective-C/Internal/CBLCollection+Internal.h
Objective-C/Internal/CBLDatabase+Internal.h
Objective-C/Internal/CBLQuery+Internal.h
Objective-C/Tests/DatabaseTest.m
Swift/Collection.swift
Swift/CollectionChangeObservable.swift

* Add delegate to listener token class and CBLDatabase/CBLCollection/CBLReplicator/CBLQuery classes now implements it.
* now removeToken function does calls the removeChangeListener callback.

CBL-3309: Collection change listener objc 

---

Objective-C/CBLCollection.mm
Objective-C/CBLDatabase.mm
Objective-C/Internal/CBLCollection+Internal.h
Objective-C/Internal/CBLDatabase+Internal.h
Objective-C/Internal/CBLScope+Internal.h

* Default collection cached
* Document expiry functions added
* Redirect the Database -> Collections - indexes, doc expiry

Collection cached + Doc Expiry

---

Objective-C/CBLArray.mm
Objective-C/CBLBlob.mm
Objective-C/CBLCollection.mm
Objective-C/CBLDatabase.mm
Objective-C/CBLDictionary.mm
Objective-C/CBLDocument.mm
Objective-C/CBLDocumentChange.m
Objective-C/Internal/CBLCollection+Internal.h
Objective-C/Internal/CBLDatabase+Internal.h
Objective-C/Internal/CBLDocument+Internal.h
Objective-C/Internal/CBLDocumentChangeNotifier.mm

* more handling of db instance being nil needs to be added

Cyclic reference

---

CouchbaseLite.xcodeproj/project.pbxproj
Objective-C/CBLDatabase.mm
Objective-C/Tests/CollectionTest.m

* implement the get scope/ scope by name API
* unit tests for default scope/collection

test: default scope/collection

---

Objective-C/CBLCollection.mm
Objective-C/Tests/CBLTestCase.h
Objective-C/Tests/CBLTestCase.m
Objective-C/Tests/CollectionTest.m

* Add unit tests collection
* Some helper methods for easy creating docs

test: Collection unit tests + collection count 

---

Objective-C/CBLDatabase.mm
Objective-C/Tests/CBLTestCase.h
Objective-C/Tests/CBLTestCase.m
Objective-C/Tests/CollectionTest.m
Objective-C/Tests/DatabaseTest.m

* Collections and Cross Database Instance
* Listeners
* Need to cleanup the listener unit test.

test: Collections and Cross Database Instance & Listeners

---

Objective-C/CBLDatabase.mm
Objective-C/Tests/CollectionTest.m

* Add unit tests to handle the deleted/closed db/collections/defaultCollections scenarios
* Fixed some issues on the way

test: Deleted/Closed db/collection/defaultCollection scenarios

---

Objective-C/CBLCollection.mm
Objective-C/CBLReplicator.mm
Objective-C/Internal/CBLCollection+Internal.h
Objective-C/Tests/ReplicatorTest+PendingDocIds.m
Swift/Replicator.swift

* Add implementation to include the pending doc ids implementation with collection
* Update unit tests to validate both methods

feat: pending document ids with collection

---

CouchbaseLite.xcodeproj/project.pbxproj
Objective-C/CBLQuery.mm
Objective-C/CBLQueryDataSource.m
Objective-C/Tests/CBLTestCase.h
Objective-C/Tests/CBLTestCase.m
Objective-C/Tests/PredictiveQueryTest.m
Objective-C/Tests/QueryTest+Collection.m

* Query support collection. 
* Add unit tests for validating the SQL++ query, Query

[feat] [test] [objc] query support collection & unit tests

---

CouchbaseLite.xcodeproj/project.pbxproj
Objective-C/CBLCollection.mm
Objective-C/CBLCollectionConfiguration.m
Objective-C/CBLDocumentReplication.mm
Objective-C/CBLReplicator.mm
Objective-C/Internal/Replicator/CBLCollectionConfiguration+Internal.h
Objective-C/Tests/ReplicatorTest+Main.m

* Collection configs are passed to ReplicatorParams
* Filter & ConflictResolver, get the collection if LC returns collection-spec, or use defaultCollection.

[feat] [objc] replicator collection LC API update

---

Swift/Tests/CBLTestCase.swift
Swift/Tests/CollectionTest.swift

* unit tests for 8.3 collections & cross database instance
* unit tests for 8.4 listeners

[test] [swift] collections & cross db instance + listeners

---

CouchbaseLite.xcodeproj/project.pbxproj
Objective-C/CBLQuery.mm
Objective-C/Internal/CBLQuery+JSON.h
Swift/DataSource.swift
Swift/Select.swift
Swift/Tests/CBLTestCase.swift
Swift/Tests/QueryTest+Collection.swift

[test] [swift] SQL++, QueryBuilder

---

CouchbaseLite.xcodeproj/project.pbxproj
Objective-C/Internal/CBLCollection+Swift.h
Swift/Collection.swift
Swift/CollectionConfiguration.swift
Swift/ReplicatorConfiguration.swift
Swift/Tests/ReplicatorTest+Collection.swift
Swift/Tests/ReplicatorTest+CustomConflict.swift
Swift/Tests/ReplicatorTest.swift

* Replicator config collection update
* CBL-3508

[feat] [test] [swift] replicator config collection update

---

Objective-C/CBLCollectionConfiguration.m
Objective-C/CBLReplicator.mm
Objective-C/Tests/DatabaseTest.m
Objective-C/Tests/MessageEndpointTest.m
Objective-C/Tests/ReplicatorTest+PendingDocIds.m
Swift/Tests/DatabaseTest.swift

* fixes made to update the lite core.
* disabled the known issues

Update LiteCore submodule to 190

---

CouchbaseLite.xcodeproj/project.pbxproj
Objective-C/CBLCollectionConfiguration.h
Objective-C/Internal/Replicator/CBLCollectionConfiguration+Swift.h
Objective-C/Internal/Replicator/CBLCollectionConfiguration+Swift.m
Objective-C/Internal/Replicator/CBLConflictResolverBridge.h
Objective-C/Internal/Replicator/CBLConflictResolverBridge.m
Objective-C/Tests/ReplicatorTest+Collection.m
Swift/CollectionConfiguration.swift
Swift/CouchbaseLiteSwift-EE.modulemap
Swift/CouchbaseLiteSwift.modulemap
Swift/ReplicatorConfiguration.swift
Swift/Tests/CBLTestCase.swift
Swift/Tests/ReplicatorTest+Collection.swift

* Add swift replicator unit tests
* Pass the collections from ReplicatorConfig to CBLReplicatorConfig, with CollectionConfig

[test] [swift] Replicator test

---

CouchbaseLite.xcodeproj/project.pbxproj
Objective-C/Tests/MessageEndpointTest.m
Objective-C/Tests/ReplicatorTest+Collection.m
Objective-C/Tests/URLEndpointListenerTest+Collection.m
Objective-C/Tests/URLEndpointListenerTest.h
Objective-C/Tests/URLEndpointListenerTest.m
Swift/Tests/ReplicatorTest+Collection.swift

* Add 8.15 MessageEndpointListener unit tests. 
* Add 8.16 URLEndpointListener unit tests.

[test] [objc] URL/Message -EndpointListener unit tests

---

Objective-C/Tests/ReplicatorTest+Collection.m
Objective-C/Tests/ReplicatorTest+CustomConflict.m
Swift/Tests/ReplicatorTest+Collection.swift

[test] [swift] [objc] testCollectionDocumentReplicationEvents

---

Objective-C/CBLCollection.mm
Objective-C/CBLDatabase.mm
Objective-C/CBLDocument.mm
Objective-C/CBLReplicator.mm
Objective-C/CBLScope.mm

* Add detailed verbose logs
* include the fullDecription for verbose log with pointer address

[feat] [CBL-3297] Add logs

---

Objective-C/CBLCollection.mm
Objective-C/Internal/CBLDocumentChangeNotifier.mm
Objective-C/Tests/CollectionTest.m
Objective-C/Tests/ReplicatorTest+CustomConflict.m
Swift/Tests/CollectionTest.swift
Swift/Tests/ReplicatorTest+CustomConflict.swift

* API updates, and enable the tests CBL-3625

[fix] LiteCore 225

---

Swift/ArrayObject.swift
Swift/Blob.swift
Swift/Collection.swift
Swift/CollectionConfiguration.swift
Swift/DataConverter.swift
Swift/DataSource.swift
Swift/Database+Query.swift
Swift/Database.swift
Swift/DictionaryObject.swift
Swift/Document.swift
Swift/DocumentFragment.swift
Swift/Fragment.swift
Swift/ListenerToken.swift
Swift/MutableArrayObject.swift
Swift/MutableDictionaryObject.swift
Swift/MutableDocument.swift
Swift/MutableFragment.swift
Swift/Query.swift
Swift/Replicator.swift
Swift/ReplicatorConfiguration.swift
Swift/Scope.swift

[fix] remove the underscore style from swift

---

Objective-C/CBLDatabase.h
Objective-C/CBLScope.mm
Objective-C/Tests/CBLTestCase.h
Objective-C/Tests/CollectionTest.m

* scope is now equatable
* some tests updates

[test] [feat] fixes 

---

Objective-C/CBLDocument.mm

- Remove the unused function
- https://issues.couchbase.com/browse/CBL-3387

CBL-3387: Remove the unused function

---

Objective-C/CBLReplicator.mm
Objective-C/CBLReplicatorConfiguration.m
Objective-C/Tests/CBLTestCase.h
Objective-C/Tests/CBLTestCase.m
Objective-C/Tests/MessageEndpointTest.m
Objective-C/Tests/PredictiveQueryTest.m
Objective-C/Tests/ReplicatorTest+Collection.m
Swift/Tests/MessageEndpointTest.swift
Swift/Tests/PredictiveQueryTest.swift
Swift/Tests/ReplicatorTest+Collection.swift

* More fixes
* Test fixes for stabilising the unit tests.

More test improvements

---

Objective-C/CBLQueryCollation.h
Swift/Collation.swift

* Unicode aware & locale null will use system locale info
* ref: CBL-3483

[doc] Unicode aware & locale null will use system locale info

---

Scripts/generate_objc_release_zip.sh
Scripts/generate_swift_release_zip.sh

* rename the coverage zip name for objc/swift to avoid overwriting.
* choose the latest simulator using simctl

[fix] script minor updates

---

Objective-C/Tests/ReplicatorTest+Collection.m
Swift/Tests/ReplicatorTest+Collection.swift

* It got failed intermittently due to the change in order. Assuming the expected change listener 3rd one fired during 1st/2nd. And the 1st/2nd fired during 3rd. Since the sequence is irrelevant, we updated to use the document count and make sure its returning correct error code.
* CBL-3710
* Reference: to Jenkins job: couchbase-lite-ios-objc-edition-build/4541/

[fix] stabilize the testCollectionConflictResolver test

---

Objective-C/Internal/CBLCollection+Internal.h

update the string to use ErrorMessage constant

Update string to ErrorMessage

---

Objective-C/CBLDatabase.mm
Objective-C/Tests/DocumentTest.m

[fix] Database.getBlob() not updating the size

---

Objective-C/CBLDocument.mm
Objective-C/CBLRemoteDatabase.mm
Objective-C/CBLReplicator.mm
Objective-C/Internal/CBLDocument+Internal.h
Objective-C/Internal/Replicator/CBLWebSocket.mm
Objective-C/Tests/RemoteDatabaseTest.m
Scripts/pull_request_build.sh

* make changes to adopt the new listener config

Fix: [connected client] Update LC APIs

---

Objective-C/Tests/QueryTest+Main.m
Objective-C/Tests/QueryTest+Meta.m
Scripts/generate_release_zip.sh
Scripts/pull_request_build.sh

* get the latest from simctl and use it instead of hard coding it
* disable the unit tests which are consistently failing, with Jira ticket.

[fix] simulator issue + unit test failures are disabled 

---

Objective-C/Internal/Replicator/CBLWebSocket.mm

* more logs.
* enforce negotiatedSSL as security level.
* print IPv4 address before socket connect.

[cherry-pick] Network interface more logs + securityLevel update (#3037)

---

Objective-C/Internal/Replicator/CBLWebSocket.mm
Objective-C/Tests/PredictiveQueryTest.m
Scripts/generate_release_zip.sh
Swift/Tests/PredictiveQueryTest.swift

[lithium] more binary fixes

---

Objective-C/Tests/ReplicatorTest+CustomConflict.m

cherry-pick: e637c27a151dc8683a5ffefb6a1966d8ea73979f

---

Objective-C/Tests/URLEndpointListenerTest.m
Swift/Tests/URLEndpointListenerTest.swift

CBL-3877: test failure and disabled it!

disable the tests - due to consistent failure(or hangs)

---

Objective-C/Tests/ReplicatorTest+CustomConflict.m

disable the double conflict resolution test failure as well

---

Objective-C/CBLReplicatorConfiguration.h
Swift/ReplicatorConfiguration.swift

CBL-3844: update docs: auto purge won't work with docIDs filter

---

Objective-C/Internal/Replicator/CBLWebSocket.h
Objective-C/Internal/Replicator/CBLWebSocket.mm
Objective-C/Tests/ReplicatorTest+Main.m

* iterate through the available network interfaces and IPAddresses of each interfaces and choose the network interface name
* continue with interface name from there.
* CBL-3102

CBL-3102: [feat] network interface as IPAddress / interface name

---

Objective-C/CBLIndex.h
Objective-C/CBLIndex.m
Objective-C/Internal/CBLIndex+Internal.h
Objective-C/Tests/CollectionTest.m
Objective-C/Tests/DatabaseTest.m
Objective-C/Tests/PredictiveQueryTest.m
Swift/Index.swift
Swift/IndexConfiguration.swift
Swift/Tests/DatabaseTest.swift

* this will allow the collection API to use Index and IndexConfig interchangably
* CBL-3859

Index inherited from IndexConfig 

---

Objective-C/CBLErrors.h
Objective-C/Internal/Replicator/CBLWebSocket.mm
Swift/Errors.swift

* set the unknown interface error when failed to find the interface

CBL-3917: Add CBLErrorUnknownInterface

---

Objective-C/Tests/CollectionTest.m
Swift/Tests/CollectionTest.swift

-Subproject commit 3b1fe0d6fe46a5a4e1655dbe6f42e89154a189dd 
+Subproject commit fbbf27c297e3b46fd63a9c94340b69734354f7c9

CBL-3980: Not allow Default collection delete + LiteCore 301

---

CouchbaseLite.xcodeproj/project.pbxproj
Objective-C/CBLReplicator.mm
Objective-C/CBLReplicatorConfiguration.h
Objective-C/CBLReplicatorConfiguration.m
Objective-C/Internal/Replicator/CBLDNSService.h
Objective-C/Internal/Replicator/CBLDNSService.mm
Objective-C/Internal/Replicator/CBLNWWebSocket.h
Objective-C/Internal/Replicator/CBLNWWebSocket.mm
Objective-C/Internal/Replicator/CBLWebSocket.mm
Swift/ReplicatorConfiguration.swift

This reverts commit afd6398faec97416b069b38165c89ed57f8aacf4.
This commit will keep the experimental changes we did in VF branch

[VF/3.0.2.1] Revert "Revert experimental API (#3074)"

---

CouchbaseLite.xcodeproj/project.pbxproj
Objective-C/Internal/Replicator/CBLDNSService.h
Objective-C/Internal/Replicator/CBLDNSService.mm
Objective-C/Internal/Replicator/CBLWebSocket.mm

* getaddrinfo is using default device network interface, so updated to use the DNSService

Update DNS resolution to use DNSService

---

Objective-C/Tests/ReplicatorTest+Main.m

* Already done different formats and parsing logic
* Once parsed, will save to LiteCore and retrive when sendWebSocketRequest

CBL-3948: [test] Update test to validate more date formats

---

CouchbaseLite.xcodeproj/project.pbxproj
Objective-C/CBLQueryExpression.h
Objective-C/CBLQueryExpression.m
Objective-C/CBLQueryFullTextFunction.h
Objective-C/CBLQueryFullTextFunction.m
Objective-C/CBLQueryFullTextIndexExpression.h
Objective-C/CBLQueryFullTextIndexExpression.m
Objective-C/CBLQueryFullTextIndexExpressionProtocol.h
Objective-C/CouchbaseLite.h
Objective-C/Tests/DatabaseTest.m

* Implement the FullTextIndexExpression
* Add unit test objc
* Add unit test for issue_cbl_3994

CBL-4008: [objc] QueryBuilders FullTextIndexExpression

---

CouchbaseLite.xcodeproj/project.pbxproj
Objective-C/CBLCollection.mm
Objective-C/CBLDatabase.mm
Objective-C/CBLIndex.h
Objective-C/CBLIndex.m
Objective-C/CBLIndexable.h
Objective-C/CBLQueryFullTextFunction.h
Objective-C/CBLQueryFullTextFunction.m
Objective-C/Internal/CBLIndex+Internal.h
Objective-C/Tests/DatabaseTest.m
Swift/ArrayExpressionSatisfies.swift
Swift/Collection.swift
Swift/CouchbaseLiteSwift-EE.modulemap
Swift/CouchbaseLiteSwift.modulemap
Swift/Expression.swift
Swift/FullTextFunction.swift
Swift/FullTextIndexExpression.swift
Swift/Index.swift
Swift/IndexConfiguration.swift
Swift/Indexable.swift
Swift/Tests/DatabaseTest.swift

* Implement the full text index expression protocol and related
* reference: f6ce1ba5e656418cfe837d671ee86c2e37d5f701 & #3085

CBL-4008: [swift] FullTextIndexExpression

---

Objective-C/Internal/Replicator/CBLWebSocket.mm

ref: https://github.com/couchbase/couchbase-lite-ios/pull/3067/commits/789a6bdd29047f6d94008b11cbf6775f58cac919
copied the log cleanup

CBL-3986: Cleanup log messages

---

CouchbaseLite.xcodeproj/project.pbxproj
Objective-C/Internal/Replicator/CBLDNSService.h
Objective-C/Internal/Replicator/CBLDNSService.mm
Objective-C/Internal/Replicator/CBLWebSocket.mm

https://github.com/couchbase/couchbase-lite-ios/commit/5222965553886aef241d94f1741f76d78c424edc
https://github.com/couchbase/couchbase-lite-ios/commit/10438329fedae00e7382c77b2d9f7e11e521f31a

CBL-4116: port DNS resolution from 3.0.7

---

Objective-C/CBLDatabase.mm
Objective-C/CBLDefaults.h
Objective-C/CBLDefaults.m
Objective-C/CBLReplicatorConfiguration.h
Objective-C/CBLReplicatorConfiguration.m
Objective-C/Internal/CBLDatabase+Internal.h
Objective-C/Internal/Replicator/CBLWebSocket.mm
Swift/Defaults.swift
Swift/ReplicatorConfiguration.swift

Added acceptParrentDomainCookies config to ReplicatorConfiguration

CBL-4120 : Add acceptParentDomainCookies config

---

Objective-C/Tests/QueryTest+Collection.m
Swift/Tests/QueryTest+Collection.swift

Added Select All Result Key Tests according to section 8.11.10 in Scope and Collection API spec.

CBL-4162 : Add Select All Result Key Tests

---

Objective-C/Internal/CBLCollection+Internal.h
Objective-C/Tests/DatabaseTest.m
Objective-C/Tests/ReplicatorTest+CustomConflict.m
Objective-C/Tests/ReplicatorTest+Main.m
Objective-C/Tests/ReplicatorTest+PendingDocIds.m
Objective-C/Tests/URLEndpointListenerTest+Main.m
Swift/Tests/DatabaseTest.swift
Swift/Tests/NotificationTest.swift
Swift/Tests/ReplicatorTest.swift

* Re-enabled tests for issues that have been fixed.
* Removed ReplicatorTest+PendingDocIds’s _testCollection as it doesn’t seem to test anything and the marked issue was fixed.

CBL-4209 : Re-enabled tests for issues that have been fixed

---

Objective-C/CBLCollection.h
Objective-C/CBLDatabase.h
Swift/Collection.swift
Swift/Database+Query.swift
Swift/Database.swift

Updated Document and Index API docs in Database class to refer to default collection instead of database.

CBL-4332 : Update Document and Index API docs in Database class

---

Objective-C/Tests/ReplicatorTest+Main.m
Objective-C/Tests/ReplicatorTest+PendingDocIds.m

* Reenabled some replicator tests as their underlining issues have been fixed.
* Fixed and simplified pending document id tests.

CBL-4207 : Re-enabled replicator tests

---

Objective-C/Tests/ReplicatorTest+PendingDocIds.m
Swift/Tests/ReplicatorTest+PendingDocIds.swift
Swift/Tests/ReplicatorTest.swift

Fixed and simplified pending document tests in Swift.

CBL-4207 : Re-enabled pending document tests in Swift

---

xcconfigs/Project.xcconfig

* Updated LiteCore to 3.2.0-6
* Bumped version number in Project.xcconfig to 3.2.0

Update LiteCore to 3.2.0-6

---

Objective-C/Tests/ReplicatorTest+Main.m

* Updated LiteCore to 3.1-356
* Removed the workaround for CBL-4391

Update LiteCore to 3.1-356

---

Package.swift
README.md

Update Swift Package and README for 3.1 Release.

Update Swift Package and README

---

Swift/Database.swift

- update deprecation warning messages from Database API
- ported from 8d6500088c1fd2d36ba86610309a90f83c64dd37 in master branch

CBL-4511: Update Database API deprecation messages

---

Scripts/pull_request_build.sh

- it builds for macos
- it builds and test for ios

CBL-4688: Jenkins PR Validation (EE) should run on both iOS and macOS

---

Objective-C/Internal/Replicator/CBLTrustCheck.mm
Objective-C/Internal/main.m

Besides this, on the EE side, LiteCore EE needs to be updated to [2798a6e00ecefbad4cfc3e881f11954a23bdc6e8](https://github.com/couchbase/couchbase-lite-core-EE/commit/2798a6e00ecefbad4cfc3e881f11954a23bdc6e8) - it will be included in 3.1.x

Build with XCode 15

---

Objective-C/Tests/ReplicatorTest+Collection.m
Swift/Tests/ReplicatorTest+Collection.swift

Fixed the condition check whether the document replication should report conflict error or not.

Fix flaky testCollectionConflictResolver

---

Objective-C/Internal/Replicator/CBLWebSocket.mm

* Ported the fix (159c4ee10ada7af91162f74281d7d18537589886) from release/3.1 branch.
* It is possible that the dispose() function is called by the c4socket before the disconnect() function is called. One of the cases is when c4socket calls the dispose() as the close timeout is reached.
* The fix ensures that when the dispose() is called, the disconnect() function will be called if the connection hasn’t been not closed yet.
* The fix also make sure that the crash doesn’t happen after the c4socket is freed while there are pending tasks in the queue being run at the same time and might access it after it’s freed. This requires to use a lock to prevent this.
* Added message to the assertions.

CBL-5418 : Ensure to disconnect from the remote before CBLWebSocket being dealloc

---

Objective-C/CBLCollection.mm
Objective-C/CBLDatabase.mm
Objective-C/CBLReplicator.mm
Objective-C/Tests/CBLTestCase.m

* Updated LiteCore to 3.2.0-148
* Added log prefix id param when creating the c4repl. Will try to shorten the id later.
* Simplified log in CBLDatabase and CBLCollection a bit.

Update LiteCore to 3.2.0-148

---

Objective-C/Internal/CBLQueryObserver.m

this was caught via [QueryTest_Main testCreateAndRemoveLiveQueriesConcurrently]

CBL-5824: Keep query reference if not stopped

---

Objective-C/Tests/UnnestArrayIndexTest.m
Swift/Tests/UnnestArrayTest.swift

- update LiteCore to 4.0.0-28
- re-enable array test [CBL-6441](https://issues.couchbase.com/browse/CBL-6441)
[CBL-6441]: https://couchbasecloud.atlassian.net/browse/CBL-6441?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

4.0.0 beta

---

Swift/Replicator.swift
Swift/Tests/PublisherTest.swift

- [CBL-6712](https://jira.issues.couchbase.com/browse/CBL-6712) Replicator Change
- [CBL-6713](https://jira.issues.couchbase.com/browse/CBL-6713) Document Replication Change
Includes tests. Will add the API doc for all the publishers in the next/last PR for the Query Publisher
[CBL-6712]: https://couchbasecloud.atlassian.net/browse/CBL-6712?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[CBL-6713]: https://couchbasecloud.atlassian.net/browse/CBL-6713?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Replicator.publish() Swift Enhancement APIs

---

CouchbaseLite.xcodeproj/project.pbxproj
Objective-C/Internal/CBLArray+Swift.h
Objective-C/Internal/CBLBlob+Swift.h
Objective-C/Internal/CBLNewDictionary.h
Swift/ArrayObject.swift
Swift/Blob.swift
Swift/DataConverter.swift
Swift/DictionaryObject.swift
Swift/WeakHolder.swift

CBL-7029: Obj-C will hold a strong ref of the new Swift's WeakHolder (#3383)

---

Jenkinsfile
Scripts/pull_request_build_test.sh

* Used mobile-mac-mini agent instead.
* Unlock keychain.
* Companion PR : https://github.com/couchbaselabs/couchbase-lite-ios-ee/pull/269

Update Jenkinsfile to use a new agent and unlock keychain

---

Objective-C/Tests/URLEndpointListenerTest.m
Swift/Tests/URLEndpointListenerTest.swift

Companion PR : https://github.com/couchbaselabs/couchbase-lite-ios-ee/pull/277

CBL-7056 : Reenable URLEndpointListener Tests

---

Objective-C/Tests/MultipeerReplicatorTest.m
Swift/Tests/MultipeerReplicatorTest.swift

* Updated LiteCore to 3.3.0-90.
* Enabled failed tests and remove workaround due to CBL-7099.

CBL-7099 : Update LiteCore to 3.3.0-90

---

Objective-C/Internal/CBLVersion.m
Scripts/get_repo_version.sh

preview: `CouchbaseLite/0-EE (Swift; macOS 15.3.2) Build/0 Commit/fa385155+48022d87+CHANGES LiteCore/3.2.2-EE (c74f8dece2fe5a9a+5886a903115fbec4)`

CBL-7146: userAgent should show correct information about the client type - Enterprise vs Community
